/* eslint-disable */
// Generated by scripts/generate-market-radars.mjs.
import type { MarketRadarDaily } from '../generatedMarketRadars.ts'
export const monthlyMarketRadars: MarketRadarDaily[] = [
  {
    "date": "2026-08-09",
    "slug": "2026-08-09",
    "title": "交易研究雷达 · 2026-08-09",
    "summary": "先锁定本周通胀双节点，再观察 Aptos 热修复透明度与 lnd 候选版迁移风险；只记录可验证事件，不输出仓位指令。",
    "reviewStatus": "automated",
    "generatedAt": "2026-08-09T12:30:00+08:00",
    "events": [
      {
        "id": "us-inflation-releases-2026-08",
        "priority": "P0",
        "status": "scheduled",
        "category": "macro",
        "eventAt": "2026-08-12T20:30:00+08:00",
        "title": "美国 CPI 与 PPI 将在 8 月 12–13 日连续发布",
        "fact": "美国劳工统计局日程显示，7 月 CPI 与实际收入定于 8 月 12 日 08:30 ET 发布，7 月 PPI 定于 8 月 13 日 08:30 ET 发布。",
        "whyWatch": "连续两天的通胀数据可能改变市场对利率路径的判断，并影响美元、权益与加密资产的风险偏好；日程本身不预设数据方向。",
        "assets": [
          "BTC",
          "ETH",
          "SPY",
          "DXY"
        ],
        "watchFor": "发布后只记录官方标题与核心分项方向，并人工核对 BTC、ETH、SPY 与美元指数在 30 分钟和 4 小时窗口的公开行情表现。",
        "invalidation": "若官方调整发布时间，以 BLS 最新日程为准；在数据发布前不把市场传闻或预测值当成事实。",
        "sourceName": "U.S. Bureau of Labor Statistics",
        "sourceUrl": "https://www.bls.gov/schedule/2026/08_sched_list.htm",
        "sourcePublishedAt": "2026-06-10"
      },
      {
        "id": "aptos-node-1-48-6-private-hotfix",
        "priority": "P1",
        "status": "monitoring",
        "category": "crypto",
        "title": "Aptos 1.48.6 热修复要求验证节点升级，但源码未公开",
        "fact": "Aptos 官方发布页将 1.48.6 标为主网热修复，要求验证节点升级、建议全节点升级，同时明确说明这是私有热修复，源码不可用。",
        "whyWatch": "强制性验证节点升级与不可审查源码同时出现，首先是网络运行和供应链透明度事件；它不自动构成 APT 的方向信号。",
        "assets": [
          "APT"
        ],
        "watchFor": "继续观察官方网络状态、验证节点升级反馈、后续公开说明以及是否出现可审查的修复细节。",
        "invalidation": "在没有公开故障说明、网络指标或复盘前，不推断漏洞范围，也不把版本发布等同于链上异常。",
        "sourceName": "Aptos Core Releases",
        "sourceUrl": "https://github.com/aptos-labs/aptos-core/releases/tag/aptos-node-v1.48.6-hotfix",
        "sourcePublishedAt": "2026-08-05"
      },
      {
        "id": "lnd-0-21-2-beta-rc1",
        "priority": "P2",
        "status": "released",
        "category": "crypto",
        "title": "lnd 0.21.2-beta.rc1 修复历史迁移路径，仍只是候选版",
        "fact": "lnd 官方候选版说明修复 KV 到 SQL 的历史支付迁移，以及缺少版本键时被跳过的 waiting-proof 迁移；发布物提供签名和可复现构建验证路径。",
        "whyWatch": "迁移修复关系到 Lightning 节点升级可用性，但候选版的工程进展不能直接外推为 BTC 市场催化。",
        "assets": [
          "BTC"
        ],
        "watchFor": "观察稳定版是否继承修复、节点运营者是否报告启动或迁移问题，以及发布说明是否补充回归边界。",
        "invalidation": "在稳定版发布和真实运营反馈出现前，只把它作为 Lightning 基础设施观察项，不写成价格方向判断。",
        "sourceName": "lnd Releases",
        "sourceUrl": "https://github.com/lightningnetwork/lnd/releases/tag/v0.21.2-beta.rc1",
        "sourcePublishedAt": "2026-08-08"
      }
    ],
    "sourceUrls": [
      "https://www.bls.gov/schedule/2026/08_sched_list.htm",
      "https://github.com/aptos-labs/aptos-core/releases/tag/aptos-node-v1.48.6-hotfix",
      "https://github.com/lightningnetwork/lnd/releases/tag/v0.21.2-beta.rc1"
    ]
  }
]
