import { existsSync, mkdirSync, readdirSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs'
import { parseMarkdownFrontmatter, requireDate, requireFields, requireStringArray } from './frontmatter.mjs'
import { isPublishable } from './public-data-contracts.mjs'
import { assertPublicRadarContent, PUBLIC_RADAR_SECTIONS } from './radar-pipeline.mjs'

const CONTENT_DIR = new URL('../content/radar/', import.meta.url)
const OUTPUT_URL = new URL('../src/data/generatedRadars.ts', import.meta.url)
const OUTPUT_ALL_URL = new URL('../src/data/generatedRadarAll.ts', import.meta.url)
const OUTPUT_LOADER_URL = new URL('../src/data/generatedRadarLoader.ts', import.meta.url)
const OUTPUT_MONTH_DIR = new URL('../src/data/generatedRadarMonths/', import.meta.url)
const LATEST_RADAR_COUNT = 7
const REQUIRED = ['date', 'slug', 'title', 'summary', 'publish', 'reviewStatus', 'generatedAt', 'sourceSections', 'missingSections', 'marketSignals', 'sourceUrls']

if (!existsSync(CONTENT_DIR)) mkdirSync(CONTENT_DIR, { recursive: true })
if (!existsSync(OUTPUT_MONTH_DIR)) mkdirSync(OUTPUT_MONTH_DIR, { recursive: true })

function optionalItem(value, field, fileName) {
  if (value == null) return undefined
  if (typeof value !== 'object' || Array.isArray(value) || !value.title || !value.summary) throw new Error(`${fileName}: ${field} must contain title and summary.`)
  return { title: String(value.title), summary: String(value.summary), sourceUrl: value.sourceUrl ? String(value.sourceUrl) : undefined }
}

function parseRadar(fileName) {
  const { meta } = parseMarkdownFrontmatter(readFileSync(new URL(fileName, CONTENT_DIR), 'utf8'), fileName)
  if (!isPublishable(meta)) return undefined
  requireFields(meta, REQUIRED, fileName)
  requireDate(meta.date, 'date', fileName)
  requireStringArray(meta, 'sourceSections', fileName)
  requireStringArray(meta, 'missingSections', fileName)
  requireStringArray(meta, 'sourceUrls', fileName)
  requireStringArray(meta, 'relatedProjectSlugs', fileName)
  if (meta.reviewStatus !== 'automated') throw new Error(`${fileName}: public radar must be automated.`)
  if (meta.slug !== meta.date) throw new Error(`${fileName}: slug must equal date.`)
  if (meta.sourceSections.length < 3 || meta.sourceSections.some(name => !PUBLIC_RADAR_SECTIONS.includes(name))) throw new Error(`${fileName}: invalid public source coverage.`)
  if (!Array.isArray(meta.marketSignals) || meta.marketSignals.length > 3) throw new Error(`${fileName}: marketSignals must be an array with at most 3 items.`)
  assertPublicRadarContent(meta)

  return {
    date: String(meta.date), slug: String(meta.slug), title: String(meta.title), summary: String(meta.summary),
    reviewStatus: 'automated', generatedAt: String(meta.generatedAt), sourceSections: meta.sourceSections.map(String), missingSections: meta.missingSections.map(String),
    marketSignals: meta.marketSignals.map((item, index) => optionalItem(item, `marketSignals[${index}]`, fileName)),
    aiTip: optionalItem(meta.aiTip, 'aiTip', fileName), web3Design: optionalItem(meta.web3Design, 'web3Design', fileName),
    vibeProject: optionalItem(meta.vibeProject, 'vibeProject', fileName), readingPick: optionalItem(meta.readingPick, 'readingPick', fileName),
    sourceUrls: meta.sourceUrls.map(String), relatedProjectSlugs: meta.relatedProjectSlugs.map(String),
  }
}

const radars = readdirSync(CONTENT_DIR)
  .filter(file => file.endsWith('.md'))
  .sort()
  .map(parseRadar)
  .filter(Boolean)
  .sort((a, b) => b.date.localeCompare(a.date))

const radarsByMonth = new Map()
for (const radar of radars) {
  const month = radar.date.slice(0, 7)
  const monthlyRadars = radarsByMonth.get(month) || []
  monthlyRadars.push(radar)
  radarsByMonth.set(month, monthlyRadars)
}

const months = [...radarsByMonth.keys()].sort().reverse()
const expectedMonthFiles = new Set(months.map(month => `${month}.ts`))
for (const fileName of readdirSync(OUTPUT_MONTH_DIR)) {
  if (fileName.endsWith('.ts') && !expectedMonthFiles.has(fileName)) unlinkSync(new URL(fileName, OUTPUT_MONTH_DIR))
}

for (const month of months) {
  const monthlyOutput = `/* eslint-disable */\n// Generated by scripts/generate-radars.mjs. Do not edit by hand.\n\nimport type { DailyRadar } from '../generatedRadars.ts'\n\nexport const monthlyRadars: DailyRadar[] = ${JSON.stringify(radarsByMonth.get(month), null, 2)}\n`
  writeFileSync(new URL(`${month}.ts`, OUTPUT_MONTH_DIR), monthlyOutput)
}

const radarIndex = radars.map(radar => ({
  date: radar.date,
  slug: radar.slug,
  title: radar.title,
  summary: radar.summary,
  marketSignals: radar.marketSignals.map(item => ({ title: item.title })),
  aiTip: radar.aiTip ? { title: radar.aiTip.title } : undefined,
  web3Design: radar.web3Design ? { title: radar.web3Design.title } : undefined,
  vibeProject: radar.vibeProject ? { title: radar.vibeProject.title } : undefined,
  readingPick: radar.readingPick ? { title: radar.readingPick.title } : undefined,
}))

const output = `/* eslint-disable */\n// Generated by scripts/generate-radars.mjs. Do not edit by hand.\n\nexport interface RadarItem { title: string; summary: string; sourceUrl?: string }\nexport interface DailyRadar { date: string; slug: string; title: string; summary: string; reviewStatus: 'automated'; generatedAt: string; sourceSections: string[]; missingSections: string[]; marketSignals: RadarItem[]; aiTip?: RadarItem; web3Design?: RadarItem; vibeProject?: RadarItem; readingPick?: RadarItem; sourceUrls: string[]; relatedProjectSlugs: string[] }\nexport interface RadarIndexItem { title: string }\nexport interface RadarIndexEntry { date: string; slug: string; title: string; summary: string; marketSignals: RadarIndexItem[]; aiTip?: RadarIndexItem; web3Design?: RadarIndexItem; vibeProject?: RadarIndexItem; readingPick?: RadarIndexItem }\n\nexport const radarIndex: RadarIndexEntry[] = ${JSON.stringify(radarIndex, null, 2)}\n\nexport const latestRadars: DailyRadar[] = ${JSON.stringify(radars.slice(0, LATEST_RADAR_COUNT), null, 2)}\n`
writeFileSync(OUTPUT_URL, output)

const allImports = months.map((month, index) => `import { monthlyRadars as month${index} } from './generatedRadarMonths/${month}.ts'`).join('\n')
const allOutput = `/* eslint-disable */\n// Generated by scripts/generate-radars.mjs. Build-time full archive only.\n\nimport type { DailyRadar } from './generatedRadars.ts'\n${allImports}\n\nexport const dailyRadars: DailyRadar[] = [${months.map((_, index) => `...month${index}`).join(', ')}]\n`
writeFileSync(OUTPUT_ALL_URL, allOutput)

const loaderEntries = months.map(month => `  '${month}': () => import('./generatedRadarMonths/${month}.ts'),`).join('\n')
const loaderOutput = `/* eslint-disable */\n// Generated by scripts/generate-radars.mjs. Do not edit by hand.\n\nimport type { DailyRadar } from './generatedRadars.ts'\n\nconst radarMonthLoaders: Record<string, () => Promise<{ monthlyRadars: DailyRadar[] }>> = {\n${loaderEntries}\n}\n\nexport async function loadRadarBySlug(slug: string): Promise<DailyRadar | undefined> {\n  if (!/^\\d{4}-\\d{2}-\\d{2}$/.test(slug)) return undefined\n  const loadMonth = radarMonthLoaders[slug.slice(0, 7)]\n  if (!loadMonth) return undefined\n  const { monthlyRadars } = await loadMonth()\n  return monthlyRadars.find(radar => radar.slug === slug)\n}\n`
writeFileSync(OUTPUT_LOADER_URL, loaderOutput)

console.log(`Generated ${radars.length} daily radar entries across ${months.length} monthly chunks; ${Math.min(radars.length, LATEST_RADAR_COUNT)} retained for the landing page.`)
