import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { parseMarkdownFrontmatter, requireDate, requireFields, requireStringArray } from './frontmatter.mjs'
import { assertPublicRadarContent, PUBLIC_RADAR_SECTIONS } from './radar-pipeline.mjs'

const CONTENT_DIR = new URL('../content/radar/', import.meta.url)
const OUTPUT_URL = new URL('../src/data/generatedRadars.ts', import.meta.url)
const REQUIRED = ['date', 'slug', 'title', 'summary', 'publish', 'reviewStatus', 'generatedAt', 'sourceSections', 'missingSections', 'marketSignals', 'sourceUrls']

if (!existsSync(CONTENT_DIR)) mkdirSync(CONTENT_DIR, { recursive: true })

function optionalItem(value, field, fileName) {
  if (value == null) return undefined
  if (typeof value !== 'object' || Array.isArray(value) || !value.title || !value.summary) throw new Error(`${fileName}: ${field} must contain title and summary.`)
  return { title: String(value.title), summary: String(value.summary), sourceUrl: value.sourceUrl ? String(value.sourceUrl) : undefined }
}

function parseRadar(fileName) {
  const { meta } = parseMarkdownFrontmatter(readFileSync(new URL(fileName, CONTENT_DIR), 'utf8'), fileName)
  requireFields(meta, REQUIRED, fileName)
  requireDate(meta.date, 'date', fileName)
  requireStringArray(meta, 'sourceSections', fileName)
  requireStringArray(meta, 'missingSections', fileName)
  requireStringArray(meta, 'sourceUrls', fileName)
  requireStringArray(meta, 'relatedProjectSlugs', fileName)
  if (meta.publish !== true || meta.reviewStatus !== 'automated') throw new Error(`${fileName}: radar must be automated and public.`)
  if (meta.slug !== meta.date) throw new Error(`${fileName}: slug must equal date.`)
  if (meta.sourceSections.length < 3 || meta.sourceSections.some(name => !PUBLIC_RADAR_SECTIONS.includes(name))) throw new Error(`${fileName}: invalid public source coverage.`)
  if (!Array.isArray(meta.marketSignals) || meta.marketSignals.length > 3) throw new Error(`${fileName}: marketSignals must be an array with at most 3 items.`)
  assertPublicRadarContent(meta)

  return {
    date: String(meta.date), slug: String(meta.slug), title: String(meta.title), summary: String(meta.summary),
    reviewStatus: 'automated', generatedAt: String(meta.generatedAt), sourceSections: meta.sourceSections.map(String), missingSections: meta.missingSections.map(String),
    marketSignals: meta.marketSignals.map((item, index) => optionalItem(item, `marketSignals[${index}]`, fileName)),
    aiTip: optionalItem(meta.aiTip, 'aiTip', fileName), web3Design: optionalItem(meta.web3Design, 'web3Design', fileName),
    vibeProject: optionalItem(meta.vibeProject, 'vibeProject', fileName), readingPick: optionalItem(meta.readingPick, 'readingPick', fileName),
    sourceUrls: meta.sourceUrls.map(String), relatedProjectSlugs: meta.relatedProjectSlugs.map(String),
  }
}

const radars = readdirSync(CONTENT_DIR).filter(file => file.endsWith('.md')).sort().map(parseRadar).sort((a, b) => b.date.localeCompare(a.date))
const output = `/* eslint-disable */\n// Generated by scripts/generate-radars.mjs. Do not edit by hand.\n\nexport interface RadarItem { title: string; summary: string; sourceUrl?: string }\nexport interface DailyRadar { date: string; slug: string; title: string; summary: string; reviewStatus: 'automated'; generatedAt: string; sourceSections: string[]; missingSections: string[]; marketSignals: RadarItem[]; aiTip?: RadarItem; web3Design?: RadarItem; vibeProject?: RadarItem; readingPick?: RadarItem; sourceUrls: string[]; relatedProjectSlugs: string[] }\n\nexport const dailyRadars: DailyRadar[] = ${JSON.stringify(radars, null, 2)}\n`
writeFileSync(OUTPUT_URL, output)
console.log(`Generated ${radars.length} daily radar entries.`)
