import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { parseMarkdownFrontmatter, requireDate, requireFields, requireStringArray } from './frontmatter.mjs'

const SOURCE_URL = new URL('../content/now/current.md', import.meta.url)
const OUTPUT_URL = new URL('../src/data/generatedNow.ts', import.meta.url)
if (!existsSync(SOURCE_URL)) throw new Error('content/now/current.md does not exist.')

const { meta } = parseMarkdownFrontmatter(readFileSync(SOURCE_URL, 'utf8'), 'content/now/current.md')
requireFields(meta, ['updatedAt', 'headline', 'summary', 'developmentProjectSlugs', 'nextFocus'], 'content/now/current.md')
requireDate(meta.updatedAt, 'updatedAt', 'content/now/current.md')
requireStringArray(meta, 'developmentProjectSlugs', 'content/now/current.md')
requireStringArray(meta, 'nextFocus', 'content/now/current.md')

const snapshot = {
  updatedAt: String(meta.updatedAt), headline: String(meta.headline), summary: String(meta.summary),
  developmentProjectSlugs: meta.developmentProjectSlugs.map(String), nextFocus: meta.nextFocus.map(String),
}
const ageInDays = Math.floor((Date.now() - new Date(`${snapshot.updatedAt}T00:00:00Z`).getTime()) / 86_400_000)
if (ageInDays > 7) {
  console.warn(`Current activity snapshot is ${ageInDays} days old. Refresh content/now/current.md.`)
}

const output = `/* eslint-disable */\n// Generated by scripts/generate-now.mjs. Do not edit by hand.\nexport interface NowSnapshot { updatedAt: string; headline: string; summary: string; developmentProjectSlugs: string[]; nextFocus: string[] }\nexport const nowSnapshot: NowSnapshot = ${JSON.stringify(snapshot, null, 2)}\n`
mkdirSync(new URL('../src/data/', import.meta.url), { recursive: true })
writeFileSync(OUTPUT_URL, output)
console.log('Generated current activity snapshot.')
