/* eslint-disable */
// Generated by scripts/generate-failure-cases.mjs. Do not edit by hand.

export type FailureCategory = 'request-state' | 'node-scanning' | 'deposit' | 'withdrawal-finality' | 'multi-chain' | 'risk-signing' | 'funds-operations'
export type FailurePriority = 'key' | 'common' | 'advanced'
export type FailureEvidenceStatus = 'implemented' | 'partial' | 'design'
export type FailureAction = 'retry' | 'compensate' | 'pause' | 'manual-review'

export interface FailureCase {
  slug: string
  title: string
  category: FailureCategory
  priority: FailurePriority
  services: string[]
  chains: string[]
  actions: FailureAction[]
  evidenceStatus: FailureEvidenceStatus
  symptom: string
  fundRisk: string
  stopLoss: string
  investigate: string[]
  recovery: string[]
  idempotencyBasis: string
  currentBoundary: string
  verificationEvidence: string[]
  relatedArticleSlugs: string[]
  relatedProjectSlugs: string[]
}

export const failureCases: FailureCase[] = [
  {
    "slug": "duplicate-request-id",
    "title": "重复 request_id 或同 ID 不同参数",
    "category": "request-state",
    "priority": "key",
    "services": [
      "wallet-service",
      "risk-service"
    ],
    "chains": [
      "all"
    ],
    "actions": [
      "pause",
      "manual-review"
    ],
    "evidenceStatus": "partial",
    "symptom": "客户端重试或并发请求命中同一 request_id，甚至携带了不同收款地址或金额。",
    "fundRisk": "若只按请求次数处理，可能重复冻结、重复提现或用旧审批签署新内容。",
    "stopLoss": "冻结该 request_id 的状态推进；参数哈希不一致时直接拒绝并告警。",
    "investigate": [
      "对比 request_id、用户、资产、金额、地址和参数哈希",
      "检查冻结记录、审批记录、签名请求与 txHash"
    ],
    "recovery": [
      "同参数重复请求返回原订单与原结果",
      "不同参数冲突进入人工复核，不复用原审批或签名"
    ],
    "idempotencyBasis": "request_id + canonical request payload hash",
    "currentBoundary": "项目已记录 request_id 幂等与审批哈希；完整的冲突恢复演示仍需补齐。",
    "verificationEvidence": [
      "risk-service 幂等标记与审批哈希相关单测已本地验证"
    ],
    "relatedArticleSlugs": [
      "withdrawal-error-handling",
      "wallet-ledger-transaction-mq-consistency"
    ],
    "relatedProjectSlugs": [
      "exchange-wallet-system",
      "web3-wallet-engineer-lab"
    ]
  },
  {
    "slug": "concurrent-state-transition",
    "title": "并发状态推进与 CAS 冲突",
    "category": "request-state",
    "priority": "common",
    "services": [
      "wallet-service"
    ],
    "chains": [
      "all"
    ],
    "actions": [
      "retry",
      "pause"
    ],
    "evidenceStatus": "design",
    "symptom": "多个 worker 同时消费同一订单，或旧版本任务试图覆盖较新的状态。",
    "fundRisk": "重复冻结、重复广播或终态被回退，导致账务与链上事实分叉。",
    "stopLoss": "状态更新必须带版本或前置状态条件；CAS 失败后停止当前动作并重新读取。",
    "investigate": [
      "检查订单 version、updated_at、worker lease 和消息投递次数",
      "确认是否已有签名结果或广播事实"
    ],
    "recovery": [
      "无资金事实时重新加载最新状态后安全重试",
      "已有签名或广播事实时转入结果查询，不重新构建交易"
    ],
    "idempotencyBasis": "order_id + expected_state/version",
    "currentBoundary": "这是生产状态机设计；当前项目尚未形成完整并发失败注入证据。",
    "verificationEvidence": [
      "已有状态机与 worker 入口梳理，CAS 冲突测试待补"
    ],
    "relatedArticleSlugs": [
      "withdrawal-error-handling",
      "wallet-ledger-transaction-mq-consistency"
    ],
    "relatedProjectSlugs": [
      "exchange-wallet-system"
    ]
  },
  {
    "slug": "partial-batch-result",
    "title": "批量签名或广播部分成功",
    "category": "request-state",
    "priority": "advanced",
    "services": [
      "wallet-service",
      "wallet-api",
      "wallet-sign"
    ],
    "chains": [
      "all"
    ],
    "actions": [
      "pause",
      "compensate",
      "manual-review"
    ],
    "evidenceStatus": "design",
    "symptom": "批次超时后只有部分子交易返回签名或 txHash，整体响应却是失败。",
    "fundRisk": "整批重放会让已成功子项重复出金；整批回滚又会丢失真实链上事实。",
    "stopLoss": "拆分到单个订单冻结重放，逐项记录签名、raw transaction 与广播结果。",
    "investigate": [
      "按子订单检查 signer request、raw transaction、txHash 和节点可见性",
      "核对批次响应与持久化明细是否一致"
    ],
    "recovery": [
      "已广播子项进入确认流程",
      "未产生签名或广播事实的子项才允许重新排队",
      "无法判定的子项人工复核"
    ],
    "idempotencyBasis": "batch_id + child_order_id + signed_payload_hash",
    "currentBoundary": "生产设计场景，当前项目未实现批量端到端恢复。",
    "verificationEvidence": [
      "仅完成单笔调用边界梳理"
    ],
    "relatedArticleSlugs": [
      "withdrawal-error-handling"
    ],
    "relatedProjectSlugs": [
      "exchange-wallet-system"
    ]
  },
  {
    "slug": "rpc-lag-rate-limit",
    "title": "节点落后、限流或 RPC timeout",
    "category": "node-scanning",
    "priority": "common",
    "services": [
      "wallet-api"
    ],
    "chains": [
      "all"
    ],
    "actions": [
      "retry",
      "pause"
    ],
    "evidenceStatus": "partial",
    "symptom": "RPC 返回超时、429、旧高度或间歇性连接错误。",
    "fundRisk": "把节点不可用误判为交易不存在，可能触发重复广播；扫链落后会延迟入账。",
    "stopLoss": "区分查询失败与业务否定结果，写入节点健康状态并限制有资金副作用的动作。",
    "investigate": [
      "比较节点高度、延迟、错误码和限流窗口",
      "用第二个独立节点核对区块或交易"
    ],
    "recovery": [
      "只读查询按退避策略重试或切换健康节点",
      "广播结果未知时按原 raw transaction 查询，不重新构建"
    ],
    "idempotencyBasis": "RPC operation key + original raw transaction hash",
    "currentBoundary": "多链 adaptor 和 RPC 边界已定位；完整节点熔断与健康评分仍属目标态。",
    "verificationEvidence": [
      "ChainDispatcher 与多链 adaptor 路由边界已验证"
    ],
    "relatedArticleSlugs": [
      "withdrawal-error-handling",
      "new-chain-integration-checklist",
      "wallet-rpc-trust-boundary"
    ],
    "relatedProjectSlugs": [
      "exchange-wallet-system"
    ]
  },
  {
    "slug": "rpc-consensus-conflict",
    "title": "多节点返回不同 blockHash 或 receipt",
    "category": "node-scanning",
    "priority": "advanced",
    "services": [
      "wallet-api"
    ],
    "chains": [
      "all"
    ],
    "actions": [
      "pause",
      "manual-review"
    ],
    "evidenceStatus": "design",
    "symptom": "同一高度或 txHash 在不同节点得到不同区块哈希、确认数或 receipt。",
    "fundRisk": "过早确认充值或错误判断提现终态，可能造成账务回滚和重复处置。",
    "stopLoss": "停止推进资金终态，把节点差异记录为待共识事件。",
    "investigate": [
      "比较节点链头、finalized/safe 高度、区块哈希和 provider 来源",
      "确认是否处于重组、节点落后或索引故障"
    ],
    "recovery": [
      "等待 canonical 链稳定后重新读取",
      "按链的最终性规则重算确认数并幂等推进或回滚"
    ],
    "idempotencyBasis": "chain + block_height + canonical_block_hash + tx_hash",
    "currentBoundary": "生产多节点仲裁设计，尚无本地故障注入实现。",
    "verificationEvidence": [
      "已整理确认数与链上事实优先原则"
    ],
    "relatedArticleSlugs": [
      "new-chain-integration-checklist",
      "wallet-rpc-trust-boundary"
    ],
    "relatedProjectSlugs": [
      "exchange-wallet-system"
    ]
  },
  {
    "slug": "scan-checkpoint-gap",
    "title": "checkpoint 跳跃、服务重启与失败高度回捞",
    "category": "node-scanning",
    "priority": "common",
    "services": [
      "wallet-service",
      "wallet-api"
    ],
    "chains": [
      "all"
    ],
    "actions": [
      "retry",
      "pause"
    ],
    "evidenceStatus": "partial",
    "symptom": "扫链 checkpoint 越过失败高度，或重启后从错误位置继续。",
    "fundRisk": "充值永久遗漏，或重复扫描导致重复入账。",
    "stopLoss": "checkpoint 只在整个高度持久化成功后推进，失败高度进入可追踪重试队列。",
    "investigate": [
      "核对 checkpoint、处理日志、失败高度表和链头",
      "抽查缺口范围内的区块与事件数量"
    ],
    "recovery": [
      "从最后成功高度重新扫描",
      "依靠链事件唯一键消除重复入账",
      "达到重试上限后暂停该链并告警"
    ],
    "idempotencyBasis": "chain + block_hash + tx_hash + event/log index",
    "currentBoundary": "扫链入口与确认推进已梳理；失败高度回捞的公开演示待完成。",
    "verificationEvidence": [
      "已定位充值扫链与确认数推进代码入口"
    ],
    "relatedArticleSlugs": [
      "cex-evm-wallet-deposit-withdrawal-loop"
    ],
    "relatedProjectSlugs": [
      "exchange-wallet-system",
      "web3-wallet-engineer-lab"
    ]
  },
  {
    "slug": "erc20-log-idempotency",
    "title": "ERC20 Event Log 重复、遗漏与 logIndex 幂等",
    "category": "deposit",
    "priority": "common",
    "services": [
      "wallet-service",
      "wallet-api"
    ],
    "chains": [
      "evm"
    ],
    "actions": [
      "retry",
      "compensate"
    ],
    "evidenceStatus": "partial",
    "symptom": "同一 Transfer log 被重复扫描，或批量查询边界导致事件遗漏。",
    "fundRisk": "重复入账或用户充值长时间不到账。",
    "stopLoss": "入账唯一键必须包含 chain、txHash、logIndex，不能只使用 txHash。",
    "investigate": [
      "核对区块范围、topics、合约地址、txHash 和 logIndex",
      "比较节点日志数量与本地事件数量"
    ],
    "recovery": [
      "对缺失区间重新扫描",
      "重复事件返回原入账记录",
      "已入账记录只推进确认数不重复记账"
    ],
    "idempotencyBasis": "chain_id + tx_hash + log_index",
    "currentBoundary": "事件幂等原则已记录，公开 Wallet Lab 首期先覆盖原生资产 txHash 幂等。",
    "verificationEvidence": [
      "充值扫描入口与事件索引字段已完成代码定位"
    ],
    "relatedArticleSlugs": [
      "cex-evm-wallet-deposit-withdrawal-loop"
    ],
    "relatedProjectSlugs": [
      "exchange-wallet-system",
      "web3-wallet-engineer-lab"
    ]
  },
  {
    "slug": "token-metadata-mismatch",
    "title": "假 Token、合约地址或 decimals 配置错误",
    "category": "deposit",
    "priority": "common",
    "services": [
      "wallet-service",
      "wallet-api",
      "risk-service"
    ],
    "chains": [
      "evm"
    ],
    "actions": [
      "pause",
      "manual-review"
    ],
    "evidenceStatus": "design",
    "symptom": "symbol 相同但合约不同，或 decimals 错误导致显示金额与最小单位换算异常。",
    "fundRisk": "假币入账、金额数量级错误或错误资产提现。",
    "stopLoss": "以 chain + contract address 识别资产；配置变更暂停入账与提现。",
    "investigate": [
      "读取合约地址、code hash、decimals 与资产白名单版本",
      "对比链上 raw amount 和本地最小单位"
    ],
    "recovery": [
      "隔离受影响资产记录并重算展示金额",
      "账务修正必须有审计分录，不直接覆写历史金额"
    ],
    "idempotencyBasis": "asset_id bound to chain + verified contract address",
    "currentBoundary": "这是资产治理设计，当前项目未实现完整 Token registry 审批流程。",
    "verificationEvidence": [
      "wallet-core 已使用最小单位金额，生产资产元数据治理待实现"
    ],
    "relatedArticleSlugs": [
      "multi-chain-wallet-resource-state"
    ],
    "relatedProjectSlugs": [
      "exchange-wallet-system",
      "wallet-core"
    ]
  },
  {
    "slug": "non-standard-token-balance",
    "title": "fee-on-transfer、rebase 等非标准 Token",
    "category": "deposit",
    "priority": "advanced",
    "services": [
      "wallet-service",
      "wallet-api",
      "risk-service"
    ],
    "chains": [
      "evm"
    ],
    "actions": [
      "pause",
      "manual-review"
    ],
    "evidenceStatus": "design",
    "symptom": "事件 amount、实际余额增量和用户预期到账金额不一致。",
    "fundRisk": "按 calldata 或普通 Transfer 假设记账会形成资产缺口。",
    "stopLoss": "未通过资产兼容性评估的 Token 默认不开放充值提现。",
    "investigate": [
      "比较交易前后托管地址余额和事件日志",
      "检查 Token 是否有税费、rebase、blacklist 或 hook 行为"
    ],
    "recovery": [
      "按已批准的资产规则计算实际到账",
      "无法稳定核对时暂停该资产并人工处理存量事件"
    ],
    "idempotencyBasis": "deposit event key + observed custody balance delta",
    "currentBoundary": "仅作为生产设计边界，不声称当前系统支持此类 Token。",
    "verificationEvidence": [
      "尚无实现证据"
    ],
    "relatedArticleSlugs": [
      "new-chain-integration-checklist"
    ],
    "relatedProjectSlugs": [
      "exchange-wallet-system"
    ]
  },
  {
    "slug": "credited-deposit-reorg",
    "title": "已入账区块发生 reorg",
    "category": "deposit",
    "priority": "key",
    "services": [
      "wallet-service",
      "wallet-api"
    ],
    "chains": [
      "evm",
      "bitcoin"
    ],
    "actions": [
      "pause",
      "compensate",
      "manual-review"
    ],
    "evidenceStatus": "design",
    "symptom": "充值达到早期确认并入账后，原区块不再属于 canonical 链。",
    "fundRisk": "用户已获得可用余额但链上资产事实消失，形成直接资金缺口。",
    "stopLoss": "暂停受影响账户出金与该高度后的确认推进，保存原/新区块证据。",
    "investigate": [
      "对比 canonical blockHash、交易位置与确认策略",
      "检查用户是否已使用或提现该笔余额"
    ],
    "recovery": [
      "未使用余额通过冲正分录回滚",
      "余额已流出时冻结相关账户并人工复核",
      "若交易在新链重新出现则按新事件键重新确认"
    ],
    "idempotencyBasis": "chain + canonical block hash + tx/event key + ledger reversal reference",
    "currentBoundary": "确认数处理已理解；已入账 reorg 的账务冲正和故障注入仍是生产设计。",
    "verificationEvidence": [
      "确认数推进和链上事实原则已有文档记录"
    ],
    "relatedArticleSlugs": [
      "cex-evm-wallet-deposit-withdrawal-loop",
      "withdrawal-error-handling"
    ],
    "relatedProjectSlugs": [
      "exchange-wallet-system",
      "web3-wallet-engineer-lab"
    ]
  },
  {
    "slug": "broadcast-result-unknown",
    "title": "广播 timeout，节点是否收到未知",
    "category": "withdrawal-finality",
    "priority": "key",
    "services": [
      "wallet-service",
      "wallet-api"
    ],
    "chains": [
      "all"
    ],
    "actions": [
      "pause",
      "retry"
    ],
    "evidenceStatus": "partial",
    "symptom": "广播请求超时或连接断开，没有拿到节点响应，但交易可能已经进入 mempool。",
    "fundRisk": "重新构建和签名第二笔交易可能重复出金。",
    "stopLoss": "订单进入 BROADCAST_UNKNOWN，禁止重新构建；保存原 signed payload。",
    "investigate": [
      "由原 raw transaction 计算 txHash",
      "按 txHash 查询多个节点、mempool 与链上结果",
      "核对签名请求和广播审计记录"
    ],
    "recovery": [
      "节点可见则绑定原 txHash 继续确认",
      "确定未接收时只重发同一 raw transaction",
      "超过观察窗口仍不确定则人工复核"
    ],
    "idempotencyBasis": "withdrawal_id + signed_payload_hash + deterministic tx_hash",
    "currentBoundary": "处理原则和调用边界已记录；完整超时故障注入仍待公开演示。",
    "verificationEvidence": [
      "已定位构建、签名、广播入口并记录结果未知策略"
    ],
    "relatedArticleSlugs": [
      "withdrawal-error-handling"
    ],
    "relatedProjectSlugs": [
      "exchange-wallet-system",
      "web3-wallet-engineer-lab"
    ]
  },
  {
    "slug": "reverted-withdrawal",
    "title": "receipt status=0",
    "category": "withdrawal-finality",
    "priority": "common",
    "services": [
      "wallet-service",
      "wallet-api"
    ],
    "chains": [
      "evm"
    ],
    "actions": [
      "compensate",
      "manual-review"
    ],
    "evidenceStatus": "partial",
    "symptom": "交易被打包但 EVM 执行回滚，receipt status 为 0。",
    "fundRisk": "用户未收到 Token，但 Gas 已消耗；若错误记为成功会造成账务错账。",
    "stopLoss": "停止成功结算，以 receipt 为失败资金事实并保留实际 gas cost。",
    "investigate": [
      "读取 receipt、revert reason/trace、gasUsed 和 effectiveGasPrice",
      "核对 nonce 与目标合约状态"
    ],
    "recovery": [
      "释放或重新建立业务冻结需遵循账务分录",
      "记录实际手续费",
      "修复可重试原因后创建新尝试而非改写旧 txHash"
    ],
    "idempotencyBasis": "withdrawal attempt id + tx_hash; new attempt uses a new attempt id",
    "currentBoundary": "receipt 查询路径已定位，细化的失败账务分录仍需实现。",
    "verificationEvidence": [
      "EVM 交易结果与确认路径已梳理"
    ],
    "relatedArticleSlugs": [
      "withdrawal-error-handling"
    ],
    "relatedProjectSlugs": [
      "exchange-wallet-system"
    ]
  },
  {
    "slug": "long-pending-transaction",
    "title": "交易长期 pending",
    "category": "withdrawal-finality",
    "priority": "common",
    "services": [
      "wallet-service",
      "wallet-api"
    ],
    "chains": [
      "evm",
      "bitcoin"
    ],
    "actions": [
      "pause",
      "manual-review"
    ],
    "evidenceStatus": "design",
    "symptom": "交易长时间在 mempool 中未确认，可能因手续费不足或网络拥堵。",
    "fundRisk": "释放冻结会重复出金；无限等待会占用余额和 nonce/UTXO。",
    "stopLoss": "保持订单和资金冻结，禁止无策略 replacement。",
    "investigate": [
      "检查 mempool 可见性、fee rate、nonce/UTXO 和链上后续交易",
      "判断是否满足 RBF 或 replacement 规则"
    ],
    "recovery": [
      "按批准策略加速同一业务尝试并关联新旧 txHash",
      "确认 dropped 后才能进入新的构建动作",
      "达到阈值后人工复核"
    ],
    "idempotencyBasis": "withdrawal_id + attempt lineage + nonce/selected UTXO set",
    "currentBoundary": "生产 fee-bump/replacement 策略尚未实现。",
    "verificationEvidence": [
      "已整理 pending 与 broadcast unknown 的状态区别"
    ],
    "relatedArticleSlugs": [
      "withdrawal-error-handling"
    ],
    "relatedProjectSlugs": [
      "exchange-wallet-system"
    ]
  },
  {
    "slug": "dropped-transaction",
    "title": "单节点查不到、疑似 dropped",
    "category": "withdrawal-finality",
    "priority": "common",
    "services": [
      "wallet-api",
      "wallet-service"
    ],
    "chains": [
      "all"
    ],
    "actions": [
      "pause",
      "retry"
    ],
    "evidenceStatus": "design",
    "symptom": "广播后一个节点返回 not found，但无法证明所有节点和 mempool 都未接收。",
    "fundRisk": "把 not found 当成失败并重新出金，可能产生双花式业务重复。",
    "stopLoss": "将单节点否定结果视为证据不足，不改变资金终态。",
    "investigate": [
      "跨独立 provider 查询 txHash",
      "对 EVM 检查账户 nonce，对 BTC 检查输入 UTXO 是否已花费",
      "核对原 raw transaction 是否可重放"
    ],
    "recovery": [
      "若 raw transaction 仍有效，重发同一字节",
      "只有证明旧交易不可生效后才创建新 attempt"
    ],
    "idempotencyBasis": "original tx hash + chain-specific consumed resource",
    "currentBoundary": "多节点仲裁与 dropped 判定属于生产设计。",
    "verificationEvidence": [
      "已记录广播结果未知不能直接重建的原则"
    ],
    "relatedArticleSlugs": [
      "withdrawal-error-handling"
    ],
    "relatedProjectSlugs": [
      "exchange-wallet-system"
    ]
  },
  {
    "slug": "replacement-multiple-txhash",
    "title": "replacement 与同一订单多个 txHash",
    "category": "withdrawal-finality",
    "priority": "advanced",
    "services": [
      "wallet-service",
      "wallet-api"
    ],
    "chains": [
      "evm",
      "bitcoin"
    ],
    "actions": [
      "pause",
      "compensate",
      "manual-review"
    ],
    "evidenceStatus": "design",
    "symptom": "同一业务订单因加速或重试关联多个 txHash。",
    "fundRisk": "只跟踪最新 txHash 会漏掉旧交易成功；多个资源不同的交易都可能确认。",
    "stopLoss": "维护 attempt lineage，所有 txHash 在确认前都不能丢弃。",
    "investigate": [
      "检查 EVM nonce 或 BTC input set 是否相同",
      "查询全部候选交易的 canonical 状态"
    ],
    "recovery": [
      "同 nonce/UTXO 的替换以最终 canonical 交易结算",
      "资源不同且可能双成功时立即人工复核并冻结相关账户"
    ],
    "idempotencyBasis": "withdrawal_id + attempt_id + resource identity + tx_hash",
    "currentBoundary": "生产 replacement 数据模型设计，当前项目尚未落地。",
    "verificationEvidence": [
      "多 txHash 异常已纳入状态机手册"
    ],
    "relatedArticleSlugs": [
      "withdrawal-error-handling"
    ],
    "relatedProjectSlugs": [
      "exchange-wallet-system"
    ]
  },
  {
    "slug": "chain-success-local-failure",
    "title": "链上成功但本地 DB 或账务更新失败",
    "category": "withdrawal-finality",
    "priority": "key",
    "services": [
      "wallet-service",
      "wallet-api"
    ],
    "chains": [
      "all"
    ],
    "actions": [
      "compensate",
      "manual-review"
    ],
    "evidenceStatus": "partial",
    "symptom": "receipt 已确认成功，但本地订单、冻结余额、账务或通知停留在中间状态。",
    "fundRisk": "重复提现、冻结不释放、用户状态错误或资产负债不平。",
    "stopLoss": "以链上成功为不可逆资金事实，禁止重签和重播；记录补偿任务。",
    "investigate": [
      "核对 canonical receipt/确认数、订单状态、冻结记录、账务分录和 outbox",
      "确认失败发生在哪个本地提交点"
    ],
    "recovery": [
      "按固定顺序幂等补写订单、账务与通知",
      "每一步使用唯一业务键和已处理标记",
      "账务不平则转人工复核"
    ],
    "idempotencyBasis": "withdrawal_id + canonical tx_hash + ledger entry type",
    "currentBoundary": "链上事实优先与补偿原则已记录；完整账务/outbox 故障注入仍待实现。",
    "verificationEvidence": [
      "已定位状态、账本和通知路径并形成恢复讲稿"
    ],
    "relatedArticleSlugs": [
      "withdrawal-error-handling"
    ],
    "relatedProjectSlugs": [
      "exchange-wallet-system",
      "web3-wallet-engineer-lab"
    ]
  },
  {
    "slug": "evm-nonce-gap",
    "title": "EVM nonce 冲突或 nonce gap",
    "category": "multi-chain",
    "priority": "key",
    "services": [
      "wallet-api",
      "wallet-service"
    ],
    "chains": [
      "evm"
    ],
    "actions": [
      "pause",
      "retry",
      "manual-review"
    ],
    "evidenceStatus": "partial",
    "symptom": "并发提现选择同一 nonce，或较低 nonce 长期 pending 阻塞后续交易。",
    "fundRisk": "交易互相替换、队列卡死，错误重建可能重复出金。",
    "stopLoss": "按热钱包地址串行或租约分配 nonce；冲突地址暂停新构建。",
    "investigate": [
      "比较 latest/pending nonce、本地 nonce lease 和全部 pending tx",
      "检查是否存在 replacement 或外部发送交易"
    ],
    "recovery": [
      "先处理最低缺口 nonce",
      "同 nonce 只按批准 replacement 策略处理",
      "本地分配状态与链上 pending 状态重新对账"
    ],
    "idempotencyBasis": "chain + sender address + nonce + withdrawal attempt",
    "currentBoundary": "wallet-core 显式传入 nonce；生产级 nonce manager 与失败注入仍未完成。",
    "verificationEvidence": [
      "TypeScript 多链构建测试覆盖显式 nonce 输入"
    ],
    "relatedArticleSlugs": [
      "multi-chain-wallet-resource-state",
      "withdrawal-error-handling"
    ],
    "relatedProjectSlugs": [
      "exchange-wallet-system",
      "wallet-core"
    ]
  },
  {
    "slug": "bitcoin-utxo-conflict",
    "title": "BTC UTXO 重复选择、RBF、手续费和粉尘",
    "category": "multi-chain",
    "priority": "common",
    "services": [
      "wallet-api",
      "wallet-service"
    ],
    "chains": [
      "bitcoin"
    ],
    "actions": [
      "pause",
      "manual-review"
    ],
    "evidenceStatus": "partial",
    "symptom": "并发交易选中相同 UTXO，找零成为粉尘，或 RBF 后旧新交易状态混乱。",
    "fundRisk": "双花冲突、交易拒绝、手续费失控或余额统计不准。",
    "stopLoss": "选币时锁定 UTXO，签名后持久化 input set；冲突 UTXO 不再分配。",
    "investigate": [
      "查询 UTXO spend 状态、mempool、RBF 标志、fee rate 和 dust threshold",
      "核对本地 UTXO lease 与找零地址"
    ],
    "recovery": [
      "同 input set 的替换纳入同一 attempt lineage",
      "释放已证明未使用的 lease",
      "无法判断花费归属时人工复核"
    ],
    "idempotencyBasis": "chain + ordered outpoint set + withdrawal attempt",
    "currentBoundary": "wallet-core 已覆盖 UTXO 构建输入；并发锁和 RBF 状态机属于目标态。",
    "verificationEvidence": [
      "bitcoinjs-lib 构建与签名测试已本地运行"
    ],
    "relatedArticleSlugs": [
      "multi-chain-wallet-resource-state"
    ],
    "relatedProjectSlugs": [
      "wallet-core",
      "exchange-wallet-system"
    ]
  },
  {
    "slug": "solana-blockhash-ata",
    "title": "Solana recentBlockhash 过期或 ATA 冲突",
    "category": "multi-chain",
    "priority": "common",
    "services": [
      "wallet-api"
    ],
    "chains": [
      "solana"
    ],
    "actions": [
      "retry",
      "pause"
    ],
    "evidenceStatus": "partial",
    "symptom": "签名前后 blockhash 失效，或并发创建同一 ATA 导致交易失败。",
    "fundRisk": "交易无法落链；盲目重签可能失去业务 attempt 关联。",
    "stopLoss": "将 blockhash 与构建时间持久化，过期交易不广播；ATA 创建使用幂等指令或先查询。",
    "investigate": [
      "检查 lastValidBlockHeight、simulation error、ATA 是否已经存在",
      "确认旧签名交易是否可能被接受"
    ],
    "recovery": [
      "证明旧交易已过期后，用新 blockhash 创建新的 attempt",
      "ATA 已存在时重新构建不包含冲突创建的交易"
    ],
    "idempotencyBasis": "withdrawal_id + attempt_id + message hash; ATA derived address",
    "currentBoundary": "wallet-core 已显式处理 recentBlockhash；生产重建编排仍待实现。",
    "verificationEvidence": [
      "Solana 构建测试已本地运行"
    ],
    "relatedArticleSlugs": [
      "multi-chain-wallet-resource-state"
    ],
    "relatedProjectSlugs": [
      "wallet-core",
      "exchange-wallet-system"
    ]
  },
  {
    "slug": "cosmos-sequence-mismatch",
    "title": "Cosmos sequence mismatch",
    "category": "multi-chain",
    "priority": "common",
    "services": [
      "wallet-api"
    ],
    "chains": [
      "cosmos"
    ],
    "actions": [
      "retry",
      "pause"
    ],
    "evidenceStatus": "partial",
    "symptom": "本地 sequence 与链上账户 sequence 不一致，交易在 CheckTx 阶段失败。",
    "fundRisk": "地址队列阻塞；错误并发分配会让后续交易连续失败。",
    "stopLoss": "同一地址串行分配 sequence，失败后暂停地址队列重新同步。",
    "investigate": [
      "读取链上 account number/sequence、mempool 与本地 lease",
      "确认先前交易是否已进入区块"
    ],
    "recovery": [
      "无链上事实时同步 sequence 后创建新 attempt",
      "已有交易时先等待其结果再推进队列"
    ],
    "idempotencyBasis": "chain + sender + account_number + sequence + attempt_id",
    "currentBoundary": "wallet-core 已显式传入 sequence；生产序列协调器尚未实现。",
    "verificationEvidence": [
      "Cosmos 交易构建测试已本地运行"
    ],
    "relatedArticleSlugs": [
      "multi-chain-wallet-resource-state"
    ],
    "relatedProjectSlugs": [
      "wallet-core",
      "exchange-wallet-system"
    ]
  },
  {
    "slug": "sui-object-version-lock",
    "title": "Sui object version 或 Gas object 被占用",
    "category": "multi-chain",
    "priority": "common",
    "services": [
      "wallet-api"
    ],
    "chains": [
      "sui"
    ],
    "actions": [
      "pause",
      "retry"
    ],
    "evidenceStatus": "partial",
    "symptom": "构建使用过期 object version，或多个交易并发占用同一 Gas object。",
    "fundRisk": "交易失败、对象锁竞争，盲目重试会持续使用陈旧输入。",
    "stopLoss": "对象和 Gas coin 按 digest/version 加租约；失败后重新读取 owned objects。",
    "investigate": [
      "查询 object ref、version、digest、锁状态和交易 effects",
      "核对本地 object lease"
    ],
    "recovery": [
      "确认旧交易未成功后刷新 object refs 再创建新 attempt",
      "已消费对象以链上 effects 更新本地状态"
    ],
    "idempotencyBasis": "object id + version + digest + transaction digest",
    "currentBoundary": "wallet-core 已显式处理 Sui 对象输入；并发对象调度仍是目标态。",
    "verificationEvidence": [
      "Sui 构建测试与充值模拟说明已记录"
    ],
    "relatedArticleSlugs": [
      "multi-chain-wallet-resource-state"
    ],
    "relatedProjectSlugs": [
      "wallet-core",
      "exchange-wallet-system"
    ]
  },
  {
    "slug": "tron-resource-tapos",
    "title": "TRON TAPOS、energy、bandwidth 或 fee limit 不足",
    "category": "multi-chain",
    "priority": "common",
    "services": [
      "wallet-api"
    ],
    "chains": [
      "tron"
    ],
    "actions": [
      "retry",
      "pause"
    ],
    "evidenceStatus": "partial",
    "symptom": "引用区块过期，或资源不足导致交易拒绝/执行失败。",
    "fundRisk": "持续失败消耗手续费，错误认为已完成会造成账务偏差。",
    "stopLoss": "广播前验证 expiration、TAPOS 引用和资源预算；过期交易不得发送。",
    "investigate": [
      "检查 ref_block、expiration、energy usage、bandwidth 和 fee_limit",
      "确认交易是否已进入链上"
    ],
    "recovery": [
      "无链上事实且已过期时重新构建新 attempt",
      "资源不足时补充资源或调整已批准 fee limit 后重建"
    ],
    "idempotencyBasis": "withdrawal attempt + transaction id + TAPOS reference",
    "currentBoundary": "wallet-core 已覆盖 TRON 构建输入；生产资源补充策略未实现。",
    "verificationEvidence": [
      "TRON SDK 构建测试已本地运行"
    ],
    "relatedArticleSlugs": [
      "multi-chain-wallet-resource-state"
    ],
    "relatedProjectSlugs": [
      "wallet-core",
      "exchange-wallet-system"
    ]
  },
  {
    "slug": "risk-signer-unavailable",
    "title": "risk-service 或 wallet-sign 不可用时 fail-closed",
    "category": "risk-signing",
    "priority": "key",
    "services": [
      "risk-service",
      "wallet-sign",
      "wallet-service"
    ],
    "chains": [
      "all"
    ],
    "actions": [
      "pause"
    ],
    "evidenceStatus": "partial",
    "symptom": "风控服务或签名服务超时、熔断或无法达到健康条件。",
    "fundRisk": "绕过风控或降级到不受控签名会直接扩大出金风险。",
    "stopLoss": "提现 fail-closed：不签名、不广播，订单保持可恢复的等待状态。",
    "investigate": [
      "检查调用超时、健康检查、审批凭证和 signer backend 状态",
      "确认是否已经产生签名结果"
    ],
    "recovery": [
      "服务恢复后用原订单和原审批上下文重试",
      "若已经签名则先核对签名内容，不能重新生成另一笔交易"
    ],
    "idempotencyBasis": "withdrawal_id + approval_hash + unsigned_payload_hash",
    "currentBoundary": "risk-service 校验与 Local Signer 基线已部分验证；跨服务故障注入待完成。",
    "verificationEvidence": [
      "risk-service 相关单测已本地验证；wallet-sign Local Signer 为当前基线"
    ],
    "relatedArticleSlugs": [
      "wallet-sign-signer",
      "withdrawal-error-handling"
    ],
    "relatedProjectSlugs": [
      "exchange-wallet-system"
    ]
  },
  {
    "slug": "authorization-replay-mismatch",
    "title": "审批凭证重放或审批内容与签名内容不一致",
    "category": "risk-signing",
    "priority": "common",
    "services": [
      "risk-service",
      "wallet-sign"
    ],
    "chains": [
      "all"
    ],
    "actions": [
      "pause",
      "manual-review"
    ],
    "evidenceStatus": "partial",
    "symptom": "旧审批被重复使用，或地址、金额、链、资产等签名内容与审批内容不一致。",
    "fundRisk": "攻击者可能替换出金目标或放大金额。",
    "stopLoss": "wallet-sign 必须校验审批哈希、有效期、nonce 和完整待签 payload；任何不一致拒签。",
    "investigate": [
      "比较审批 canonical payload 与 unsigned transaction",
      "检查审批 nonce、有效期、使用记录和调用方身份"
    ],
    "recovery": [
      "废弃不匹配凭证并重新走审批",
      "疑似重放时冻结订单和主体，保留审计证据"
    ],
    "idempotencyBasis": "approval_id/nonce + canonical approval payload hash + signed payload hash",
    "currentBoundary": "离线交易一致性、审批哈希与幂等标记单测已有证据；跨服务完整接入仍需验证。",
    "verificationEvidence": [
      "risk-service 提现提交、审批哈希和一致性校验单测已本地验证"
    ],
    "relatedArticleSlugs": [
      "wallet-sign-signer",
      "wallet-api-boundary",
      "wallet-signing-intent-abuse"
    ],
    "relatedProjectSlugs": [
      "exchange-wallet-system"
    ]
  },
  {
    "slug": "signing-backend-threshold",
    "title": "密钥后端、HSM/TSS 节点或门限不足",
    "category": "risk-signing",
    "priority": "advanced",
    "services": [
      "wallet-sign"
    ],
    "chains": [
      "all"
    ],
    "actions": [
      "pause",
      "manual-review"
    ],
    "evidenceStatus": "design",
    "symptom": "HSM 不可达、TSS 在线节点不足或 key share 状态异常，无法满足签名策略。",
    "fundRisk": "为了可用性降级到导出私钥或降低门限会破坏安全边界。",
    "stopLoss": "禁止不安全降级；保持订单未签名并对 signer backend 告警。",
    "investigate": [
      "检查 key version、committee、threshold、节点健康和审计日志",
      "确认是否已产生完整签名"
    ],
    "recovery": [
      "恢复满足策略的原后端后重试同一待签 payload",
      "密钥状态异常进入受控人工恢复流程，不能复制或导出私钥"
    ],
    "idempotencyBasis": "sign_request_id + key_version + unsigned_payload_hash",
    "currentBoundary": "独立三节点 TSS Keygen/Sign 已本地验证，但尚未接入 wallet-sign；HSM 仅为架构设计。",
    "verificationEvidence": [
      "独立 TSS 项目的三节点 Keygen / Sign 本地验证记录"
    ],
    "relatedArticleSlugs": [
      "mpc-wallet-sign-integration",
      "aws-cloudhsm-wallet-sign-integration",
      "mpc-tss-security-boundaries",
      "hsm-key-extractability-boundaries"
    ],
    "relatedProjectSlugs": [
      "tss-mpc",
      "exchange-wallet-system"
    ]
  },
  {
    "slug": "gas-asset-insufficient",
    "title": "Token 足够但 Gas 币不足",
    "category": "funds-operations",
    "priority": "common",
    "services": [
      "wallet-service",
      "wallet-api",
      "risk-service"
    ],
    "chains": [
      "evm",
      "sui",
      "tron",
      "solana"
    ],
    "actions": [
      "pause",
      "retry"
    ],
    "evidenceStatus": "design",
    "symptom": "热地址 Token 余额足够，但原生 Gas 资产或链资源不足，交易无法执行。",
    "fundRisk": "提现队列堆积；无上限自动补 Gas 可能被滥用。",
    "stopLoss": "暂停该地址/资产出金，Gas 补充必须经过限额和风控策略。",
    "investigate": [
      "估算当前交易所需 Gas/资源并读取原生资产余额",
      "检查补 Gas 任务、阈值和近期异常消耗"
    ],
    "recovery": [
      "受控补充 Gas 后重新估算并创建新 attempt",
      "异常消耗先人工复核，不自动持续补充"
    ],
    "idempotencyBasis": "gas top-up request id + target address + policy window",
    "currentBoundary": "链级资源参数已在 wallet-core 显式建模；自动 Gas station 属于生产设计。",
    "verificationEvidence": [
      "多链交易构建测试要求显式资源输入"
    ],
    "relatedArticleSlugs": [
      "multi-chain-wallet-resource-state"
    ],
    "relatedProjectSlugs": [
      "wallet-core",
      "exchange-wallet-system"
    ]
  },
  {
    "slug": "hot-wallet-liquidity-collection",
    "title": "热钱包流动性不足或归集任务卡住",
    "category": "funds-operations",
    "priority": "common",
    "services": [
      "wallet-service",
      "wallet-api",
      "risk-service"
    ],
    "chains": [
      "all"
    ],
    "actions": [
      "pause",
      "manual-review"
    ],
    "evidenceStatus": "design",
    "symptom": "总资产充足但可出金热钱包余额不足，归集任务长期未完成。",
    "fundRisk": "提现 SLA 下降；临时跨地址调资若缺乏风控会扩大热端暴露。",
    "stopLoss": "暂停超出可用流动性的提现批次，禁止隐式透支或未审批调资。",
    "investigate": [
      "核对热/冷/归集地址余额、在途交易和归集任务状态",
      "检查 Gas、UTXO/nonce 与风控限额"
    ],
    "recovery": [
      "恢复归集或发起有审计的补充流动性任务",
      "按优先级重新排队提现，不改变原订单幂等键"
    ],
    "idempotencyBasis": "collection job id + source/destination + asset + amount",
    "currentBoundary": "这是资金运营设计，当前项目没有真实热冷钱包运维经验声明。",
    "verificationEvidence": [
      "尚无生产运行证据"
    ],
    "relatedArticleSlugs": [
      "cex-evm-wallet-deposit-withdrawal-loop"
    ],
    "relatedProjectSlugs": [
      "exchange-wallet-system"
    ]
  },
  {
    "slug": "residual-locked-balance",
    "title": "终态订单仍残留冻结余额",
    "category": "funds-operations",
    "priority": "common",
    "services": [
      "wallet-service"
    ],
    "chains": [
      "all"
    ],
    "actions": [
      "compensate",
      "manual-review"
    ],
    "evidenceStatus": "design",
    "symptom": "订单已成功、失败或取消，但用户 frozen balance 未按终态释放或扣减。",
    "fundRisk": "用户余额不可用，或 available + frozen 与账务总额不一致。",
    "stopLoss": "停止直接修改余额，先锁定账户并按订单和分录对账。",
    "investigate": [
      "核对订单终态、冻结明细、账务分录和余额聚合",
      "检查重复消费、事务中断和补偿任务"
    ],
    "recovery": [
      "通过唯一补偿分录释放或扣减残留冻结",
      "重算余额并验证会计恒等式",
      "无法平账转人工复核"
    ],
    "idempotencyBasis": "order_id + ledger_entry_type + compensation_version",
    "currentBoundary": "账务恢复原则已整理，严格双式账和余额不变量测试仍未完成。",
    "verificationEvidence": [
      "已定位提现状态、冻结与通知路径"
    ],
    "relatedArticleSlugs": [
      "withdrawal-error-handling",
      "wallet-ledger-transaction-mq-consistency"
    ],
    "relatedProjectSlugs": [
      "exchange-wallet-system",
      "web3-wallet-engineer-lab"
    ]
  },
  {
    "slug": "ledger-fee-reconciliation",
    "title": "链上余额、业务账和实际手续费不一致",
    "category": "funds-operations",
    "priority": "advanced",
    "services": [
      "wallet-service",
      "wallet-api"
    ],
    "chains": [
      "all"
    ],
    "actions": [
      "pause",
      "manual-review",
      "compensate"
    ],
    "evidenceStatus": "design",
    "symptom": "托管地址链上余额、用户负债汇总、运营账户和实际 network fee 无法对平。",
    "fundRisk": "资产负债缺口可能被隐藏，继续出金会扩大损失。",
    "stopLoss": "暂停受影响资产的自动出金与自动调账，保存对账快照。",
    "investigate": [
      "按时间窗核对充值、提现、归集、Gas 补充和手续费分录",
      "比较 canonical 链上余额与内部 ledger，不使用缓存余额作最终依据"
    ],
    "recovery": [
      "定位差异来源后用有审计的调整分录修复",
      "无法解释的差异升级安全事件并人工复核"
    ],
    "idempotencyBasis": "reconciliation run id + asset + address/account + adjustment reference",
    "currentBoundary": "生产对账框架设计，当前项目未实现完整资产负债与手续费账。",
    "verificationEvidence": [
      "已明确链上事实、账务分录与业务确认的不同恢复来源"
    ],
    "relatedArticleSlugs": [
      "withdrawal-error-handling",
      "wallet-ledger-transaction-mq-consistency"
    ],
    "relatedProjectSlugs": [
      "exchange-wallet-system"
    ]
  },
  {
    "slug": "notification-infrastructure-backlog",
    "title": "通知堆积、outbox/死信或 DB/Redis 部分失败",
    "category": "funds-operations",
    "priority": "common",
    "services": [
      "wallet-service"
    ],
    "chains": [
      "all"
    ],
    "actions": [
      "retry",
      "compensate"
    ],
    "evidenceStatus": "partial",
    "symptom": "资金状态已持久化，但通知未发送、重复发送，或 DB 成功而 Redis/消息投递失败。",
    "fundRisk": "下游看不到真实状态或重复处理；若通知被误当作资金事实会产生错误补偿。",
    "stopLoss": "资金事实与通知解耦，通知失败不得回滚已经确认的链上/账务结果。",
    "investigate": [
      "核对 DB 事务、outbox、delivery attempt、死信和消费者幂等记录",
      "确认下游是否已处理同一 event id"
    ],
    "recovery": [
      "从 outbox/死信按 event id 重放",
      "下游重复事件返回已处理结果",
      "DB/缓存不一致时以持久化账务状态重建派生缓存"
    ],
    "idempotencyBasis": "domain event id + consumer id",
    "currentBoundary": "通知与状态路径已定位；完整 transactional outbox 与死信演示仍待补。",
    "verificationEvidence": [
      "已记录通知失败不能改变资金事实的恢复原则"
    ],
    "relatedArticleSlugs": [
      "withdrawal-error-handling"
    ],
    "relatedProjectSlugs": [
      "exchange-wallet-system",
      "web3-wallet-engineer-lab"
    ]
  }
]
