/* eslint-disable */
// Generated by scripts/generate-radars.mjs. Build-time full archive only.

import type { DailyRadar } from './generatedRadars.ts'
import { monthlyRadars as month0 } from './generatedRadarMonths/2026-08.ts'
import { monthlyRadars as month1 } from './generatedRadarMonths/2026-07.ts'

export const dailyRadars: DailyRadar[] = [...month0, ...month1]
