/* eslint-disable */
// Generated by scripts/generate-market-radars.mjs.
import type { MarketRadarDaily } from './generatedMarketRadars.ts'
const loaders: Record<string, () => Promise<{ monthlyMarketRadars: MarketRadarDaily[] }>> = {
  '2026-08': () => import('./generatedMarketRadarMonths/2026-08.ts'),
}
export async function loadMarketRadarBySlug(slug: string): Promise<MarketRadarDaily | undefined> {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(slug)) return undefined
  const load = loaders[slug.slice(0, 7)]
  if (!load) return undefined
  const { monthlyMarketRadars } = await load()
  return monthlyMarketRadars.find(entry => entry.slug === slug)
}
