/* eslint-disable */
// Generated by scripts/generate-ai-cases.mjs. Do not edit by hand.

export type AiCaseStage = 'building' | 'verified-local' | 'operational'

export interface AiCase {
  id: number
  slug: string
  title: string
  stage: AiCaseStage
  updatedAt: string
  summary: string
  currentFocus: string
  flow: string[]
  responsibilities: string[]
  evidence: string[]
  failureHandling: string[]
  knownLimits: string[]
  targetOutcome: string
  nextMilestone: string
  relatedArticleSlugs: string[]
}

export const aiCases: AiCase[] = [
  {
    "id": 1,
    "slug": "ai-coding-collaboration",
    "title": "AI Coding 协作",
    "stage": "verified-local",
    "updatedAt": "2026-07-13",
    "summary": "用 Planner、Worker、Reviewer 和人工验收拆开计划、执行与审查，让 AI 修改代码时有边界、有交接、有验证。",
    "currentFocus": "把这套协作方式应用到钱包项目的真实改动，并让每次交付都能回到代码差异、测试结果和未解决风险。",
    "flow": [
      "定义目标与不做什么",
      "Planner 拆解边界与验收标准",
      "Worker 按计划实现",
      "Reviewer 检查错误、遗漏和越界",
      "我运行验证并决定是否接受"
    ],
    "responsibilities": [
      "我负责目标、风险偏好和最终验收",
      "AI 负责方案比较、实现辅助、测试补充和第二视角审查",
      "高风险钱包判断必须由代码与运行结果支撑"
    ],
    "evidence": [
      "已形成最小 Planner/Worker/Reviewer 工作流",
      "在网站与钱包项目中使用构建、类型检查和测试作为完成条件",
      "记录 Agent 修改错文件、目标漂移和验证不足等失败模式"
    ],
    "failureHandling": [
      "发现目标漂移时回到原始成功标准",
      "发现修改越界时保留用户变更并缩小补丁",
      "测试失败时不把代码生成等同于完成"
    ],
    "knownLimits": [
      "并非所有小任务都值得拆成多 Agent",
      "模型审查不能替代本人理解和安全判断",
      "仍需积累更多钱包项目中的量化案例"
    ],
    "targetOutcome": "形成一套可以在复杂工程任务中重复使用的协作协议：上下文模板、角色边界、交接格式、验证清单和失败接管规则完整一致。",
    "nextMilestone": "选择一次钱包状态机或签名边界改动，保留计划、实现、审查和人工验收的完整公开复盘。",
    "relatedArticleSlugs": [
      "minimal-multi-agent-coding-workflow",
      "codex-ai-workflow-system-retrospective"
    ]
  },
  {
    "id": 2,
    "slug": "obsidian-knowledge-system",
    "title": "Obsidian 知识系统",
    "stage": "operational",
    "updatedAt": "2026-07-13",
    "summary": "把外部资料、AI 候选、项目记录和个人理解分层管理，通过人工审核与发布门禁维护唯一主库。",
    "currentFocus": "减少重复笔记和未经核验的 AI 内容，让知识能回到钱包项目、面试讲解、文章和下一步行动。",
    "flow": [
      "来源进入资料库或收件箱",
      "AI 生成待审核候选",
      "人工核对代码与来源",
      "结论合并到唯一主库",
      "显式 publish: true 后生成公开内容"
    ],
    "responsibilities": [
      "我决定哪些结论进入主库和公开站点",
      "AI 负责查重、结构化、关联与候选生成",
      "私人日记、求职计划和未核验内容永远不自动公开"
    ],
    "evidence": [
      "已建立项目、知识、资料、模板和归档分区",
      "网站同步脚本只接受显式发布标记",
      "钱包讲义、Go 学习和项目看板使用统一入口与维护规则"
    ],
    "failureHandling": [
      "没有 publish: true 时同步器忽略笔记",
      "内容重复时合并到唯一主库而不是新增第二份",
      "来源或代码事实不足时保持候选状态"
    ],
    "knownLimits": [
      "发布记录仍需要人工挑选和编辑",
      "站点不读取本机绝对路径",
      "知识结构需要定期清理失效入口"
    ],
    "targetOutcome": "让每次学习都可以沿来源、候选、核验、主库、项目和公开输出追踪，同时确保隐私内容无法因自动同步进入网站。",
    "nextMilestone": "把项目里程碑也接入显式发布流程，并为同步前后的字段、隐私词和关联项目增加自动校验。",
    "relatedArticleSlugs": [
      "codex-ai-workflow-system-retrospective",
      "minimal-multi-agent-coding-workflow"
    ]
  },
  {
    "id": 3,
    "slug": "research-automation-workflows",
    "title": "研究与自动化工作流",
    "stage": "building",
    "updatedAt": "2026-07-13",
    "summary": "把每日简报、AI + Web3 设计雷达和公众号增量整理做成有来源、有去重、有固定写入边界的重复工作流。",
    "currentFocus": "从“每天生成内容”升级为“稳定产生可行动、可回溯、不会覆盖人工记录的研究输入”。",
    "flow": [
      "按主题和时间触发任务",
      "检索并优先核验一手来源",
      "与历史状态去重",
      "生成结构化结论与行动",
      "只写入目标文档的固定标记区块",
      "人工复盘后进入知识或项目"
    ],
    "responsibilities": [
      "我定义选题价值、风险边界和最终行动",
      "AI 负责检索、交叉核验、去重与结构化",
      "自动化只能写入被授权的区块，不能覆盖手写复盘"
    ],
    "evidence": [
      "已运行币圈新闻早报、每日简报与 AI + Web3 设计雷达",
      "公众号工作流采用增量获取和独立文章沉淀",
      "每日任务使用 start/end 标记保护其他自动化与人工内容"
    ],
    "failureHandling": [
      "没有可靠发现时明确报告而不凑数",
      "状态写入失败时保留输出并报告目标位置",
      "登录墙、反爬或指标不可见时明确说明盲区"
    ],
    "knownLimits": [
      "信息源质量仍需持续评估",
      "自动化结果不会直接成为个人结论",
      "部分外部平台存在可访问性和指标核验限制"
    ],
    "targetOutcome": "形成一组可维护的研究工作流：每个任务都有来源策略、去重状态、写入边界、失败语义和知识回流路径，而不是互相覆盖的定时摘要。",
    "nextMilestone": "为三类工作流增加统一的运行质量记录：来源覆盖、重复率、人工采用率和失败原因。",
    "relatedArticleSlugs": [
      "codex-ai-workflow-system-retrospective",
      "web3-narrative-participation-framework"
    ]
  }
]
