/* eslint-disable */
// Generated by scripts/generate-radars.mjs. Do not edit by hand.

export interface RadarItem { title: string; summary: string; sourceUrl?: string }
export interface DailyRadar { date: string; slug: string; title: string; summary: string; reviewStatus: 'automated'; generatedAt: string; sourceSections: string[]; missingSections: string[]; marketSignals: RadarItem[]; aiTip?: RadarItem; web3Design?: RadarItem; vibeProject?: RadarItem; readingPick?: RadarItem; sourceUrls: string[]; relatedProjectSlugs: string[] }

export const dailyRadars: DailyRadar[] = [
  {
    "date": "2026-07-16",
    "slug": "2026-07-16",
    "title": "每日研究雷达 · 2026-07-16",
    "summary": "关注美英稳定币协作与美国加密资产分类解释，把 AI 评测变成可复跑实验，并用多钱包发现机制明确签名边界。",
    "reviewStatus": "automated",
    "generatedAt": "2026-07-16T17:22:02+08:00",
    "sourceSections": [
      "crypto",
      "radar",
      "vibe",
      "reading"
    ],
    "missingSections": [],
    "marketSignals": [
      {
        "title": "美英将跨境稳定币活动纳入联合工作项",
        "summary": "两国财政部门发布未来市场工作组建议及稳定币联合声明，显示跨境稳定币服务的合规接口与运营边界正成为产品基础设施议题；这属于政策方向，并非对具体业务的批准。",
        "sourceUrl": "https://home.treasury.gov/news/press-releases/sb0560"
      },
      {
        "title": "SEC 与 CFTC 的加密资产分类解释已生效",
        "summary": "面向美国市场的资产展示、发行与交易流程，应分别记录资产特性、发行方承诺和交易活动，不能只按代币名称判断合规属性；具体业务仍需专业法律意见。",
        "sourceUrl": "https://www.cftc.gov/LawRegulation/FederalRegister/finalrules/2026-05635.html"
      },
      {
        "title": "节点软件分发是钱包基础设施的供应链风险面",
        "summary": "自建或可切换链节点的服务应把发行物签名与校验和验证、版本记录和升级前检查纳入部署验收；这是通用完整性建议，不代表存在特定漏洞。",
        "sourceUrl": "https://ethereum.org/developers/docs/nodes-and-clients/run-a-node/"
      }
    ],
    "aiTip": {
      "title": "用五次固定条件运行检查评测稳定性",
      "summary": "对小型代码任务固定输入、工具版本和超时，连续运行五次并记录通过情况、耗时、工具调用数及失败类型；先辨别结果是否稳定，再调整提示词或模型。",
      "sourceUrl": "https://openai.com/news/research/separating-signal-from-noise-in-coding-evaluations/"
    },
    "web3Design": {
      "title": "EIP-6963 用事件循环处理多钱包发现",
      "summary": "将连接器发现结果建模为短生命周期、可验证的能力清单，按内部 connector ID 去重；签名前绑定已选连接器、账户和链 ID，在重连或发现变化后重新确认。",
      "sourceUrl": "https://eips.ethereum.org/EIPS/eip-6963"
    },
    "vibeProject": {
      "title": "Trust Wallet Core · 可嵌入的多链钱包底层库",
      "summary": "该开源跨平台库可帮助团队避免逐链重复实现地址、序列化与签名细节；可从单链的 ParseUnsignedTx、BuildSigningPayload、Sign、Verify/Encode 窄接口和固定测试向量起步。",
      "sourceUrl": "https://github.com/trustwallet/wallet-core"
    },
    "readingPick": {
      "title": "U.S.-UK Transatlantic Taskforce for the Markets of the Future",
      "summary": "阅读美国财政部关于跨境资本市场、代币化活动与数字资产监管协作的公开建议。行动问题：产品在跨境稳定币流程中保存或传递的每类数据，属于协议事实、产品政策还是潜在合规证据？",
      "sourceUrl": "https://home.treasury.gov/news/press-releases/sb0560"
    },
    "sourceUrls": [
      "https://home.treasury.gov/news/press-releases/sb0560",
      "https://www.cftc.gov/LawRegulation/FederalRegister/finalrules/2026-05635.html",
      "https://ethereum.org/developers/docs/nodes-and-clients/run-a-node/",
      "https://coinmarketcap.com/zh/",
      "https://openai.com/news/research/separating-signal-from-noise-in-coding-evaluations/",
      "https://eips.ethereum.org/EIPS/eip-6963",
      "https://github.com/trustwallet/wallet-core"
    ],
    "relatedProjectSlugs": [
      "wallet-core",
      "exchange-wallet-system",
      "web3-wallet-engineer-lab"
    ]
  },
  {
    "date": "2026-07-15",
    "slug": "2026-07-15",
    "title": "每日研究雷达 · 2026-07-15",
    "summary": "关注美英稳定币监管协作、AI 判别性实验、Bitcoin PSBT 签名边界，以及给 AI 生成 SQL 增加确定性检查。",
    "reviewStatus": "automated",
    "generatedAt": "2026-07-15T10:30:00+08:00",
    "sourceSections": [
      "crypto",
      "radar",
      "vibe",
      "reading"
    ],
    "missingSections": [],
    "marketSignals": [
      {
        "title": "实时币价统一使用可读行情入口",
        "summary": "BTC 与 ETH 的实时价格继续通过 CoinMarketCap 中文站查看；日报不使用单个交易所的原始 JSON 作为读者入口，也不依据单一时点价格判断方向。",
        "sourceUrl": "https://coinmarketcap.com/zh/"
      },
      {
        "title": "美英发布数字资产市场合作建议",
        "summary": "美国财政部与英国财政部公布跨大西洋市场工作组建议，涉及跨境资本市场、代币化活动与数字资产监管协作。",
        "sourceUrl": "https://home.treasury.gov/news/press-releases/sb0560"
      },
      {
        "title": "美英继续推进稳定币监管协调",
        "summary": "联合声明支持合规稳定币服务的风险分级市场准入和跨境监管协作；这是政策方向，不代表具体产品已经获批。",
        "sourceUrl": "https://www.gov.uk/government/publications/recommendations-of-the-transatlantic-taskforce-for-markets-of-the-future/uk-us-joint-statement-on-stablecoins"
      }
    ],
    "aiTip": {
      "title": "假设账本与判别性实验",
      "summary": "调试时先列出互斥假设，再只运行一个信息增益最高、可逆且能排除候选的最小实验；把预期、实际结果和被排除的假设继续沉淀为回归测试。"
    },
    "web3Design": {
      "title": "Bitcoin PSBT 把签名上下文变成可校验的数据契约",
      "summary": "PSBT 将构建、UTXO 证据、离线签名、组合和广播分开；wallet-sign 可以复核 prevout、输出、找零、费用与 sighash，而不需要联网选币或广播。",
      "sourceUrl": "https://bips.dev/174/"
    },
    "vibeProject": {
      "title": "sqlsure · AI 生成 SQL 的确定性语义闸门",
      "summary": "sqlsure 在执行前检查 join 扇出、不可加指标、错误 join key 与策略违规，让 Agent 形成生成、检查、修复、再检查的闭环。",
      "sourceUrl": "https://github.com/sqlsure/sqlsure"
    },
    "readingPick": {
      "title": "Fragments · July 6",
      "summary": "Martin Fowler 用短札记连接软件设计、specification-driven development 与工程观察；适合练习把即时灵感整理为有来源、有反证条件和下一次验证动作的判断。",
      "sourceUrl": "https://www.martinfowler.com/fragments/"
    },
    "sourceUrls": [
      "https://coinmarketcap.com/zh/",
      "https://home.treasury.gov/news/press-releases/sb0560",
      "https://www.gov.uk/government/publications/recommendations-of-the-transatlantic-taskforce-for-markets-of-the-future/uk-us-joint-statement-on-stablecoins",
      "https://bips.dev/174/",
      "https://bips.dev/370/",
      "https://doxygen.bitcoincore.org/wallet_2rpc_2coins_8cpp_source.html",
      "https://github.com/sqlsure/sqlsure",
      "https://www.martinfowler.com/fragments/"
    ],
    "relatedProjectSlugs": [
      "wallet-core",
      "exchange-wallet-system",
      "web3-wallet-engineer-lab"
    ]
  },
  {
    "date": "2026-07-14",
    "slug": "2026-07-14",
    "title": "每日研究雷达 · 2026-07-14",
    "summary": "修正并交叉核验 BTC/ETH 价格快照，同时关注 CPI 波动、AI 上下文交接、Sui Object Reference 与本地编码记忆。",
    "reviewStatus": "automated",
    "generatedAt": "2026-07-14T16:24:48+08:00",
    "sourceSections": [
      "crypto",
      "radar",
      "vibe",
      "reading"
    ],
    "missingSections": [],
    "marketSignals": [
      {
        "title": "BTC 交易所 K 线快照为 62,153.89 美元",
        "summary": "Coinbase 现货分钟收盘显示，北京时间 05:00 BTC 报 62,153.89 美元，24 小时约跌 3.14%，区间为 61,750.90–64,388.01 美元。",
        "sourceUrl": "https://coinmarketcap.com/zh/"
      },
      {
        "title": "ETH 价格已更正为约 1,765 美元",
        "summary": "原快照曾将 ETH 误读为 1,624.95 美元；Coinbase 同时点收盘为 1,765.21 美元，Kraken 为 1,765.50 美元，两家交易所均确认 ETH 未跌破 1,700 美元。",
        "sourceUrl": "https://coinmarketcap.com/zh/"
      },
      {
        "title": "CPI 是确定的波动事件，不是方向信号",
        "summary": "美国劳工统计局计划在北京时间 20:30 发布 6 月 CPI；日历事件提高波动先验，但方向仍需等待实际值与成交、资金费率等后续证据确认。",
        "sourceUrl": "https://www.bls.gov/schedule/news_release/cpi.htm"
      }
    ],
    "aiTip": {
      "title": "Context Handoff 上下文交接包",
      "summary": "长任务切换前只保留目标、已确认事实、当前状态、未决问题、下一步和证据位置；链上资源还要标注获取时间与是否可能过期，避免新会话把旧快照当成当前事实。"
    },
    "web3Design": {
      "title": "Sui Object Reference 把可花费状态变成认证引用",
      "summary": "objectId、version 与 digest 共同描述被签名交易使用的对象版本；旧引用在对象被消费后明确失效，使钱包可以围绕资源预留、冲突、重建和 canonical effects 组织恢复状态。",
      "sourceUrl": "https://docs.sui.io/doc/sui.pdf"
    },
    "vibeProject": {
      "title": "Recall · 本地优先的编码会话交接记忆",
      "summary": "Recall 将编码会话整理为可审计的本地活动日志和交接摘要，重点不是重放完整聊天，而是保留目标、变更、验证与未决事项，同时控制脱敏和加载边界。",
      "sourceUrl": "https://github.com/raiyanyahya/recall"
    },
    "readingPick": {
      "title": "Finally, finance's digital transformation",
      "summary": "文章把区块链理解为多方缺乏共同信任时的中立协调层；评估钱包或链上产品时，应先识别谁在对账、谁能改单、谁承担交易对手风险，再判断链上共享状态是否真的必要。",
      "sourceUrl": "https://a16zcrypto.com/posts/article/finance-digital-transformation-finally/"
    },
    "sourceUrls": [
      "https://coinmarketcap.com/zh/",
      "https://api.exchange.coinbase.com/products/BTC-USD/candles?granularity=300&start=2026-07-12T21:00:00Z&end=2026-07-13T21:00:00Z",
      "https://api.exchange.coinbase.com/products/ETH-USD/candles?granularity=300&start=2026-07-12T21:00:00Z&end=2026-07-13T21:00:00Z",
      "https://api.kraken.com/0/public/OHLC?pair=ETHUSD&interval=1&since=1783976340",
      "https://www.bls.gov/schedule/news_release/cpi.htm",
      "https://docs.sui.io/doc/sui.pdf",
      "https://github.com/raiyanyahya/recall",
      "https://a16zcrypto.com/posts/article/finance-digital-transformation-finally/"
    ],
    "relatedProjectSlugs": [
      "wallet-core",
      "exchange-wallet-system"
    ]
  },
  {
    "date": "2026-07-13",
    "slug": "2026-07-13",
    "title": "每日研究雷达 · 2026-07-13",
    "summary": "关注地缘风险下的加密市场、反例驱动的 AI 验收、ERC-4337 多通道 nonce，以及可审计的 Agent PR 证据包。",
    "reviewStatus": "automated",
    "generatedAt": "2026-07-13T09:15:00+08:00",
    "sourceSections": [
      "crypto",
      "radar",
      "vibe",
      "reading"
    ],
    "missingSections": [],
    "marketSignals": [
      {
        "title": "地缘风险尚未触发加密市场剧烈重定价",
        "summary": "BTC 在报道时点维持窄幅波动；周末传统市场休市意味着价格发现仍不完整，需要等待跨资产重新定价。",
        "sourceUrl": "https://www.coindesk.com/markets/2026/07/12/bitcoin-ether-little-changed-as-u-s-launches-fresh-iran-strikes"
      },
      {
        "title": "行业消息需要按证据等级处理",
        "summary": "监管、融资和安全事件若缺少原始公告，只能标记待核验，不能从新闻标题直接推导结论。",
        "sourceUrl": "https://decrypt.co/news-explorer?pinned=1484186&title=stablecoin-giant-circle-secures-final-federal-bank-charter-nod"
      }
    ],
    "aiTip": {
      "title": "反例驱动验收",
      "summary": "先让 AI 写出可判定标准、失败反例和证据要求，再执行和自评任务，减少“看似完整但遗漏关键边界”的输出。"
    },
    "web3Design": {
      "title": "ERC-4337 的 key + sequence nonce",
      "summary": "将全局队列拆成多条有序通道，在保留抗重放边界的同时支持不同权限与操作并行；钱包系统仍需显式保存资源状态。",
      "sourceUrl": "https://eips.ethereum.org/EIPS/eip-4337"
    },
    "vibeProject": {
      "title": "Agent PR 证据包",
      "summary": "把编码 Agent 的提示摘要、关键工具调用、测试结果、最终 diff 与人工确认点整理为可审计的 PR 上下文。",
      "sourceUrl": "https://github.com/es617/claude-replay"
    },
    "readingPick": {
      "title": "Not Every Workflow Is An Agent",
      "summary": "用目标、状态、证据、恢复路径和停止条件区分确定性工作流与真正需要判断循环的 Agent 系统。",
      "sourceUrl": "https://www.tonywood.org/writing/not-every-workflow-is-an-agent/"
    },
    "sourceUrls": [
      "https://www.coindesk.com/markets/2026/07/12/bitcoin-ether-little-changed-as-u-s-launches-fresh-iran-strikes",
      "https://decrypt.co/news-explorer?pinned=1484186&title=stablecoin-giant-circle-secures-final-federal-bank-charter-nod",
      "https://eips.ethereum.org/EIPS/eip-4337",
      "https://github.com/es617/claude-replay",
      "https://www.tonywood.org/writing/not-every-workflow-is-an-agent/"
    ],
    "relatedProjectSlugs": [
      "exchange-wallet-system"
    ]
  }
]
