/* eslint-disable */
// Generated by scripts/generate-radars.mjs. Do not edit by hand.

export interface RadarItem { title: string; summary: string; sourceUrl?: string }
export interface DailyRadar { date: string; slug: string; title: string; summary: string; reviewStatus: 'automated'; generatedAt: string; sourceSections: string[]; missingSections: string[]; marketSignals: RadarItem[]; aiTip?: RadarItem; web3Design?: RadarItem; vibeProject?: RadarItem; readingPick?: RadarItem; sourceUrls: string[]; relatedProjectSlugs: string[] }

export const dailyRadars: DailyRadar[] = [
  {
    "date": "2026-07-24",
    "slug": "2026-07-24",
    "title": "每日研究雷达 · 2026-07-24",
    "summary": "聚焦第三方托管桥风险、俄罗斯加密资产流通规则、高管社交账号劫持、Agent 结果与轨迹双重评测、并发 nonce 域，以及本地代码图谱与 AI 时代的变更定价。",
    "reviewStatus": "automated",
    "generatedAt": "2026-07-24T07:05:00+08:00",
    "sourceSections": [
      "crypto",
      "radar",
      "vibe",
      "reading"
    ],
    "missingSections": [],
    "marketSignals": [
      {
        "title": "AFX 自营 USDC 托管桥遭利用",
        "summary": "AFX 确认其在 Arbitrum 上运营的 USDC custody bridge 发生安全事件并暂停桥接，Blockaid 初步估算约 2,415 万 USDC 被转出。现有证据指向第三方托管桥的独立信任与运维风险，不能据此认定 Arbitrum 原生桥或主网被攻破；完整根因、最终损失和追回结果仍待披露。",
        "sourceUrl": "https://x.com/AFX_XYZ/status/2080126901205770734"
      },
      {
        "title": "俄罗斯拟将加密货币持有、交易与跨境结算纳入许可体系",
        "summary": "俄罗斯央行称，国家杜马通过拟于 2026 年 9 月 1 日生效的加密货币流通规则：非合格投资者通过测试后受年度额度约束，合格投资者通过测试后不设同类金额上限，进出口商可用于跨境支付，但境内支付仍被禁止。具体高流动性资产清单、中介准入与执行细则尚未公布。",
        "sourceUrl": "https://www.cbr.ru/eng/press/event/?id=32724"
      },
      {
        "title": "Robinhood CEO 的 X 账号被劫持并推广假迷因币",
        "summary": "Robinhood 官方确认 CEO Vlad Tenev 的 X 账号遭入侵，攻击者借可信身份发布虚假迷因币推广内容，相关帖子随后被删除。通报未显示 Robinhood 应用、客户账户、客户资金或 Robinhood Chain 遭入侵，也未披露是否产生用户损失。",
        "sourceUrl": "https://x.com/RobinhoodComms/status/2080353603160584640"
      }
    ],
    "aiTip": {
      "title": "把 Agent 评测拆成结果状态与执行轨迹两套断言",
      "summary": "用确定性断言检查数据库、文件、测试或远端对象的最终状态，再用规则或经人工校准的模型 grader 检查完整工具轨迹中的越权、绕过审批、重复重试与高成本路径。每个版本运行多次隔离副作用的 trial，分别保留结果通过率和轨迹违规率，避免“完成但危险”与“过程合理但未完成”被一个总分抵消。",
      "sourceUrl": "https://www.anthropic.com/engineering/demystifying-evals-for-ai-agents"
    },
    "web3Design": {
      "title": "用显式 nonce 域解除同一账户下无关操作的全局串行",
      "summary": "EIP-8250 草案用 nonce key 集合与序列建立独立的重放顺序。钱包基础设施可迁移版本化 nonceDomains、规范化排序、域集合冲突检测、幂等广播与替换，以及把完整域集合哈希绑定进签名摘要；但该草案依赖未定稿的 EIP-8141，具体 key 数量、序列位宽、gas、支付批准与回滚规则不能直接照搬到其他链。",
      "sourceUrl": "https://eips.ethereum.org/EIPS/eip-8250"
    },
    "vibeProject": {
      "title": "GitNexus · 本地代码知识图谱与 Agent 影响分析",
      "summary": "GitNexus 用 Tree-sitter、图数据库、CLI 与 MCP 在本地索引文件、符号、导入、调用和继承关系，为编码 Agent 提供查询、路径追踪与变更影响线索。固定 v1.6.9 的小仓库流程已可复现，但 PolyForm Noncommercial 许可证限制商业使用，静态启发式图谱、FTS 警告和缺失 execution flow 也意味着它不能替代测试、运行时追踪与人工审阅。",
      "sourceUrl": "https://github.com/abhigyanpatwari/GitNexus"
    },
    "readingPick": {
      "title": "The cost of saying yes has changed",
      "summary": "AI 降低了首版代码的生成成本，却没有同步降低理解、审查、上线和长期维护成本。文章建议用边界明确的最小补丁作为需求的“价格检查”，但最终判断应是人能否验证并承担这个行为。行动问题：为一个近期小需求写下不可改变的契约、可触碰范围、测试与红线；当试做补丁越过哪条边界时，应升级为正式设计决策？",
      "sourceUrl": "https://github.blog/engineering/the-cost-of-saying-yes-has-changed/"
    },
    "sourceUrls": [
      "https://x.com/AFX_XYZ/status/2080126901205770734",
      "https://x.com/blockaid_/status/2080080240265621680",
      "https://www.cbr.ru/eng/press/event/?id=32724",
      "https://x.com/RobinhoodComms/status/2080353603160584640",
      "https://www.anthropic.com/engineering/demystifying-evals-for-ai-agents",
      "https://eips.ethereum.org/EIPS/eip-8250",
      "https://github.com/abhigyanpatwari/GitNexus",
      "https://github.com/abhigyanpatwari/GitNexus/releases/tag/v1.6.9",
      "https://registry.npmjs.org/gitnexus/latest",
      "https://api.npmjs.org/downloads/point/2026-06-22:2026-07-21/gitnexus",
      "https://github.com/abhigyanpatwari/GitNexus/issues/1939",
      "https://github.com/abhigyanpatwari/GitNexus/blob/v1.6.9/LICENSE",
      "https://github.com/sindresorhus/yoctocolors",
      "https://github.blog/engineering/the-cost-of-saying-yes-has-changed/"
    ],
    "relatedProjectSlugs": [
      "wallet-core",
      "exchange-wallet-system",
      "web3-wallet-engineer-lab"
    ]
  },
  {
    "date": "2026-07-23",
    "slug": "2026-07-23",
    "title": "每日研究雷达 · 2026-07-23",
    "summary": "聚焦共识客户端安全升级、故障证明进程治理、测试网协议变更、Agent PR 风险路由、不可逆密钥迁移，以及本地任务规格管理。",
    "reviewStatus": "automated",
    "generatedAt": "2026-07-23T07:02:51+08:00",
    "sourceSections": [
      "crypto",
      "radar",
      "vibe",
      "reading"
    ],
    "missingSections": [],
    "marketSignals": [
      {
        "title": "Lighthouse v8.2.1 将主网信标节点升级列为高优先级安全事项",
        "summary": "Sigma Prime 称该版本修复多项安全漏洞，并修正 EIP-8136 partial data columns 的缓存与 gossip 行为，要求主网 beacon node 用户尽快升级。漏洞细节暂未公开，不能判断可利用条件、影响范围或是否已被利用；data-column backfill 的 OOM 风险也仍待后续版本修复。",
        "sourceUrl": "https://github.com/sigp/lighthouse/releases/tag/v8.2.1"
      },
      {
        "title": "op-challenger v1.9.4 收束超时后的 VM 进程残留",
        "summary": "OP Labs 的补丁版会在 --vm-timeout 触发时终止整个 VM 进程组，并用包含工具链 CVE 修复的 Go 版本重建镜像，改善 fault-proof 挑战器的故障恢复与运行环境安全。官方将升级标为可选但推荐，相关 ZK 与 super dispute games 尚未在生产启用。",
        "sourceUrl": "https://github.com/ethereum-optimism/optimism/releases/tag/op-challenger/v1.9.4"
      },
      {
        "title": "Avalanche Helicon 在 Fuji 排定六项协议变更",
        "summary": "AvalancheGo v1.15.0-fuji 为 7 月 28 日的 Fuji 激活安排执行、验证者、质押与费用规则变更，并要求测试网节点提前升级。该二进制明确拒绝主网配置，且激活后暂不支持 C-Chain state sync，不能视为主网版本已经就绪。",
        "sourceUrl": "https://github.com/ava-labs/avalanchego/releases/tag/v1.15.0-fuji"
      }
    ],
    "aiTip": {
      "title": "用多信号置信度路由 Agent PR",
      "summary": "不要依赖模型自报信心；把阻断性工程规范、远程沙箱测试与流量回放、Agent 版本评测趋势，以及 agent × repo × change-class 的历史回滚率组合成可审计路由。先从低风险变更校准阈值，只有各项同时过线才自动合并，否则附上失败信号转人工。",
      "sourceUrl": "https://aws.amazon.com/blogs/machine-learning/ai-teammates-how-monday-com-runs-production-ai-agents-on-amazon-bedrock/"
    },
    "web3Design": {
      "title": "把不可逆签名算法迁移建模为独立密钥状态机",
      "summary": "EIP-8164 草案把 EOA 从 ECDSA 迁移到 ML-DSA-44 后的认证切换设计为不可回退状态。钱包系统可借鉴版本化 migration/rotation envelope、链上状态重验、同账户串行化和激活后禁用旧算法，但该草案仍未定稿且缺少恢复机制，不能在链未采纳时模拟协议级失效。",
      "sourceUrl": "https://eips.ethereum.org/EIPS/eip-8164"
    },
    "vibeProject": {
      "title": "Backlog.md · 仓库内的 Agent 任务规格与审阅工作流",
      "summary": "Backlog.md 将任务、验收条件、里程碑、依赖和决策保存为可版本化 Markdown，并提供 CLI、终端与本地 Web 看板。固定 v1.48.0 的无 Git 流程已可复现；多人或多 Agent 共用工作树时，autoCommit 可能把未审阅草稿和其他脏改动卷入提交，应保持关闭并使用隔离 worktree。",
      "sourceUrl": "https://github.com/MrLesk/Backlog.md"
    },
    "readingPick": {
      "title": "Towards demystifying the creativity of diffusion models",
      "summary": "文章以 score smoothing 解释扩散模型如何在靠近数据流形的同时减少向有限训练样本坍缩，把所谓创造力拆成可实验的函数近似与正则化机制。行动问题：能否为一个熟悉的生成任务同时设计真实性、训练样本距离和任务有效性指标，并明确它们仍无法证明什么？",
      "sourceUrl": "https://www.research.google/blog/towards-demystifying-the-creativity-of-diffusion-models/"
    },
    "sourceUrls": [
      "https://github.com/sigp/lighthouse/releases/tag/v8.2.1",
      "https://github.com/ethereum-optimism/optimism/releases/tag/op-challenger/v1.9.4",
      "https://github.com/ava-labs/avalanchego/releases/tag/v1.15.0-fuji",
      "https://aws.amazon.com/blogs/machine-learning/ai-teammates-how-monday-com-runs-production-ai-agents-on-amazon-bedrock/",
      "https://eips.ethereum.org/EIPS/eip-8164",
      "https://github.com/MrLesk/Backlog.md",
      "https://github.com/MrLesk/Backlog.md/releases/tag/v1.48.0",
      "https://raw.githubusercontent.com/MrLesk/Backlog.md/v1.48.0/README.md",
      "https://api.npmjs.org/downloads/point/2026-06-22:2026-07-21/backlog.md",
      "https://github.com/MrLesk/Backlog.md/issues/795",
      "https://www.research.google/blog/towards-demystifying-the-creativity-of-diffusion-models/"
    ],
    "relatedProjectSlugs": [
      "wallet-core",
      "exchange-wallet-system",
      "web3-wallet-engineer-lab"
    ]
  },
  {
    "date": "2026-07-22",
    "slug": "2026-07-22",
    "title": "每日研究雷达 · 2026-07-22",
    "summary": "聚焦资金基础设施恢复隔离、跨链池安全事件、可验证提示词构建、Agent 签名策略，以及多 Agent 工作树隔离。",
    "reviewStatus": "automated",
    "generatedAt": "2026-07-22T07:03:47+08:00",
    "sourceSections": [
      "crypto",
      "radar",
      "vibe"
    ],
    "missingSections": [
      "reading"
    ],
    "marketSignals": [
      {
        "title": "Coinbase 网关配置冲突暴露恢复路径的循环依赖",
        "summary": "Coinbase 对 7 月 14 日约 50 分钟服务降级的复盘显示，一次 Kubernetes 资源重名意外修改了 Istio ingress gateway，而标准回滚工具也依赖该网关，最终需借助云控制面和临时特权路径恢复；这提示资金基础设施应隔离部署面与恢复面。客户资金安全与积压任务完成情况来自 Coinbase 自述，尚无独立审计材料佐证。",
        "sourceUrl": "https://www.coinbase.com/blog/a-postmortem-of-our-july-14-2026-incident"
      },
      {
        "title": "Aptos 测试网要求采用未公开源码的私有热修复",
        "summary": "Aptos 要求测试网验证者与全节点升级到 1.48.3-hotfix，但仅提供二进制或镜像且未公开源码。该预发布版本没有说明具体缺陷，不能据此推断主网受影响、漏洞已被利用或二进制已经独立审计。",
        "sourceUrl": "https://github.com/aptos-labs/aptos-core/releases/tag/aptos-node-v1.48.3-hotfix-rc"
      },
      {
        "title": "Allbridge Core 事件凸显跨链稳定币池定价风险",
        "summary": "Allbridge 已确认安全事件、暂停协议并要求受影响池的流动性提供者撤出；CertiK 将链上活动定位到 Solana 部署并估计约 165 万美元资产被转移。完整根因、最终损失、资金追回与重启安排仍待项目复盘，当前链上归因不应视为最终审计结论。",
        "sourceUrl": "https://x.com/Allbridge_io/status/2078932561036722319"
      }
    ],
    "aiTip": {
      "title": "把生产提示词编译成可验证的不可变产物",
      "summary": "将身份与安全边界、工具规则和领域流程拆成显式依赖模块，在构建阶段解析引用与环境变量，检查缺失引用、未定义变量和循环依赖，并以固定输入对生成产物做 golden-file 漂移检测。语法正确不代表指令无冲突，仍需端到端行为评测和运行时 skill 的版本、权限与观测控制。",
      "sourceUrl": "https://developers.googleblog.com/en/building-scalable-ai-agents-with-modular-prompt-transpilation/"
    },
    "web3Design": {
      "title": "用策略哈希把 Agent 签名权收敛为可撤销额度",
      "summary": "ERC-8196 将 agent、目标与动作、额度和有效期编码进授权策略，并在 EIP-712 动作摘要中绑定 policyHash、nonce、到期时间与 entropy commitment。wallet-api 可规范化策略与摘要，wallet-service 负责生命周期、额度、防重放、撤销及广播前复核，wallet-sign 只签域分离摘要；Ethereum 字段、额度语义和目标白名单不能直接移植到其他链，生产实现仍需参数级策略、模拟、费用上限和并发原子扣减。",
      "sourceUrl": "https://eips.ethereum.org/EIPS/eip-8196"
    },
    "vibeProject": {
      "title": "Claude Squad · 用 worktree 隔离多个终端编码 Agent",
      "summary": "Claude Squad 通过 tmux 保持独立会话，以 Git worktree 和分支隔离任务，并在 TUI 中提供会话管理、diff 预览和 Git 操作。固定 v1.0.19 的测试与构建已通过，但未完成 tmux 端到端交互验证；工具可创建或清理 worktree、提交、checkout 和 push，实验性的 --autoyes 也会扩大误操作与权限风险。",
      "sourceUrl": "https://github.com/smtg-ai/claude-squad"
    },
    "sourceUrls": [
      "https://www.coinbase.com/blog/a-postmortem-of-our-july-14-2026-incident",
      "https://github.com/aptos-labs/aptos-core/releases/tag/aptos-node-v1.48.3-hotfix-rc",
      "https://x.com/Allbridge_io/status/2078932561036722319",
      "https://x.com/CertiKAlert/status/2079013163014770987",
      "https://developers.googleblog.com/en/building-scalable-ai-agents-with-modular-prompt-transpilation/",
      "https://eips.ethereum.org/EIPS/eip-8196",
      "https://github.com/smtg-ai/claude-squad",
      "https://github.com/smtg-ai/claude-squad/releases/tag/v1.0.19",
      "https://api.github.com/repos/smtg-ai/claude-squad/releases?per_page=100",
      "https://formulae.brew.sh/api/formula/claude-squad.json",
      "https://github.com/smtg-ai/claude-squad/issues/215"
    ],
    "relatedProjectSlugs": [
      "wallet-core",
      "exchange-wallet-system",
      "web3-wallet-engineer-lab"
    ]
  },
  {
    "date": "2026-07-21",
    "slug": "2026-07-21",
    "title": "每日研究雷达 · 2026-07-21",
    "summary": "聚焦协议升级与监管核验、Agent 凭证绑定的出网代理、钱包调用准备协议，以及可验证的 AI 工具用量治理。",
    "reviewStatus": "automated",
    "generatedAt": "2026-07-21T07:03:40+08:00",
    "sourceSections": [
      "crypto",
      "radar",
      "vibe",
      "reading"
    ],
    "missingSections": [],
    "marketSignals": [
      {
        "title": "NEAR 协议版本 86 进入升级投票窗口",
        "summary": "NEAR Core 2.13.1 要求希望继续参与共识的节点在投票窗口前升级，并给出投票成功后的预计激活安排；这不代表协议版本 86 已在主网完成激活，仍需以链上状态和官方后续通告为准。",
        "sourceUrl": "https://github.com/near/nearcore/releases/tag/2.13.1"
      },
      {
        "title": "Sui devnet 为有网络认证结果的分叉增加自动恢复",
        "summary": "Sui devnet v1.76.0 允许验证者在重启并部署新二进制后，对已有网络认证规范结果的 checkpoint 或交易分叉自动恢复；没有认证结果或错误仍存在于当前二进制时，节点仍会停机等待处理，且该能力不能据此视为已部署到主网。",
        "sourceUrl": "https://github.com/MystenLabs/sui/releases/tag/devnet-v1.76.0"
      },
      {
        "title": "MiCA 过渡期结束后中央登记成为公开核验入口",
        "summary": "ESMA 按周汇总白皮书、ART 与 EMT 发行人、获授权 CASP 和不合规实体，为欧盟加密资产服务商状态提供统一公开入口；登记存在报送时间差，白皮书入册也不等于获得监管批准。",
        "sourceUrl": "https://www.esma.europa.eu/esmas-activities/digital-finance-and-innovation/markets-crypto-assets-regulation-mica"
      }
    ],
    "aiTip": {
      "title": "把 Agent 出网白名单改造成凭证绑定的能力代理",
      "summary": "长期凭证不进入 Agent 沙箱，只下发单次运行、最小权限且可撤销的会话令牌；代理同时校验域名、方法、路径、令牌来源与账户，并默认拒绝未声明能力。这项环境层收口仍需配合文件系统隔离、工具最小权限和注入检测。",
      "sourceUrl": "https://www.anthropic.com/engineering/how-we-contain-claude"
    },
    "web3Design": {
      "title": "用 prepare → sign → submit 隔离账户编码与签名执行",
      "summary": "ERC-7836 草案让钱包先把调用转换为带上下文、链与版本信息的待签摘要，再接收签名执行。wallet-api 可提供短时幂等的 prepare/submit 接口，wallet-service 负责链相关编码、策略校验与提交前重算，wallet-sign 只处理域分离摘要和归一化策略元数据；草案字段与 EVM 语义不能直接套用到其他链。",
      "sourceUrl": "https://eips.ethereum.org/EIPS/eip-7836"
    },
    "vibeProject": {
      "title": "OpenUsage · 多种 AI 编码工具的本地用量仪表盘",
      "summary": "OpenUsage 用 Go 汇总 Claude Code、Codex、Cursor、Copilot、Gemini CLI 与 OpenRouter 等工具的配额、费用和重置时间，并支持 TUI、无头报告与本地历史。项目可在固定版本构建运行，但会接触本地日志、数据库和凭证环境，且测试存在环境隔离不足，不能把可启动等同于全面可靠。",
      "sourceUrl": "https://github.com/janekbaraniewski/openusage"
    },
    "readingPick": {
      "title": "AI Mania Is Eviscerating Global Decision-Making",
      "summary": "文章从组织激励与反馈回路审视 AI 项目，提醒团队不要把 token、调用量或许可证数误当业务成果，并建议用基线、停止条件和无惩罚坏消息通道恢复真实反馈。行动问题：你熟悉的一个 AI 项目，哪项结果指标最不容易被工具使用量替代？",
      "sourceUrl": "https://ludic.mataroa.blog/blog/ai-mania-is-eviscerating-global-decision-making/"
    },
    "sourceUrls": [
      "https://github.com/near/nearcore/releases/tag/2.13.1",
      "https://github.com/MystenLabs/sui/releases/tag/devnet-v1.76.0",
      "https://www.esma.europa.eu/esmas-activities/digital-finance-and-innovation/markets-crypto-assets-regulation-mica",
      "https://www.anthropic.com/engineering/how-we-contain-claude",
      "https://eips.ethereum.org/EIPS/eip-7836",
      "https://github.com/janekbaraniewski/openusage",
      "https://github.com/janekbaraniewski/openusage/releases/tag/v0.24.0",
      "https://api.github.com/repos/janekbaraniewski/openusage/releases?per_page=100",
      "https://github.com/janekbaraniewski/openusage/issues/216",
      "https://github.com/janekbaraniewski/openusage/issues/268",
      "https://github.com/janekbaraniewski/openusage/blob/v0.24.0/internal/providers/hermes/hermes_test.go",
      "https://ludic.mataroa.blog/blog/ai-mania-is-eviscerating-global-decision-making/"
    ],
    "relatedProjectSlugs": [
      "wallet-core",
      "exchange-wallet-system",
      "web3-wallet-engineer-lab"
    ]
  },
  {
    "date": "2026-07-20",
    "slug": "2026-07-20",
    "title": "每日研究雷达 · 2026-07-20",
    "summary": "关注 Bitcoin 共识形式化验证与节点维护修复、以任务锚点约束 Agent 工具轨迹，以及为钱包扫描器提供最小只读内核视图。",
    "reviewStatus": "automated",
    "generatedAt": "2026-07-20T08:48:39+08:00",
    "sourceSections": [
      "crypto",
      "radar",
      "vibe",
      "reading"
    ],
    "missingSections": [],
    "marketSignals": [
      {
        "title": "Bitcoin 协议形式化验证开始落到可运行组件",
        "summary": "btc-verified 正用 Lean 4 表达 Bitcoin 的序列化、交易 ID、Merkle 承诺与链状态，并针对真实主网数据运行检查。当前成果仍是早期 proof leaves，不能视为完整共识、供应上限或分叉选择已经获得端到端证明。",
        "sourceUrl": "https://github.com/ProofOfKeags/btc-verified"
      },
      {
        "title": "Bitcoin Core 30.3/29.4 修复链状态异常磁盘重写",
        "summary": "两个维护版本修复正常运行时可能造成过量磁盘读写的 chainstate 问题，并包含钱包、PSBT、miniscript、网络与测试修复。升级前仍需核对官方说明、签名和部署兼容性。",
        "sourceUrl": "https://bitcoincore.org/bin/bitcoin-core-30.3/"
      },
      {
        "title": "LND 封堵辅助资产通道的不安全 RBF 关闭路径",
        "summary": "已合并的 LND 编号 10962 变更禁止 Taproot Assets 等 auxiliary channel 进入缺少资产辅助钩子的 RBF cooperative-close 流程，避免资产承诺丢失与通道卡住。该问题和修复针对 LND 特定实现路径。",
        "sourceUrl": "https://github.com/lightningnetwork/lnd/pull/10962"
      }
    ],
    "aiTip": {
      "title": "让 Agent 从任务锚点收窄证据",
      "summary": "对代码审查类任务，从 diff 形成具体问题，先批量用 grep/glob 找候选，再用 view 读取最小证据范围，并以工具 trace 检查是否持续围绕证据。GitHub 在该窄任务上报告平均 review 成本约降 20%，但也明确说明同样提示不适合直接复制到开放式 CLI 编码任务。",
      "sourceUrl": "https://github.blog/ai-and-ml/github-copilot/better-tools-made-copilot-code-review-worse-heres-how-we-actually-improved-it/"
    },
    "web3Design": {
      "title": "为钱包扫描器提供最小只读内核视图",
      "summary": "Bitcoin Core 通过 libbitcoinkernel 暴露 witness stack 与 scriptSig 视图，让 Silent Payment 扫描器复用核心解析结果。wallet-service 可借鉴“核心暴露受限只读视图、扫描层消费稳定接口”的分层；wallet-api 应限制字段大小与生命周期，wallet-sign 不应重复解析同一不可信原始交易。Bitcoin 的 C API 和 witness 语义不能原样移植到其他链。",
      "sourceUrl": "https://github.com/bitcoin/bitcoin/pull/35380"
    },
    "vibeProject": {
      "title": "Grok Build · 可检查的 Rust 编码 Agent Harness 与 TUI",
      "summary": "项目同时支持全屏终端交互、无头脚本/CI 和 ACP 编辑器嵌入，并公开工具、工作区、沙箱与插件实现。2026-07-20 的 GitHub 数据约为 2 万 stars、3600 forks；高关注度不等于生产可靠性，仓库从公司 monorepo 同步且暂不接受外部贡献。",
      "sourceUrl": "https://github.com/xai-org/grok-build"
    },
    "readingPick": {
      "title": "Autoconf’s revenge: ad-hoc shell templates",
      "summary": "Julio Merino 用 Bazel wrapper 展示如何以受限、透明的生成层补齐少量条件配置，而不引入完整模板框架。行动问题：你当前哪一份多环境配置，只需要变量替换与整行启停就能合并为一个可审查模板？",
      "sourceUrl": "https://jmmv.dev/2026/07/ad-hoc-shell-templates.html"
    },
    "sourceUrls": [
      "https://github.com/ProofOfKeags/btc-verified",
      "https://bitcoinops.org/en/newsletters/2026/07/17/",
      "https://bitcoincore.org/bin/bitcoin-core-30.3/",
      "https://github.com/lightningnetwork/lnd/pull/10962",
      "https://github.blog/ai-and-ml/github-copilot/better-tools-made-copilot-code-review-worse-heres-how-we-actually-improved-it/",
      "https://github.com/bitcoin/bitcoin/pull/35380",
      "https://bitcoinops.org/en/topics/silent-payments/",
      "https://github.com/xai-org/grok-build",
      "https://jmmv.dev/2026/07/ad-hoc-shell-templates.html"
    ],
    "relatedProjectSlugs": [
      "wallet-core",
      "exchange-wallet-system",
      "web3-wallet-engineer-lab"
    ]
  },
  {
    "date": "2026-07-19",
    "slug": "2026-07-19",
    "title": "每日研究雷达 · 2026-07-19",
    "summary": "关注 MiCA 过渡期结束后的有序退出、可复现的 Agent 评测记录、可缩减的钱包执行权限，以及为 Agent API 支付设计的 HTTP 中间件。",
    "reviewStatus": "automated",
    "generatedAt": "2026-07-19T15:11:15+08:00",
    "sourceSections": [
      "crypto",
      "radar",
      "vibe",
      "reading"
    ],
    "missingSections": [],
    "marketSignals": [
      {
        "title": "MiCA 过渡期结束后的有序退出成为运营要求",
        "summary": "ESMA 更新的 MiCA 信息说明，原国家制度下提供服务实体的最长期过渡安排截至 2026-07-01；未获授权的服务商应有序停止欧盟活动并保护客户利益。该监管信号不构成对具体公司授权状态或资产安全的判断。",
        "sourceUrl": "https://www.esma.europa.eu/esmas-activities/digital-finance-and-innovation/markets-crypto-assets-regulation-mica"
      },
      {
        "title": "监管预期从注册状态延伸到产品退出流程",
        "summary": "ESMA 的公开声明强调，未获授权的 CASP 应立即且有序停止欧盟活动。面向欧盟用户的产品应预先设计新增客户停止、资产转移、用户通知和可审计的退出状态；具体适用仍须结合成员国执行与个案核对。",
        "sourceUrl": "https://www.esma.europa.eu/sites/default/files/2026-06/ESMA75-113276571-1710_Public_Statement_MiCA_transitional_period_ends.pdf"
      }
    ],
    "aiTip": {
      "title": "让每次 Agent 评测保留“主张—环境—证据”记录",
      "summary": "将待验证主张、模型/提示词/工具版本/权限/超时等运行环境，以及测试输出、人工抽样和失败原因并列记录。同一任务结果不同时，先比较环境差异，以发现评分器问题、环境漂移或不可复现的偶然通过。",
      "sourceUrl": "https://openai.com/index/trustworthy-third-party-evaluations-foundations/"
    },
    "web3Design": {
      "title": "ERC-7715 的可缩减执行权限",
      "summary": "将权限请求、批准版本、账户与链上下文、有效期和撤销状态作为审计记录；每次执行校验目标、调用数据、链、上下文与过期时间。签名前展示可读范围并绑定策略哈希和有效期。该提案不替代服务端鉴权、密钥托管、风控或重放防护。",
      "sourceUrl": "https://eips.ethereum.org/EIPS/eip-7715"
    },
    "vibeProject": {
      "title": "Faremeter · 面向 HTTP 服务的机器间小额支付",
      "summary": "Faremeter 提供 TypeScript 客户端、中间件、支付 facilitator、Nginx 网关和 OpenAPI 定价中间件，用于为按次 API 访问建立支付闭环。采用时可先在只读低风险 API 验证 402、付款凭证和资源返回，并以幂等键与过期时间处理重试；公开仓库信息不等同于生产采用或安全审计。",
      "sourceUrl": "https://github.com/faremeter/faremeter"
    },
    "readingPick": {
      "title": "Introducing Precursor: detecting agentic behavior with continuous client-side signals",
      "summary": "文章讨论用持续客户端信号与风险式挑战识别自动化或代理式浏览行为，启发将信号采集、策略决策、用户确认和审计分离。行动问题：对一个会触发外部副作用的 Agent 操作，哪三类连续信号应分别用于记录、加验证或阻断？",
      "sourceUrl": "https://blog.cloudflare.com/introducing-precursor/"
    },
    "sourceUrls": [
      "https://www.esma.europa.eu/esmas-activities/digital-finance-and-innovation/markets-crypto-assets-regulation-mica",
      "https://www.esma.europa.eu/sites/default/files/2026-06/ESMA75-113276571-1710_Public_Statement_MiCA_transitional_period_ends.pdf",
      "https://coinmarketcap.com/zh/",
      "https://openai.com/index/trustworthy-third-party-evaluations-foundations/",
      "https://eips.ethereum.org/EIPS/eip-7715",
      "https://github.com/faremeter/faremeter",
      "https://blog.cloudflare.com/introducing-precursor/"
    ],
    "relatedProjectSlugs": [
      "wallet-core",
      "exchange-wallet-system",
      "web3-wallet-engineer-lab"
    ]
  },
  {
    "date": "2026-07-18",
    "slug": "2026-07-18",
    "title": "每日研究雷达 · 2026-07-18",
    "summary": "关注稳定币机构接入、Agent 的公开 URL 预检、策略绑定的钱包代理授权，以及团队级编码代理的可控交付。",
    "reviewStatus": "automated",
    "generatedAt": "2026-07-18T09:47:07+08:00",
    "sourceSections": [
      "crypto",
      "radar",
      "vibe",
      "reading"
    ],
    "missingSections": [],
    "marketSignals": [
      {
        "title": "稳定币供给与现货成交量同步收缩",
        "summary": "CoinGecko 的 2026 年第二季度回顾显示加密资产总市值、稳定币市值和前十大中心化交易所现货成交量均下降；这些聚合指标适合观察行业流动性变化，不能用于预测单一资产价格。",
        "sourceUrl": "https://www.coingecko.com/research/publications/2026-q2-crypto-report"
      },
      {
        "title": "BNY 将 USDC 托管、铸造与赎回接入机构工作流",
        "summary": "BNY 扩大与 Circle 的合作，使客户可在其托管钱包中持有和转移 USDC，并指示 Circle 以美元铸造或赎回；公告不代表所有机构或司法辖区均可使用。",
        "sourceUrl": "https://www.circle.com/pressroom/bny-expands-relationship-with-circle-and-adds-to-institutional-grade-stablecoin-enablement-services"
      },
      {
        "title": "Standard Chartered 推出面向合格机构的 USDC 进出通道",
        "summary": "Standard Chartered 与 Circle 宣布面向符合条件机构客户的 USDC 铸造与赎回能力；系统设计仍应区分请求发起、账户权限、资金状态与链上最终性。",
        "sourceUrl": "https://www.circle.com/pressroom/standard-chartered-and-circle-launch-launch-first-g-sib-led-integrated-access-to-usdc-minting-and-redemption"
      }
    ],
    "aiTip": {
      "title": "以“已知公开 URL”作为 Agent 自动抓取前置条件",
      "summary": "自动抓取只接受独立索引已知的公开精确 URL，未命中链接进入确认或替代检索路径；用公开命中、未命中、重定向和会话参数 URL 建立回归用例，降低外发用户特定数据的风险。",
      "sourceUrl": "https://openai.com/index/ai-agent-link-safety/"
    },
    "web3Design": {
      "title": "ERC-8196 将代理授权绑定为可验证策略",
      "summary": "代理钱包仅在交易证明符合资产所有者策略时执行；将策略、委托、会话、撤销与策略哈希建模为版本化记录，并在签名时绑定账户、链、有效期与调用范围。该提案仍是草案，不能替代服务端鉴权或密钥保管设计。",
      "sourceUrl": "https://eips.ethereum.org/EIPS/eip-8196"
    },
    "vibeProject": {
      "title": "Cursor · 团队级编码代理工作流",
      "summary": "Cursor 的 NVIDIA 案例展示了将代码生成、测试、调试与部署嵌入团队工作流的路径；采用时应先从有明确验收测试的小范围任务开始，以 PR 周期、回滚率与测试通过率衡量，而非只看代码生成量。",
      "sourceUrl": "https://cursor.com/blog/nvidia"
    },
    "readingPick": {
      "title": "GPT-5.6: Frontier intelligence that scales with your ambition",
      "summary": "文章将长程工作流能力、按需推理强度、成本与安全防护放在同一取舍框架。行动问题：你的真实工作流中，哪一步值得升级推理强度，哪一步应保持低成本模型并加入人工确认？",
      "sourceUrl": "https://openai.com/index/gpt-5-6/"
    },
    "sourceUrls": [
      "https://www.coingecko.com/research/publications/2026-q2-crypto-report",
      "https://www.circle.com/pressroom/bny-expands-relationship-with-circle-and-adds-to-institutional-grade-stablecoin-enablement-services",
      "https://www.circle.com/pressroom/standard-chartered-and-circle-launch-launch-first-g-sib-led-integrated-access-to-usdc-minting-and-redemption",
      "https://openai.com/index/ai-agent-link-safety/",
      "https://eips.ethereum.org/EIPS/eip-8196",
      "https://cursor.com/blog/nvidia",
      "https://openai.com/index/gpt-5-6/"
    ],
    "relatedProjectSlugs": [
      "wallet-core",
      "exchange-wallet-system",
      "web3-wallet-engineer-lab"
    ]
  },
  {
    "date": "2026-07-17",
    "slug": "2026-07-17",
    "title": "每日研究雷达 · 2026-07-17",
    "summary": "聚焦 AI 安全分诊与提示注入回归测试、钱包批量调用和隐私模块化，以及链上基础设施的可复核安全边界。",
    "reviewStatus": "automated",
    "generatedAt": "2026-07-17T09:25:53+08:00",
    "sourceSections": [
      "crypto",
      "radar",
      "vibe",
      "reading"
    ],
    "missingSections": [],
    "marketSignals": [
      {
        "title": "AI 安全研究强调可复核的漏洞分诊",
        "summary": "Ethereum Foundation Protocol Security 披露其协调运行的 AI 代理在真实协议代码中发现漏洞，并将可复现、分诊与披露视为交付的一部分；这反映链上基础设施采用 AI 时，修复流程与告警数量同样重要。",
        "sourceUrl": "https://blog.ethereum.org/2026/07/09/triage-is-the-product"
      },
      {
        "title": "Clear Signing 正走向共享安全基础设施",
        "summary": "钱包开发者、安全机构与基金会共同推出开放的 Clear Signing 标准和注册表，目标是减少盲签；标准本身不能替代对合约、授权额度和钓鱼风险的独立检查。",
        "sourceUrl": "https://blog.ethereum.org/2026/05/12/clear-signing"
      },
      {
        "title": "libp2p 公开漏洞应进入节点依赖门禁",
        "summary": "NVD 记录的 CVE-2026-34219 与 libp2p gossipsub 远程触发 panic 有关；实际受影响范围仍需按具体实现、版本和补丁状态核验。",
        "sourceUrl": "https://nvd.nist.gov/vuln/detail/CVE-2026-34219"
      }
    ],
    "aiTip": {
      "title": "将提示注入防护变成可回归的攻击用例集",
      "summary": "为会调用工具的任务维护固定恶意输入和可判定预期，在提示词、工具权限或模型版本变化后重跑；这能把安全改动从主观试玩转成可比较的工程信号。",
      "sourceUrl": "https://openai.com/index/unlocking-self-improvement-gpt-red/"
    },
    "web3Design": {
      "title": "EIP-5792 以能力协商分离应用意图与钱包实现",
      "summary": "`wallet_sendCalls` 将多笔调用作为一个请求交给钱包，并可通过能力协商决定是否支持批量、原子执行或 paymaster；服务端仍应校验链、地址、calldata、幂等键和签名绑定，不能把能力声明当作用户授权。",
      "sourceUrl": "https://eips.ethereum.org/EIPS/eip-5792"
    },
    "vibeProject": {
      "title": "Kohaku · 模块化的钱包隐私能力试验场",
      "summary": "Kohaku 将私密读写、隐私池、轻客户端和后量子账户等能力拆成可替换模块；适合先从可替换的读取 adapter 验证隐私收益与可用性，但未完成部分不应视为生产审计或匿名性证明。",
      "sourceUrl": "https://github.com/ethereum/kohaku"
    },
    "readingPick": {
      "title": "The next great wallet will be private",
      "summary": "文章将钱包隐私拆成启动网络请求、RPC 认知、DApp 地址关联和支付关系等可观察层。行动问题：一次钱包操作的五个阶段中，哪一处能以最小可用性代价减少地址关联？",
      "sourceUrl": "https://ethereum.org/latest/next-great-wallet-private"
    },
    "sourceUrls": [
      "https://blog.ethereum.org/2026/07/09/triage-is-the-product",
      "https://blog.ethereum.org/2026/05/12/clear-signing",
      "https://nvd.nist.gov/vuln/detail/CVE-2026-34219",
      "https://coinmarketcap.com/zh/",
      "https://openai.com/index/unlocking-self-improvement-gpt-red/",
      "https://eips.ethereum.org/EIPS/eip-5792",
      "https://github.com/ethereum/kohaku",
      "https://ethereum.github.io/kohaku/getting-started/",
      "https://ethereum.org/latest/next-great-wallet-private"
    ],
    "relatedProjectSlugs": [
      "wallet-core",
      "exchange-wallet-system",
      "web3-wallet-engineer-lab"
    ]
  },
  {
    "date": "2026-07-16",
    "slug": "2026-07-16",
    "title": "每日研究雷达 · 2026-07-16",
    "summary": "关注美英稳定币协作与美国加密资产分类解释，把 AI 评测变成可复跑实验，并用多钱包发现机制明确签名边界。",
    "reviewStatus": "automated",
    "generatedAt": "2026-07-16T17:22:02+08:00",
    "sourceSections": [
      "crypto",
      "radar",
      "vibe",
      "reading"
    ],
    "missingSections": [],
    "marketSignals": [
      {
        "title": "美英将跨境稳定币活动纳入联合工作项",
        "summary": "两国财政部门发布未来市场工作组建议及稳定币联合声明，显示跨境稳定币服务的合规接口与运营边界正成为产品基础设施议题；这属于政策方向，并非对具体业务的批准。",
        "sourceUrl": "https://home.treasury.gov/news/press-releases/sb0560"
      },
      {
        "title": "SEC 与 CFTC 的加密资产分类解释已生效",
        "summary": "面向美国市场的资产展示、发行与交易流程，应分别记录资产特性、发行方承诺和交易活动，不能只按代币名称判断合规属性；具体业务仍需专业法律意见。",
        "sourceUrl": "https://www.cftc.gov/LawRegulation/FederalRegister/finalrules/2026-05635.html"
      },
      {
        "title": "节点软件分发是钱包基础设施的供应链风险面",
        "summary": "自建或可切换链节点的服务应把发行物签名与校验和验证、版本记录和升级前检查纳入部署验收；这是通用完整性建议，不代表存在特定漏洞。",
        "sourceUrl": "https://ethereum.org/developers/docs/nodes-and-clients/run-a-node/"
      }
    ],
    "aiTip": {
      "title": "用五次固定条件运行检查评测稳定性",
      "summary": "对小型代码任务固定输入、工具版本和超时，连续运行五次并记录通过情况、耗时、工具调用数及失败类型；先辨别结果是否稳定，再调整提示词或模型。",
      "sourceUrl": "https://openai.com/news/research/separating-signal-from-noise-in-coding-evaluations/"
    },
    "web3Design": {
      "title": "EIP-6963 用事件循环处理多钱包发现",
      "summary": "将连接器发现结果建模为短生命周期、可验证的能力清单，按内部 connector ID 去重；签名前绑定已选连接器、账户和链 ID，在重连或发现变化后重新确认。",
      "sourceUrl": "https://eips.ethereum.org/EIPS/eip-6963"
    },
    "vibeProject": {
      "title": "Trust Wallet Core · 可嵌入的多链钱包底层库",
      "summary": "该开源跨平台库可帮助团队避免逐链重复实现地址、序列化与签名细节；可从单链的 ParseUnsignedTx、BuildSigningPayload、Sign、Verify/Encode 窄接口和固定测试向量起步。",
      "sourceUrl": "https://github.com/trustwallet/wallet-core"
    },
    "readingPick": {
      "title": "U.S.-UK Transatlantic Taskforce for the Markets of the Future",
      "summary": "阅读美国财政部关于跨境资本市场、代币化活动与数字资产监管协作的公开建议。行动问题：产品在跨境稳定币流程中保存或传递的每类数据，属于协议事实、产品政策还是潜在合规证据？",
      "sourceUrl": "https://home.treasury.gov/news/press-releases/sb0560"
    },
    "sourceUrls": [
      "https://home.treasury.gov/news/press-releases/sb0560",
      "https://www.cftc.gov/LawRegulation/FederalRegister/finalrules/2026-05635.html",
      "https://ethereum.org/developers/docs/nodes-and-clients/run-a-node/",
      "https://coinmarketcap.com/zh/",
      "https://openai.com/news/research/separating-signal-from-noise-in-coding-evaluations/",
      "https://eips.ethereum.org/EIPS/eip-6963",
      "https://github.com/trustwallet/wallet-core"
    ],
    "relatedProjectSlugs": [
      "wallet-core",
      "exchange-wallet-system",
      "web3-wallet-engineer-lab"
    ]
  },
  {
    "date": "2026-07-15",
    "slug": "2026-07-15",
    "title": "每日研究雷达 · 2026-07-15",
    "summary": "关注美英稳定币监管协作、AI 判别性实验、Bitcoin PSBT 签名边界，以及给 AI 生成 SQL 增加确定性检查。",
    "reviewStatus": "automated",
    "generatedAt": "2026-07-15T10:30:00+08:00",
    "sourceSections": [
      "crypto",
      "radar",
      "vibe",
      "reading"
    ],
    "missingSections": [],
    "marketSignals": [
      {
        "title": "实时币价统一使用可读行情入口",
        "summary": "BTC 与 ETH 的实时价格继续通过 CoinMarketCap 中文站查看；日报不使用单个交易所的原始 JSON 作为读者入口，也不依据单一时点价格判断方向。",
        "sourceUrl": "https://coinmarketcap.com/zh/"
      },
      {
        "title": "美英发布数字资产市场合作建议",
        "summary": "美国财政部与英国财政部公布跨大西洋市场工作组建议，涉及跨境资本市场、代币化活动与数字资产监管协作。",
        "sourceUrl": "https://home.treasury.gov/news/press-releases/sb0560"
      },
      {
        "title": "美英继续推进稳定币监管协调",
        "summary": "联合声明支持合规稳定币服务的风险分级市场准入和跨境监管协作；这是政策方向，不代表具体产品已经获批。",
        "sourceUrl": "https://www.gov.uk/government/publications/recommendations-of-the-transatlantic-taskforce-for-markets-of-the-future/uk-us-joint-statement-on-stablecoins"
      }
    ],
    "aiTip": {
      "title": "假设账本与判别性实验",
      "summary": "调试时先列出互斥假设，再只运行一个信息增益最高、可逆且能排除候选的最小实验；把预期、实际结果和被排除的假设继续沉淀为回归测试。"
    },
    "web3Design": {
      "title": "Bitcoin PSBT 把签名上下文变成可校验的数据契约",
      "summary": "PSBT 将构建、UTXO 证据、离线签名、组合和广播分开；wallet-sign 可以复核 prevout、输出、找零、费用与 sighash，而不需要联网选币或广播。",
      "sourceUrl": "https://bips.dev/174/"
    },
    "vibeProject": {
      "title": "sqlsure · AI 生成 SQL 的确定性语义闸门",
      "summary": "sqlsure 在执行前检查 join 扇出、不可加指标、错误 join key 与策略违规，让 Agent 形成生成、检查、修复、再检查的闭环。",
      "sourceUrl": "https://github.com/sqlsure/sqlsure"
    },
    "readingPick": {
      "title": "Fragments · July 6",
      "summary": "Martin Fowler 用短札记连接软件设计、specification-driven development 与工程观察；适合练习把即时灵感整理为有来源、有反证条件和下一次验证动作的判断。",
      "sourceUrl": "https://www.martinfowler.com/fragments/"
    },
    "sourceUrls": [
      "https://coinmarketcap.com/zh/",
      "https://home.treasury.gov/news/press-releases/sb0560",
      "https://www.gov.uk/government/publications/recommendations-of-the-transatlantic-taskforce-for-markets-of-the-future/uk-us-joint-statement-on-stablecoins",
      "https://bips.dev/174/",
      "https://bips.dev/370/",
      "https://doxygen.bitcoincore.org/wallet_2rpc_2coins_8cpp_source.html",
      "https://github.com/sqlsure/sqlsure",
      "https://www.martinfowler.com/fragments/"
    ],
    "relatedProjectSlugs": [
      "wallet-core",
      "exchange-wallet-system",
      "web3-wallet-engineer-lab"
    ]
  },
  {
    "date": "2026-07-14",
    "slug": "2026-07-14",
    "title": "每日研究雷达 · 2026-07-14",
    "summary": "修正并交叉核验 BTC/ETH 价格快照，同时关注 CPI 波动、AI 上下文交接、Sui Object Reference 与本地编码记忆。",
    "reviewStatus": "automated",
    "generatedAt": "2026-07-14T16:24:48+08:00",
    "sourceSections": [
      "crypto",
      "radar",
      "vibe",
      "reading"
    ],
    "missingSections": [],
    "marketSignals": [
      {
        "title": "BTC 交易所 K 线快照为 62,153.89 美元",
        "summary": "Coinbase 现货分钟收盘显示，北京时间 05:00 BTC 报 62,153.89 美元，24 小时约跌 3.14%，区间为 61,750.90–64,388.01 美元。",
        "sourceUrl": "https://coinmarketcap.com/zh/"
      },
      {
        "title": "ETH 价格已更正为约 1,765 美元",
        "summary": "原快照曾将 ETH 误读为 1,624.95 美元；Coinbase 同时点收盘为 1,765.21 美元，Kraken 为 1,765.50 美元，两家交易所均确认 ETH 未跌破 1,700 美元。",
        "sourceUrl": "https://coinmarketcap.com/zh/"
      },
      {
        "title": "CPI 是确定的波动事件，不是方向信号",
        "summary": "美国劳工统计局计划在北京时间 20:30 发布 6 月 CPI；日历事件提高波动先验，但方向仍需等待实际值与成交、资金费率等后续证据确认。",
        "sourceUrl": "https://www.bls.gov/schedule/news_release/cpi.htm"
      }
    ],
    "aiTip": {
      "title": "Context Handoff 上下文交接包",
      "summary": "长任务切换前只保留目标、已确认事实、当前状态、未决问题、下一步和证据位置；链上资源还要标注获取时间与是否可能过期，避免新会话把旧快照当成当前事实。"
    },
    "web3Design": {
      "title": "Sui Object Reference 把可花费状态变成认证引用",
      "summary": "objectId、version 与 digest 共同描述被签名交易使用的对象版本；旧引用在对象被消费后明确失效，使钱包可以围绕资源预留、冲突、重建和 canonical effects 组织恢复状态。",
      "sourceUrl": "https://docs.sui.io/doc/sui.pdf"
    },
    "vibeProject": {
      "title": "Recall · 本地优先的编码会话交接记忆",
      "summary": "Recall 将编码会话整理为可审计的本地活动日志和交接摘要，重点不是重放完整聊天，而是保留目标、变更、验证与未决事项，同时控制脱敏和加载边界。",
      "sourceUrl": "https://github.com/raiyanyahya/recall"
    },
    "readingPick": {
      "title": "Finally, finance's digital transformation",
      "summary": "文章把区块链理解为多方缺乏共同信任时的中立协调层；评估钱包或链上产品时，应先识别谁在对账、谁能改单、谁承担交易对手风险，再判断链上共享状态是否真的必要。",
      "sourceUrl": "https://a16zcrypto.com/posts/article/finance-digital-transformation-finally/"
    },
    "sourceUrls": [
      "https://coinmarketcap.com/zh/",
      "https://api.exchange.coinbase.com/products/BTC-USD/candles?granularity=300&start=2026-07-12T21:00:00Z&end=2026-07-13T21:00:00Z",
      "https://api.exchange.coinbase.com/products/ETH-USD/candles?granularity=300&start=2026-07-12T21:00:00Z&end=2026-07-13T21:00:00Z",
      "https://api.kraken.com/0/public/OHLC?pair=ETHUSD&interval=1&since=1783976340",
      "https://www.bls.gov/schedule/news_release/cpi.htm",
      "https://docs.sui.io/doc/sui.pdf",
      "https://github.com/raiyanyahya/recall",
      "https://a16zcrypto.com/posts/article/finance-digital-transformation-finally/"
    ],
    "relatedProjectSlugs": [
      "wallet-core",
      "exchange-wallet-system"
    ]
  },
  {
    "date": "2026-07-13",
    "slug": "2026-07-13",
    "title": "每日研究雷达 · 2026-07-13",
    "summary": "关注地缘风险下的加密市场、反例驱动的 AI 验收、ERC-4337 多通道 nonce，以及可审计的 Agent PR 证据包。",
    "reviewStatus": "automated",
    "generatedAt": "2026-07-13T09:15:00+08:00",
    "sourceSections": [
      "crypto",
      "radar",
      "vibe",
      "reading"
    ],
    "missingSections": [],
    "marketSignals": [
      {
        "title": "地缘风险尚未触发加密市场剧烈重定价",
        "summary": "BTC 在报道时点维持窄幅波动；周末传统市场休市意味着价格发现仍不完整，需要等待跨资产重新定价。",
        "sourceUrl": "https://www.coindesk.com/markets/2026/07/12/bitcoin-ether-little-changed-as-u-s-launches-fresh-iran-strikes"
      },
      {
        "title": "行业消息需要按证据等级处理",
        "summary": "监管、融资和安全事件若缺少原始公告，只能标记待核验，不能从新闻标题直接推导结论。",
        "sourceUrl": "https://decrypt.co/news-explorer?pinned=1484186&title=stablecoin-giant-circle-secures-final-federal-bank-charter-nod"
      }
    ],
    "aiTip": {
      "title": "反例驱动验收",
      "summary": "先让 AI 写出可判定标准、失败反例和证据要求，再执行和自评任务，减少“看似完整但遗漏关键边界”的输出。"
    },
    "web3Design": {
      "title": "ERC-4337 的 key + sequence nonce",
      "summary": "将全局队列拆成多条有序通道，在保留抗重放边界的同时支持不同权限与操作并行；钱包系统仍需显式保存资源状态。",
      "sourceUrl": "https://eips.ethereum.org/EIPS/eip-4337"
    },
    "vibeProject": {
      "title": "Agent PR 证据包",
      "summary": "把编码 Agent 的提示摘要、关键工具调用、测试结果、最终 diff 与人工确认点整理为可审计的 PR 上下文。",
      "sourceUrl": "https://github.com/es617/claude-replay"
    },
    "readingPick": {
      "title": "Not Every Workflow Is An Agent",
      "summary": "用目标、状态、证据、恢复路径和停止条件区分确定性工作流与真正需要判断循环的 Agent 系统。",
      "sourceUrl": "https://www.tonywood.org/writing/not-every-workflow-is-an-agent/"
    },
    "sourceUrls": [
      "https://www.coindesk.com/markets/2026/07/12/bitcoin-ether-little-changed-as-u-s-launches-fresh-iran-strikes",
      "https://decrypt.co/news-explorer?pinned=1484186&title=stablecoin-giant-circle-secures-final-federal-bank-charter-nod",
      "https://eips.ethereum.org/EIPS/eip-4337",
      "https://github.com/es617/claude-replay",
      "https://www.tonywood.org/writing/not-every-workflow-is-an-agent/"
    ],
    "relatedProjectSlugs": [
      "exchange-wallet-system"
    ]
  }
]
