/* eslint-disable */
// Generated by scripts/generate-radars.mjs. Do not edit by hand.

import type { DailyRadar } from './generatedRadars.ts'

const radarMonthLoaders: Record<string, () => Promise<{ monthlyRadars: DailyRadar[] }>> = {
  '2026-08': () => import('./generatedRadarMonths/2026-08.ts'),
  '2026-07': () => import('./generatedRadarMonths/2026-07.ts'),
}

export async function loadRadarBySlug(slug: string): Promise<DailyRadar | undefined> {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(slug)) return undefined
  const loadMonth = radarMonthLoaders[slug.slice(0, 7)]
  if (!loadMonth) return undefined
  const { monthlyRadars } = await loadMonth()
  return monthlyRadars.find(radar => radar.slug === slug)
}
