/* eslint-disable */
// Generated by scripts/generate-market-radars.mjs.
export type MarketRadarPriority = 'P0' | 'P1' | 'P2'
export type MarketRadarStatus = 'scheduled' | 'released' | 'monitoring'
export type MarketRadarCategory = 'macro' | 'crypto' | 'equity' | 'regulation'
export interface MarketRadarEvent { id: string; priority: MarketRadarPriority; status: MarketRadarStatus; category: MarketRadarCategory; eventAt?: string; title: string; fact: string; whyWatch: string; assets: string[]; watchFor: string; invalidation: string; sourceName: string; sourceUrl: string; sourcePublishedAt: string }
export type MarketQuantAssetGroup = 'us_equity_etf' | 'crypto' | 'gold_etf'
export interface MarketQuantAsset { symbol: 'SPY' | 'QQQ' | 'BTC' | 'ETH' | 'GLD'; group: MarketQuantAssetGroup; up: number; sideways: number; down: number }
export interface MarketQuantStrategy { horizonTradingDays: number; status: 'heuristic_unbacktested'; methodology: string; assets: MarketQuantAsset[]; rationale: string; nextValidation: string; invalidation: string; sourceUrls: string[] }
export interface MarketRadarDaily { date: string; slug: string; title: string; summary: string; reviewStatus: 'automated'; generatedAt: string; events: MarketRadarEvent[]; sourceUrls: string[]; quantStrategy?: MarketQuantStrategy }
export interface MarketRadarIndexEntry { date: string; slug: string; title: string; summary: string; eventCount: number; assetCount: number; leadTitle: string }
export const marketRadarIndex: MarketRadarIndexEntry[] = [
  {
    "date": "2026-08-10",
    "slug": "2026-08-10",
    "title": "交易研究雷达 · 2026-08-10",
    "summary": "本周先盯紧美国中长期国债连续拍卖与联储偏鹰分歧，再把 Agave 4.2.0 视为 Solana 客户端运行事件；只记录可验证条件，不预设资产方向。",
    "eventCount": 3,
    "assetCount": 6,
    "leadTitle": "美国 3 年、10 年与 30 年国债将在 8 月 11–13 日连续拍卖"
  },
  {
    "date": "2026-08-09",
    "slug": "2026-08-09",
    "title": "交易研究雷达 · 2026-08-09",
    "summary": "先锁定本周通胀双节点，再观察 Aptos 热修复透明度与 lnd 候选版迁移风险；只记录可验证事件，不输出仓位指令。",
    "eventCount": 3,
    "assetCount": 5,
    "leadTitle": "美国 CPI 与 PPI 将在 8 月 12–13 日连续发布"
  }
]
export const latestMarketRadars: MarketRadarDaily[] = [
  {
    "date": "2026-08-10",
    "slug": "2026-08-10",
    "title": "交易研究雷达 · 2026-08-10",
    "summary": "本周先盯紧美国中长期国债连续拍卖与联储偏鹰分歧，再把 Agave 4.2.0 视为 Solana 客户端运行事件；只记录可验证条件，不预设资产方向。",
    "reviewStatus": "automated",
    "generatedAt": "2026-08-10T15:01:26+08:00",
    "events": [
      {
        "id": "us-treasury-august-refunding-auctions-2026",
        "priority": "P0",
        "status": "scheduled",
        "category": "macro",
        "title": "美国 3 年、10 年与 30 年国债将在 8 月 11–13 日连续拍卖",
        "fact": "美国财政部暂定拍卖日程列出：3 年期国债在 8 月 11 日拍卖，10 年期在 8 月 12 日拍卖，30 年期在 8 月 13 日拍卖，三者均计划于 8 月 17 日结算。",
        "whyWatch": "连续的中长期期限供给会给出公开的需求与期限溢价观察窗口，可能影响美债收益率、美元与风险资产定价；日程本身不代表需求强弱或市场方向。",
        "assets": [
          "SPY",
          "QQQ",
          "DXY",
          "BTC",
          "ETH"
        ],
        "watchFor": "逐场核对财政部正式结果中的最高收益率、投标倍数与间接投标占比，再观察公开市场收益率和相关资产在结果公布后的变化。",
        "invalidation": "若财政部更新拍卖或结算安排，以最新正式公告为准；在结果出现前，不把发行日程单独写成收益率或资产方向结论。",
        "sourceName": "U.S. Department of the Treasury",
        "sourceUrl": "https://home.treasury.gov/system/files/221/TentativeAuctionScheduleQ22026.pdf",
        "sourcePublishedAt": "2026-05-06"
      },
      {
        "id": "fomc-july-2026-hold-three-hike-dissents",
        "priority": "P1",
        "status": "monitoring",
        "category": "macro",
        "title": "联储维持 3.50%–3.75% 利率区间，三票异议倾向加息",
        "fact": "7 月 29 日 FOMC 以 9 比 3 通过维持联邦基金利率目标区间在 3.50%–3.75%；三名反对者偏好上调 25 个基点，声明同时称通胀仍高于 2% 目标。",
        "whyWatch": "利率不变与三票偏鹰异议同时存在，使后续官方经济数据和联储沟通更容易改变市场对政策路径的定价；本次表决不能直接外推下一次会议行动。",
        "assets": [
          "SPY",
          "QQQ",
          "DXY",
          "BTC",
          "ETH"
        ],
        "watchFor": "继续核对后续官方经济数据、FOMC 纪要与联储公开表态，观察偏鹰分歧是否扩大、收敛或被新的事实替代。",
        "invalidation": "任何更新的 FOMC 决议或明确修正政策判断的官方材料都会取代本项；单一市场波动不证明政策路径已经改变。",
        "sourceName": "Federal Reserve Board",
        "sourceUrl": "https://www.federalreserve.gov/newsevents/pressreleases/monetary20260729a.htm",
        "sourcePublishedAt": "2026-07-29"
      },
      {
        "id": "agave-4-2-0-stable-release",
        "priority": "P2",
        "status": "released",
        "category": "crypto",
        "title": "Agave 4.2.0 发布稳定版，覆盖主网 Beta 运行边界",
        "fact": "Anza 将 Agave 4.2.0 标为适用于 Testnet、Devnet 与 Mainnet Beta 的稳定版；变更包括不再重写非活跃质押、账户哈希线程栈设置、Token-2022 指令解析与增量快照间隔调整。",
        "whyWatch": "这是 Solana 验证节点客户端的运行与升级事件，值得关注节点采用、资源表现和后续修复；稳定版标签本身不等于网络已经全量升级，也不构成 SOL 方向信号。",
        "assets": [
          "SOL"
        ],
        "watchFor": "观察 Anza 的后续发布、验证节点采用信息、官方状态页以及是否出现快照、重放、质押或 Token-2022 解析相关的公开问题。",
        "invalidation": "若后续补丁撤回或替代相关变更，或官方限制适用环境，应以新版本说明重写判断；没有运行证据时不外推性能或市场影响。",
        "sourceName": "Anza Agave Releases",
        "sourceUrl": "https://github.com/anza-xyz/agave/releases/tag/v4.2.0",
        "sourcePublishedAt": "2026-08-07"
      }
    ],
    "sourceUrls": [
      "https://home.treasury.gov/system/files/221/TentativeAuctionScheduleQ22026.pdf",
      "https://www.federalreserve.gov/newsevents/pressreleases/monetary20260729a.htm",
      "https://github.com/anza-xyz/agave/releases/tag/v4.2.0"
    ],
    "quantStrategy": {
      "horizonTradingDays": 3,
      "status": "heuristic_unbacktested",
      "methodology": "基于已确认公开事件与当前价格动量的透明启发式；尚未进行历史回测或概率校准，因此这些数字是情景权重，不是统计胜率。",
      "assets": [
        {
          "symbol": "SPY",
          "group": "us_equity_etf",
          "up": 34,
          "sideways": 41,
          "down": 25
        },
        {
          "symbol": "QQQ",
          "group": "us_equity_etf",
          "up": 36,
          "sideways": 36,
          "down": 28
        },
        {
          "symbol": "BTC",
          "group": "crypto",
          "up": 27,
          "sideways": 40,
          "down": 33
        },
        {
          "symbol": "ETH",
          "group": "crypto",
          "up": 25,
          "sideways": 40,
          "down": 35
        },
        {
          "symbol": "GLD",
          "group": "gold_etf",
          "up": 42,
          "sideways": 36,
          "down": 22
        }
      ],
      "rationale": "SPY、QQQ 与 GLD 当前动量偏强，BTC 当日略弱。联储维持利率但出现三票加息异议，对高久期与高波动资产构成约束；8 月 11–13 日美国中长期国债连续拍卖在结果公布前主要提高不确定性，不直接给出方向。",
      "nextValidation": "逐场核对最高收益率、投标倍数、间接投标占比，再观察美债收益率、美元与相关资产反应。",
      "invalidation": "财政部更新日程、出现新的联储官方材料，或 3 个交易日窗口结束后，必须重新计算。",
      "sourceUrls": [
        "https://www.federalreserve.gov/newsevents/pressreleases/monetary20260729a.htm",
        "https://home.treasury.gov/system/files/221/TentativeAuctionScheduleQ22026.pdf"
      ]
    }
  },
  {
    "date": "2026-08-09",
    "slug": "2026-08-09",
    "title": "交易研究雷达 · 2026-08-09",
    "summary": "先锁定本周通胀双节点，再观察 Aptos 热修复透明度与 lnd 候选版迁移风险；只记录可验证事件，不输出仓位指令。",
    "reviewStatus": "automated",
    "generatedAt": "2026-08-09T12:30:00+08:00",
    "events": [
      {
        "id": "us-inflation-releases-2026-08",
        "priority": "P0",
        "status": "scheduled",
        "category": "macro",
        "eventAt": "2026-08-12T20:30:00+08:00",
        "title": "美国 CPI 与 PPI 将在 8 月 12–13 日连续发布",
        "fact": "美国劳工统计局日程显示，7 月 CPI 与实际收入定于 8 月 12 日 08:30 ET 发布，7 月 PPI 定于 8 月 13 日 08:30 ET 发布。",
        "whyWatch": "连续两天的通胀数据可能改变市场对利率路径的判断，并影响美元、权益与加密资产的风险偏好；日程本身不预设数据方向。",
        "assets": [
          "BTC",
          "ETH",
          "SPY",
          "DXY"
        ],
        "watchFor": "发布后只记录官方标题与核心分项方向，并人工核对 BTC、ETH、SPY 与美元指数在 30 分钟和 4 小时窗口的公开行情表现。",
        "invalidation": "若官方调整发布时间，以 BLS 最新日程为准；在数据发布前不把市场传闻或预测值当成事实。",
        "sourceName": "U.S. Bureau of Labor Statistics",
        "sourceUrl": "https://www.bls.gov/schedule/2026/08_sched_list.htm",
        "sourcePublishedAt": "2026-06-10"
      },
      {
        "id": "aptos-node-1-48-6-private-hotfix",
        "priority": "P1",
        "status": "monitoring",
        "category": "crypto",
        "title": "Aptos 1.48.6 热修复要求验证节点升级，但源码未公开",
        "fact": "Aptos 官方发布页将 1.48.6 标为主网热修复，要求验证节点升级、建议全节点升级，同时明确说明这是私有热修复，源码不可用。",
        "whyWatch": "强制性验证节点升级与不可审查源码同时出现，首先是网络运行和供应链透明度事件；它不自动构成 APT 的方向信号。",
        "assets": [
          "APT"
        ],
        "watchFor": "继续观察官方网络状态、验证节点升级反馈、后续公开说明以及是否出现可审查的修复细节。",
        "invalidation": "在没有公开故障说明、网络指标或复盘前，不推断漏洞范围，也不把版本发布等同于链上异常。",
        "sourceName": "Aptos Core Releases",
        "sourceUrl": "https://github.com/aptos-labs/aptos-core/releases/tag/aptos-node-v1.48.6-hotfix",
        "sourcePublishedAt": "2026-08-05"
      },
      {
        "id": "lnd-0-21-2-beta-rc1",
        "priority": "P2",
        "status": "released",
        "category": "crypto",
        "title": "lnd 0.21.2-beta.rc1 修复历史迁移路径，仍只是候选版",
        "fact": "lnd 官方候选版说明修复 KV 到 SQL 的历史支付迁移，以及缺少版本键时被跳过的 waiting-proof 迁移；发布物提供签名和可复现构建验证路径。",
        "whyWatch": "迁移修复关系到 Lightning 节点升级可用性，但候选版的工程进展不能直接外推为 BTC 市场催化。",
        "assets": [
          "BTC"
        ],
        "watchFor": "观察稳定版是否继承修复、节点运营者是否报告启动或迁移问题，以及发布说明是否补充回归边界。",
        "invalidation": "在稳定版发布和真实运营反馈出现前，只把它作为 Lightning 基础设施观察项，不写成价格方向判断。",
        "sourceName": "lnd Releases",
        "sourceUrl": "https://github.com/lightningnetwork/lnd/releases/tag/v0.21.2-beta.rc1",
        "sourcePublishedAt": "2026-08-08"
      }
    ],
    "sourceUrls": [
      "https://www.bls.gov/schedule/2026/08_sched_list.htm",
      "https://github.com/aptos-labs/aptos-core/releases/tag/aptos-node-v1.48.6-hotfix",
      "https://github.com/lightningnetwork/lnd/releases/tag/v0.21.2-beta.rc1"
    ]
  }
]
