/* eslint-disable */
// Generated by scripts/generate-projects.mjs. Do not edit by hand.

export type ProjectStage = 'exploring' | 'building' | 'verified-local' | 'showcase-ready'
export type ProjectSourceType = 'original' | 'adapted' | 'source-study'
export type ProjectVisibility = 'private' | 'public' | 'none'

export interface Project {
  id: number
  legacyIds: number[]
  slug: string
  name: string
  category: string
  featured: boolean
  stage: ProjectStage
  sourceType: ProjectSourceType
  visibility: ProjectVisibility
  repositoryUrl?: string
  positioning: string
  currentFocus: string
  verifiedEvidence: string[]
  targetOutcome: string
  nextMilestone: string
  knownLimits: string[]
  updatedAt: string
  coreAbilities: string[]
  talkingPoints: string[]
  techStack: string[]
  engineering: { role: string; systemBoundary: string; callFlow: string[]; failureScenarios: string[]; evidence: string[]; knownLimits: string[]; overviewSummary: string }
  learning: { goal: string; verified: string[]; verification: string[]; verificationNote?: string; tradeoffs: string[]; nextSteps: string[] }
  conceptTags: string[]
  relatedArticleSlugs: string[]
  suggestedQuestions: string[]
}

export const projects: Project[] = [
  {
    "id": 1,
    "legacyIds": [
      2
    ],
    "slug": "exchange-wallet-system",
    "name": "Exchange Wallet Infrastructure",
    "category": "钱包基础设施",
    "featured": true,
    "stage": "building",
    "sourceType": "adapted",
    "visibility": "private",
    "positioning": "围绕交易所充值、提现与资金安全组织的 Go 钱包基础设施：wallet-service 编排资金状态，risk-service 承担交易校验与风控放行，wallet-api 隔离多链节点能力，wallet-sign 收敛密钥与签名能力。",
    "currentFocus": "把资金编排、风险控制、链交互和签名四个服务的调用链、状态机与失败恢复整理成可以运行、可以讲解、可以复核的统一工程案例。",
    "verifiedEvidence": [
      "已定位充值扫链、提现构建、签名、广播与通知的核心代码入口",
      "已验证 ChainDispatcher 与多链 adaptor 的路由边界",
      "已记录 request_id 幂等、确认数推进和广播结果未知等异常场景",
      "已验证 risk-service 的提现提交、离线交易一致性校验、审批哈希与幂等标记单测",
      "已在独立 TSS 项目完成三节点 Keygen / Sign 本地验证，wallet-sign 接入仍在进行"
    ],
    "targetOutcome": "形成一套本地可复现的充值与提现演示：能够启动四个服务、跑通风控校验到签名广播的核心流程、展示状态变化，并用测试复现风控拒绝、广播超时和链上成功但本地更新失败的恢复策略。",
    "nextMilestone": "固定四个服务的兼容基线，统一验证命令，并跑通一条包含 risk-service 放行与失败注入的提现端到端流程。",
    "knownLimits": [
      "当前仍是学习与工程验证项目，不代表生产环境部署经历",
      "risk-service 当前仍以本地规则和模拟 AML 能力为主，不代表完整生产风控系统",
      "部分 context 传播、余额事务和链级资源并发仍需继续补强",
      "wallet-sign 当前以 Local Signer 为已验证基线；MPC/TSS 尚未完成端到端接入，HSM 属于下一阶段",
      "仓库暂按私有项目展示，不提供公开源码链接"
    ],
    "updatedAt": "2026-07-13",
    "coreAbilities": [
      "充值提现异步状态机",
      "多链 RPC 与 Chain Adaptor",
      "独立签名服务与私钥边界",
      "提现风控、审批凭证与离线交易一致性校验",
      "幂等、重试、确认数与失败补偿",
      "Go、gRPC、PostgreSQL 与 Redis"
    ],
    "talkingPoints": [
      "为什么资金编排、链节点、签名和风控要分属不同信任边界",
      "广播超时为什么不能直接重发第二笔交易",
      "链上成功但本地失败时如何以链上事实幂等恢复",
      "哪些生产化能力仍然没有完成"
    ],
    "techStack": [
      "Go",
      "gRPC",
      "PostgreSQL",
      "Redis",
      "LevelDB",
      "GORM",
      "Chain Adaptor",
      "EVM",
      "Bitcoin",
      "Solana",
      "Sui"
    ],
    "engineering": {
      "role": "钱包基础设施代码理解、增量实现、运行验证与异常路径梳理",
      "systemBoundary": "wallet-service 维护业务资金状态，risk-service 校验提现内容并产生风控放行结果，wallet-api 负责链节点查询与交易构建/广播，wallet-sign 负责地址生成和签名；Local Signer、MPC/TSS 与未来 HSM 都位于 wallet-sign 后方，不增加新的业务服务边界。",
      "callFlow": [
        "业务请求进入 wallet-service 并持久化 request_id 与状态",
        "risk-service 校验提现内容、幂等状态与风险放行条件",
        "wallet-api 获取链资源并构建待签名交易",
        "wallet-sign 在独立边界内完成签名",
        "wallet-api 拼装并广播 raw transaction",
        "wallet-service 根据链上确认推进账务与通知"
      ],
      "failureScenarios": [
        "广播请求超时但节点可能已经接受交易",
        "链上成功后本地状态、账本或通知更新失败",
        "服务重启后需要从持久化状态继续推进而不是重复出金"
      ],
      "evidence": [
        "四个服务的 README、状态机文档和代码入口索引",
        "dispatcher、adaptor、RPC service 与业务模块测试",
        "risk-service 的 services、bigint 与 LevelDB 相关验证命令",
        "多链 E2E 文档、migrations 与失败恢复设计记录"
      ],
      "knownLimits": [
        "尚未形成一条覆盖四服务的稳定一键端到端演示",
        "MPC/TSS 已完成独立三节点验证但未接入 wallet-sign；HSM、严格账务模型与完整可观测性仍属于目标态"
      ],
      "overviewSummary": "这是我的 Web3 钱包后端主线：用 Exchange Wallet Infrastructure 拆开资金状态、多链节点、私钥签名和风险控制，并围绕幂等、确认数、风控放行、结果未知和补偿恢复理解资金系统。"
    },
    "learning": {
      "goal": "能够不依赖背稿讲清四个服务的职责、充值提现状态机和关键异常恢复案例，并能回到代码和测试证明判断。",
      "verified": [
        "API 与 Sign 两套 adaptor 的职责差异",
        "risk-service 的提现提交、离线一致性校验、审批哈希与幂等标记",
        "充值与提现 worker、数据库状态和通知路径",
        "广播超时与链上/本地状态不一致的处理原则"
      ],
      "verification": [
        "go test ./chaindispatcher ./chain/ethereum ./chain/bitcoin",
        "go test ./services/grpc",
        "go test ./services/rpc",
        "go test ./services ./common/bigint ./leveldb"
      ],
      "verificationNote": "命令来自对应私有仓库的当前验证记录；全链路稳定基线仍在整理。",
      "tradeoffs": [
        "当前代码事实、设计理解和生产化建议分开表达",
        "不使用线上规模、真实资金量或生产事故包装项目",
        "优先完成可复现失败路径，而不是继续堆叠支持链数量"
      ],
      "nextSteps": [
        "固定四个服务的兼容版本和启动顺序",
        "补齐风控拒绝、提现失败注入与重启恢复测试",
        "整理简版与完整两档工程说明"
      ]
    },
    "conceptTags": [
      "wallet-backend",
      "api-design",
      "multi-chain",
      "signer-service",
      "risk-control",
      "go-infra"
    ],
    "relatedArticleSlugs": [
      "cex-evm-wallet-deposit-withdrawal-loop",
      "withdrawal-error-handling",
      "wallet-api-boundary",
      "wallet-sign-signer",
      "new-chain-integration-checklist"
    ],
    "suggestedQuestions": [
      "Exchange Wallet Infrastructure 为什么要拆成四个服务边界？",
      "提现广播超时后应该如何恢复？",
      "当前哪些是已实现事实，哪些仍是生产化方向？"
    ]
  },
  {
    "id": 3,
    "legacyIds": [],
    "slug": "s78-market-services",
    "name": "S78 Market Services",
    "category": "数据服务扩展",
    "featured": false,
    "stage": "building",
    "sourceType": "adapted",
    "visibility": "private",
    "positioning": "交易所行情数据服务学习项目：串联外部数据源、Crawler、Worker、Redis/PostgreSQL、HTTP/gRPC API 与 Vue Dashboard。",
    "currentFocus": "把数据新鲜度、真实错误状态和本地运行链路整理为可复现证据，而不是用 mock 行情掩盖数据源故障。",
    "verifiedEvidence": [
      "已拆分 Crawler、Worker、存储和查询职责",
      "Dashboard 展示更新时间与数据延迟",
      "API 失败时明确显示 Error，不使用 mock 数据兜底"
    ],
    "targetOutcome": "形成一条可重复的本地行情链路：采集真实数据、写入 Redis/PostgreSQL、通过 API 查询并在前端展示更新时间、延迟和错误状态。",
    "nextMilestone": "固定本地依赖和 seed 流程，运行后端测试、前端构建与一条端到端行情查询。",
    "knownLimits": [
      "多数据源容灾、K 线缺口补偿和价格异常检测仍未完成",
      "当前不包含撮合或钱包资金状态",
      "仓库暂按私有项目展示"
    ],
    "updatedAt": "2026-07-13",
    "coreAbilities": [
      "行情采集与 Worker",
      "Redis/PostgreSQL",
      "HTTP/gRPC",
      "Vue Dashboard",
      "数据新鲜度与错误状态"
    ],
    "talkingPoints": [
      "为什么采集和查询要分层",
      "行情可用与行情新鲜有什么区别",
      "为什么不能使用 mock 兜底真实故障"
    ],
    "techStack": [
      "Go",
      "HTTP",
      "gRPC",
      "Redis",
      "PostgreSQL",
      "GORM",
      "Vue",
      "Vite"
    ],
    "engineering": {
      "role": "行情采集、处理、存储和展示链路的运行梳理与可信数据表达",
      "systemBoundary": "负责交易所后台行情数据流，不承担撮合、订单或钱包资金状态。",
      "callFlow": [
        "Crawler 拉取外部行情",
        "Worker 处理热点价格",
        "Redis/PostgreSQL 持久化",
        "HTTP/gRPC 查询",
        "Dashboard 展示新鲜度"
      ],
      "failureScenarios": [
        "外部 API 失败时不能伪造行情",
        "数据存在但过期时必须明确标记 stale"
      ],
      "evidence": [
        "Crawler/Worker 分层",
        "last_updated 与 data_delay_seconds",
        "Dashboard Error 状态"
      ],
      "knownLimits": [
        "一键本地验收仍需固定",
        "完整数据质量与容灾策略未完成"
      ],
      "overviewSummary": "S78 是钱包主线之外的数据服务补充，串联外部数据源、异步处理、缓存、数据库、API 和前端之间的完整链路。"
    },
    "learning": {
      "goal": "理解交易所数据服务的采集、处理、存储和查询边界，并用时间和错误状态表达数据可信度。",
      "verified": [
        "服务分层",
        "数据更新时间与延迟",
        "前端真实错误态"
      ],
      "verification": [
        "go test ./...",
        "go build ./cmd/market-services",
        "make verify-local",
        "npm run build"
      ],
      "verificationNote": "命令已经整理，完整稳定基线将在下一里程碑重新执行。",
      "tradeoffs": [
        "不使用假数据兜底",
        "延迟与错误作为 API 语义的一部分",
        "未完成能力继续保持目标态标签"
      ],
      "nextSteps": [
        "跑通本地依赖和行情查询",
        "补齐 K 线缺口验证",
        "设计多数据源容灾和告警"
      ]
    },
    "conceptTags": [
      "go-infra",
      "api-design"
    ],
    "relatedArticleSlugs": [
      "market-services-data-flow",
      "http-rpc-grpc",
      "api-system-calls"
    ],
    "suggestedQuestions": [
      "行情服务如何表达数据新鲜度？",
      "为什么失败时不应该展示 mock 行情？"
    ]
  },
  {
    "id": 9,
    "legacyIds": [],
    "slug": "stableflow",
    "name": "StableFlow",
    "category": "当前开发副线",
    "featured": false,
    "stage": "verified-local",
    "sourceType": "original",
    "visibility": "private",
    "positioning": "面向 B2B 稳定币发票结算的非托管工程沙盒，围绕 invoice 状态机、合规审批、EIP-712 授权、签名边界、链上支付与 outbox 交付组织完整链路。",
    "currentFocus": "在不改变钱包后端核心定位的前提下，验证稳定币业务如何复用资金状态、幂等、风控授权、独立签名和链上索引能力。",
    "verifiedEvidence": [
      "12 个 workspace 包的 TypeScript 类型检查通过",
      "Vitest、Foundry 测试通过，包含授权防重放、金额篡改、错误链和合约不托管资金不变量",
      "API、worker、indexer、signer、contracts 与 Next.js web 完整构建通过"
    ],
    "targetOutcome": "形成一条可重复的本地 B2B 稳定币结算演示：创建 invoice、风险审核、签发 EIP-712 授权、付款、索引确认、退款和 outbox 交付均有可观察状态。",
    "nextMilestone": "跑通无缓存的一键本地 demo 与浏览器 E2E，并记录失败注入、数据新鲜度和链上/本地状态恢复证据。",
    "knownLimits": [
      "当前验证以本地测试与构建为主，一键 demo 和浏览器 E2E 尚未计入已完成证据",
      "Base Sepolia 部署和合约验证不作为当前已完成能力",
      "仓库暂时私有，不提供公开源码按钮"
    ],
    "updatedAt": "2026-07-13",
    "coreAbilities": [
      "Invoice 状态机",
      "EIP-712 授权",
      "非托管合约结算",
      "风控审核",
      "Signer 服务",
      "Indexer 与 Outbox",
      "TypeScript Monorepo"
    ],
    "talkingPoints": [
      "为什么合约直接 payer 到 merchant 而不托管 USDC",
      "审批授权如何绑定 invoice、金额、链和 deadline",
      "链上事件、内部状态和通知失败如何最终一致"
    ],
    "techStack": [
      "TypeScript",
      "pnpm",
      "Turborepo",
      "Next.js",
      "Node.js",
      "PostgreSQL",
      "gRPC",
      "Solidity",
      "Foundry",
      "EIP-712"
    ],
    "engineering": {
      "role": "稳定币结算沙盒的架构实现、测试验证与状态边界梳理",
      "systemBoundary": "StableFlow 是钱包工程能力的业务应用副线：它不替代 Exchange Wallet Infrastructure，也不声称提供生产支付服务。",
      "callFlow": [
        "创建并审核 invoice",
        "生成与 invoice 内容绑定的 EIP-712 授权",
        "独立 signer 验证授权并签名",
        "payer 通过非托管合约直接向 merchant 支付",
        "indexer 更新链上事实，worker 通过 outbox 交付事件"
      ],
      "failureScenarios": [
        "重复授权、金额篡改、错误 chainId 或错误 signer 必须拒绝",
        "链上已支付但本地 invoice 或下游通知未推进时需要幂等恢复"
      ],
      "evidence": [
        "pnpm typecheck",
        "pnpm test",
        "pnpm build",
        "Foundry invariantContractNeverCustodiesUSDC"
      ],
      "knownLimits": [
        "集成测试中仍有依赖外部服务而跳过的用例",
        "完整本地 demo、E2E 和测试网部署需要单独验收"
      ],
      "overviewSummary": "StableFlow 是当前开发副线，用稳定币发票结算验证状态机、风控授权、签名边界、链上事实和 outbox，而钱包后端仍是我的主工程身份。"
    },
    "learning": {
      "goal": "把钱包基础设施中的资金状态与签名安全判断迁移到非托管稳定币结算场景。",
      "verified": [
        "状态机与金额值对象",
        "EIP-712 防重放和内容绑定",
        "合约不托管资金不变量",
        "服务与前端构建"
      ],
      "verification": [
        "pnpm typecheck",
        "pnpm test",
        "pnpm build"
      ],
      "verificationNote": "2026-07-13 在本地仓库执行通过；部分外部依赖集成测试按项目配置跳过。",
      "tradeoffs": [
        "保持非托管结算，不把网站文案扩大为支付生产经验",
        "将测试、构建与端到端部署分开标注",
        "作为当前副线展示，不稀释 Web3 钱包后端主线"
      ],
      "nextSteps": [
        "无缓存重跑关键测试",
        "跑通 demo:local 与浏览器 E2E",
        "补链上成功本地失败的恢复演示"
      ]
    },
    "conceptTags": [
      "wallet-backend",
      "signer-service",
      "api-design",
      "ai-engineering"
    ],
    "relatedArticleSlugs": [
      "withdrawal-error-handling",
      "wallet-sign-signer",
      "api-system-calls"
    ],
    "suggestedQuestions": [
      "StableFlow 与钱包基础设施共享哪些工程问题？",
      "为什么它被标为当前开发副线？",
      "目前通过了哪些验证，还有什么没完成？"
    ]
  },
  {
    "id": 5,
    "legacyIds": [],
    "slug": "tss-mpc",
    "name": "TSS / MPC 签名研究",
    "category": "安全扩展",
    "featured": false,
    "stage": "verified-local",
    "sourceType": "source-study",
    "visibility": "private",
    "positioning": "基于现有 TSS 项目进行源码学习与安全边界改造，理解 Manager、Node、Keygen、Sign、committee、threshold 和 key share。",
    "currentFocus": "把已本地验证的三节点 Keygen / Sign 收敛为 wallet-sign 可替换后端，并明确会话路由、超时、份额存储和降级边界。",
    "verifiedEvidence": [
      "已完成 Manager/Node 职责与 Keygen/Sign 流程导读",
      "已定位 CPK、committee、threshold 与本地 share 的元数据路径",
      "已在本地运行三节点 Keygen 并产生不含密钥材料的验证记录",
      "已在本地运行三节点 Sign 并验证标准签名结果"
    ],
    "targetOutcome": "在 wallet-sign 保持统一策略与审计边界的前提下，将 TSS 作为可替换签名后端，完成请求路由、签名返回和节点不足门限的失败演示。",
    "nextMilestone": "设计并实现 wallet-sign → TSS Manager 的最小接口，跑通一条不含真实资金的端到端签名请求。",
    "knownLimits": [
      "属于源码学习和改造，不是从零原创协议实现",
      "三节点 Keygen / Sign 已独立验证，但尚未接入 wallet-sign",
      "尚未接入生产钱包或真实资金",
      "完整回归仍受旧版依赖和 Go 工具链限制"
    ],
    "updatedAt": "2026-07-13",
    "coreAbilities": [
      "TSS Keygen/Sign",
      "Manager/Node 边界",
      "threshold 与 committee",
      "key share 安全",
      "钱包签名网关接入"
    ],
    "talkingPoints": [
      "TSS 与链上多签的区别",
      "Manager 为什么不应持有完整 share",
      "TSS 为什么不能替代提现风控",
      "节点不足门限如何影响可用性"
    ],
    "techStack": [
      "Go",
      "tss-lib",
      "ECDSA",
      "Paillier",
      "libp2p",
      "WebSocket",
      "LevelDB"
    ],
    "engineering": {
      "role": "TSS 源码学习、安全边界梳理与局部改造",
      "systemBoundary": "TSS 负责多方 Keygen/Sign 和份额安全，不承担业务审核、限额、幂等和提现状态推进。",
      "callFlow": [
        "Manager 接收请求并选择 committee",
        "Nodes 参与协议轮次",
        "满足 threshold 后产生标准签名",
        "签名返回钱包签名网关"
      ],
      "failureScenarios": [
        "在线节点不足门限导致签名不可用",
        "控制面错误路由或元数据不一致导致会话失败"
      ],
      "evidence": [
        "Manager/Node 代码导读",
        "CPK 和 committee 持久化路径",
        "本地运行手册与兼容性记录"
      ],
      "knownLimits": [
        "三节点证据来自独立 TSS 环境",
        "尚未完成 wallet-sign 接入，也未用于生产资金"
      ],
      "overviewSummary": "这是一个源码学习与安全改造项目，用来理解 TSS 如何降低完整私钥单点风险，以及它在钱包系统里仍然依赖业务风控和高可用设计。"
    },
    "learning": {
      "goal": "能够从代码和运行结果解释门限签名的控制面、协议面、份额边界和可用性风险。",
      "verified": [
        "Manager 调度与响应路由",
        "Node 本地 share 与协议轮次",
        "committee 和 threshold 元数据"
      ],
      "verification": [
        "三节点 Keygen 本地运行记录",
        "三节点 Sign 本地运行记录"
      ],
      "verificationNote": "网站只描述验证结论，不公开 key share、助记词、私钥或敏感运行配置；具体兼容命令保留在私有运行记录中。",
      "tradeoffs": [
        "明确标注源码学习来源",
        "安全理解与生产部署分开",
        "不公开任何密钥份额或敏感配置"
      ],
      "nextSteps": [
        "设计 wallet-sign 到 Manager 的契约",
        "跑通端到端签名请求",
        "增加节点掉线和请求超时场景"
      ]
    },
    "conceptTags": [
      "mpc-tss",
      "signer-service"
    ],
    "relatedArticleSlugs": [
      "mpc-wallet-sign-integration",
      "thorchain-tss-attack-analysis",
      "aws-cloudhsm-wallet-sign-integration"
    ],
    "suggestedQuestions": [
      "TSS 在钱包系统里解决什么问题？",
      "当前项目哪些是理解，哪些已经运行验证？"
    ]
  },
  {
    "id": 7,
    "legacyIds": [],
    "slug": "wallet-core",
    "name": "wallet-core",
    "category": "TypeScript 多链",
    "featured": true,
    "stage": "verified-local",
    "sourceType": "original",
    "visibility": "private",
    "positioning": "TypeScript 多链离线钱包核心：统一密钥派生、交易构建与签名入口，同时保留 nonce、UTXO、blockhash、TAPOS 和 object version 等链级资源差异。",
    "currentFocus": "稳定不同链的输入契约、异常参数校验和可复现测试，让离线边界比支持链数量更可信。",
    "verifiedEvidence": [
      "TypeScript 类型检查与构建可以运行",
      "已覆盖 EVM、BTC、Solana、TRON、Cosmos 与 Sui 的交易模型",
      "已完成 Sui 原生充值交易 dry-run 流程"
    ],
    "targetOutcome": "形成一个有清晰 API、链级输入文档、示例和稳定测试矩阵的 TypeScript 离线钱包库，调用方可以安全地准备链上资源、离线签名并自行广播。",
    "nextMilestone": "修复 Cosmos 依赖解析并恢复全量测试，再补齐链资源过期和异常金额输入用例。",
    "knownLimits": [
      "不查询 RPC、不广播交易，调用方必须提供新鲜链状态",
      "Cosmos 全量测试仍受依赖解析问题影响",
      "仓库暂按私有项目展示"
    ],
    "updatedAt": "2026-07-13",
    "coreAbilities": [
      "TypeScript SDK 集成",
      "多链离线交易构建",
      "账户/UTXO/对象模型",
      "最小单位整数金额",
      "Jest 链级测试"
    ],
    "talkingPoints": [
      "离线核心为什么不读取 RPC",
      "不同链的资源状态为何不能被统一字段抹平",
      "整数金额约束如何降低资产错误",
      "测试如何覆盖链模型差异"
    ],
    "techStack": [
      "TypeScript",
      "ethers",
      "bitcoinjs-lib",
      "@solana/web3.js",
      "@mysten/sui",
      "CosmJS",
      "TronWeb",
      "Jest"
    ],
    "engineering": {
      "role": "TypeScript 多链离线钱包核心的实现与验证",
      "systemBoundary": "只负责密钥派生、交易构建与签名；RPC 查询、资源锁定和广播由调用方承担。",
      "callFlow": [
        "调用方准备链上资源",
        "wallet-core 校验链级输入",
        "构建并签名交易",
        "返回 raw transaction"
      ],
      "failureScenarios": [
        "链资源过期后旧签名不可继续使用",
        "浮点金额或错误单位可能造成资产精度错误"
      ],
      "evidence": [
        "TypeScript typecheck",
        "链相关 Jest 套件",
        "Sui dry-run 充值模拟"
      ],
      "knownLimits": [
        "Cosmos 依赖解析待修复",
        "不包含在线 RPC、资源预占和广播服务"
      ],
      "overviewSummary": "wallet-core 用 TypeScript 收敛多链钱包入口，但保留每条链影响资产安全的资源状态，而不是假装所有链都只有 from、to、amount。"
    },
    "learning": {
      "goal": "把不同链的密钥、交易和签名差异收敛成可测试的离线核心，同时保留不可抹平的链级约束。",
      "verified": [
        "EVM 原生币与 Token",
        "BTC 多 UTXO、找零和多地址类型",
        "SOL/SPL、TRX/TRC20 与 Sui 原生转账"
      ],
      "verification": [
        "npm run typecheck",
        "npm test -- --runInBand",
        "npm run test:sui",
        "npm run build",
        "npm run sui:deposit"
      ],
      "verificationNote": "类型检查、构建和主要链套件已有本地验证记录；Cosmos 依赖问题明确列为限制。",
      "tradeoffs": [
        "离线核心不负责网络状态",
        "金额只接受最小单位整数",
        "示例不保存真实密钥"
      ],
      "nextSteps": [
        "修复 Cosmos 测试依赖",
        "补充异常交易参数校验",
        "整理链适配器输入契约"
      ]
    },
    "conceptTags": [
      "wallet-core",
      "multi-chain",
      "signer-service",
      "wallet-backend"
    ],
    "relatedArticleSlugs": [
      "multi-chain-wallet-resource-state",
      "wallet-address-models",
      "wallet-sign-signer",
      "wallet-api-boundary"
    ],
    "suggestedQuestions": [
      "wallet-core 如何处理不同链的离线签名输入？",
      "为什么金额只接受最小单位整数？",
      "如何验证多链交易构建？"
    ]
  },
  {
    "id": 8,
    "legacyIds": [],
    "slug": "web3-wallet-engineer-lab",
    "name": "Web3 Wallet Engineer Lab",
    "category": "可运行实验",
    "featured": true,
    "stage": "showcase-ready",
    "sourceType": "original",
    "visibility": "public",
    "repositoryUrl": "https://github.com/qianqiu0404/web3-wallet-engineer-lab",
    "positioning": "用 Go 标准库和内存仓储实现的最小钱包后端闭环，用于练习地址、充值、提现、审核、风控、nonce、归集、审计和指标。",
    "currentFocus": "让钱包领域模型和状态转换可以在一个轻量环境中运行、测试和演示，为 Exchange Wallet Infrastructure 提供更容易复现的证据。",
    "verifiedEvidence": [
      "公开仓库包含可启动 HTTP API，go test ./... 已通过",
      "同一 chain + tx_hash 与相同参数重复充值返回原记录，冲突参数被稳定拒绝",
      "充值与提现流程具有单元测试和接口流程测试，并提供健康检查、Prometheus 文本指标和审计日志"
    ],
    "targetOutcome": "成为一个五分钟可启动、十五分钟可讲完的钱包后端最小实验：完整演示充值入账、提现审核、风控拒绝、nonce 分配和链上确认。",
    "nextMilestone": "增加广播结果未知与链上成功本地失败的可运行故障注入，并让异常手册直接引用对应测试。",
    "knownLimits": [
      "当前使用内存仓储，不等同于生产数据库与分布式状态",
      "链上交互使用模拟接口，不使用真实资产或私钥",
      "当前幂等证据覆盖充值 txHash，提现 request_id、reorg 和账务补偿仍待实现"
    ],
    "updatedAt": "2026-07-13",
    "coreAbilities": [
      "钱包领域模型",
      "充值提现闭环",
      "风控与审核",
      "nonce 与审计",
      "Go HTTP 与测试"
    ],
    "talkingPoints": [
      "为什么先用内存仓储验证领域边界",
      "哪些接口可以替换为 PostgreSQL、Redis 和链 adaptor",
      "如何从最小实验演进到钱包基础设施"
    ],
    "techStack": [
      "Go",
      "net/http",
      "In-memory Store",
      "Prometheus Text",
      "Unit Test"
    ],
    "engineering": {
      "role": "最小钱包后台领域模型与可运行证据的设计实现",
      "systemBoundary": "只验证业务流程和接口边界，不声称包含真实链节点、生产密钥或分布式基础设施。",
      "callFlow": [
        "创建用户并分配地址",
        "模拟充值并确认入账",
        "创建提现并通过风控/审核",
        "分配 nonce 并模拟广播",
        "确认链上交易并写审计"
      ],
      "failureScenarios": [
        "黑名单或额度触发风控拒绝",
        "重复充值事件返回同一记录，同 txHash 不同参数返回幂等冲突"
      ],
      "evidence": [
        "go test ./...",
        "go run ./cmd/api",
        "/healthz 与 /metrics",
        "接口流程测试"
      ],
      "knownLimits": [
        "内存状态不支持多实例",
        "没有真实链和签名机接入"
      ],
      "overviewSummary": "这个实验把钱包业务闭环压缩到可运行的最小代码，用于观察状态机、风控、nonce、审计和可观测性如何协作。"
    },
    "learning": {
      "goal": "用最小代码重复验证钱包领域判断，并把每个核心概念对应到可运行接口和测试。",
      "verified": [
        "充值与提现状态流程",
        "黑名单和额度规则",
        "nonce、归集、审计与指标接口"
      ],
      "verification": [
        "go test ./...",
        "go run ./cmd/api"
      ],
      "verificationNote": "2026-07-13 本地测试通过，源码与 CI 配置已发布到公开仓库。",
      "tradeoffs": [
        "以可运行和可解释优先",
        "内存仓储只用于边界验证",
        "生产化差距必须明确展示"
      ],
      "nextSteps": [
        "增加广播结果未知故障注入",
        "增加链上成功本地失败的补偿测试",
        "明确与钱包基础设施四个服务边界的概念映射"
      ]
    },
    "conceptTags": [
      "wallet-backend",
      "go-infra",
      "api-design"
    ],
    "relatedArticleSlugs": [
      "cex-evm-wallet-deposit-withdrawal-loop",
      "withdrawal-error-handling",
      "http-rpc-grpc"
    ],
    "suggestedQuestions": [
      "这个最小实验验证了哪些钱包后端概念？",
      "它与生产钱包系统还差什么？"
    ]
  }
]
