/* eslint-disable */
// Generated by scripts/generate-articles.mjs. Do not edit by hand.

export type ArticleConceptTag = 'wallet-backend' | 'signer-service' | 'multi-chain' | 'go-infra' | 'evm' | 'mpc-tss' | 'api-design' | 'ai-engineering'
export type ArticleKind = 'engineering-note' | 'research' | 'learning-log'

export interface ArticleSummary {
  id: number
  slug: string
  title: string
  date: string
  updatedAt?: string
  summary: string
  tags: string[]
  readingTime: string
  difficulty: string
  kind: ArticleKind
}

export interface ArticleKnowledge extends ArticleSummary {
  conceptTags: ArticleConceptTag[]
  relatedProjectIds: number[]
  recommendedSlugs: string[]
  suggestedQuestions: string[]
}

export const articleKnowledge: ArticleKnowledge[] = [
  {
    "id": 1,
    "slug": "api-system-calls",
    "title": "API 到底是什么？从钱包后端项目理解系统调用",
    "date": "2026-05-14",
    "summary": "作为基础补充，解释 API 为什么是系统能力边界；核心工程用法已在 wallet-api 职责边界文章中展开。",
    "tags": [
      "API",
      "Backend",
      "System Design",
      "Wallet"
    ],
    "readingTime": "8 min",
    "difficulty": "基础",
    "kind": "engineering-note",
    "conceptTags": [
      "api-design",
      "wallet-backend"
    ],
    "relatedProjectIds": [
      1,
      2,
      3
    ],
    "recommendedSlugs": [
      "wallet-api-boundary",
      "cex-evm-wallet-deposit-withdrawal-loop"
    ],
    "suggestedQuestions": [
      "这篇文章如何解释钱包 API 的系统边界？",
      "普通业务 API 和钱包 API 的差异是什么？"
    ]
  },
  {
    "id": 2,
    "slug": "http-rpc-grpc",
    "title": "HTTP、RPC、gRPC 的区别与项目使用场景",
    "date": "2026-05-16",
    "summary": "作为基础补充，解释 HTTP、RPC、gRPC 的边界；在钱包工程里重点落到 wallet-api 对外 HTTP、wallet-sign 内部 gRPC。",
    "tags": [
      "HTTP",
      "RPC",
      "gRPC",
      "Backend"
    ],
    "readingTime": "10 min",
    "difficulty": "进阶",
    "kind": "engineering-note",
    "conceptTags": [
      "api-design",
      "go-infra"
    ],
    "relatedProjectIds": [
      1,
      2,
      3
    ],
    "recommendedSlugs": [
      "wallet-sign-signer",
      "wallet-api-boundary",
      "cex-evm-wallet-deposit-withdrawal-loop"
    ],
    "suggestedQuestions": [
      "HTTP、RPC、gRPC 在钱包系统里分别适合什么场景？",
      "wallet-api 和 wallet-sign 为什么适合用 gRPC 通信？"
    ]
  },
  {
    "id": 3,
    "slug": "wallet-api-boundary",
    "title": "wallet-api：多链钱包后端 API 的职责边界",
    "date": "2026-05-19",
    "summary": "梳理多链钱包 API 服务如何组织链配置、接口入口、节点 RPC 转换、交易构建、错误处理和签名服务协作。",
    "tags": [
      "Web3",
      "Wallet",
      "Go",
      "API"
    ],
    "readingTime": "12 min",
    "difficulty": "项目拆解",
    "kind": "engineering-note",
    "conceptTags": [
      "wallet-backend",
      "api-design",
      "multi-chain"
    ],
    "relatedProjectIds": [
      1,
      2
    ],
    "recommendedSlugs": [
      "wallet-sign-signer",
      "wallet-address-models"
    ],
    "suggestedQuestions": [
      "wallet-api 应该负责什么，不应该负责什么？",
      "多链钱包 API 的核心复杂度在哪里？",
      "为什么 API 不是一个 URL，而是钱包系统的能力边界？"
    ]
  },
  {
    "id": 4,
    "slug": "wallet-sign-signer",
    "title": "wallet-sign：多链签名机为什么要独立设计",
    "date": "2026-05-21",
    "summary": "从安全边界、私钥管理、离线签名、批量签名和多链差异角度，拆解签名机在钱包系统中的位置。",
    "tags": [
      "Wallet",
      "Signer",
      "Security",
      "Multi-chain"
    ],
    "readingTime": "12 min",
    "difficulty": "项目拆解",
    "kind": "engineering-note",
    "conceptTags": [
      "signer-service",
      "wallet-backend",
      "multi-chain"
    ],
    "relatedProjectIds": [
      1,
      2,
      5
    ],
    "recommendedSlugs": [
      "wallet-api-boundary",
      "wallet-address-models"
    ],
    "suggestedQuestions": [
      "为什么签名机要从 API 层独立出来？",
      "签名服务如何降低私钥暴露风险？",
      "为什么 wallet-api 和 wallet-sign 之间适合用内部 RPC / gRPC？"
    ]
  },
  {
    "id": 5,
    "slug": "market-services-data-flow",
    "title": "market-services：Go 行情服务如何组织数据流",
    "date": "2026-05-24",
    "summary": "从 HTTP、gRPC、Redis、PostgreSQL、行情同步和 Dashboard API，拆解一个 Go 后端行情服务如何运行。",
    "tags": [
      "Go",
      "Market",
      "Backend",
      "Redis"
    ],
    "readingTime": "12 min",
    "difficulty": "项目拆解",
    "kind": "engineering-note",
    "conceptTags": [
      "go-infra",
      "api-design"
    ],
    "relatedProjectIds": [
      3
    ],
    "recommendedSlugs": [
      "http-rpc-grpc",
      "api-system-calls"
    ],
    "suggestedQuestions": [
      "market-services 的数据流如何组织？",
      "Redis 和 PostgreSQL 在行情服务里如何分工？"
    ]
  },
  {
    "id": 6,
    "slug": "wallet-address-models",
    "title": "BTC、ETH、Solana 地址生成与签名模型对比",
    "date": "2026-05-27",
    "summary": "对比 UTXO 模型、账户模型、HD 钱包路径、地址格式和不同链的签名逻辑差异，理解多链钱包为什么需要抽象。",
    "tags": [
      "BTC",
      "ETH",
      "Solana",
      "Multi-chain"
    ],
    "readingTime": "12 min",
    "difficulty": "进阶",
    "kind": "engineering-note",
    "conceptTags": [
      "multi-chain",
      "signer-service",
      "wallet-backend"
    ],
    "relatedProjectIds": [
      1,
      2
    ],
    "recommendedSlugs": [
      "wallet-api-boundary",
      "wallet-sign-signer"
    ],
    "suggestedQuestions": [
      "BTC、ETH、Solana 的地址和签名模型有什么差异？",
      "多链钱包为什么不能用一套交易模型硬套所有链？"
    ]
  },
  {
    "id": 7,
    "slug": "evm-call-proxy-patterns",
    "title": "合约调用与代理升级：从 delegatecall 到钻石代理的工程实践",
    "date": "2026-06-02",
    "summary": "拆解 call / delegatecall / staticcall 的底层差异、透明代理 vs UUPS vs 钻石代理的取舍逻辑，以及不可升级合约的升级策略。",
    "tags": [
      "Solidity",
      "EVM",
      "Proxy",
      "Upgradeability"
    ],
    "readingTime": "14 min",
    "difficulty": "进阶",
    "kind": "engineering-note",
    "conceptTags": [
      "evm"
    ],
    "relatedProjectIds": [],
    "recommendedSlugs": [
      "evm-create2-assembly-lifecycle",
      "eip-erc-protocol-evolution"
    ],
    "suggestedQuestions": [
      "delegatecall 和代理升级的工程风险是什么？",
      "钻石代理适合什么样的合约系统？"
    ]
  },
  {
    "id": 8,
    "slug": "evm-create2-assembly-lifecycle",
    "title": "EVM 深度工程：create2、内联汇编与合约生命周期管理",
    "date": "2026-06-06",
    "summary": "深入 create2 确定性部署、Solidity 内联汇编的内存模型、合约自毁的边界条件和函数选择器的底层工作机制。",
    "tags": [
      "Solidity",
      "EVM",
      "Assembly",
      "create2"
    ],
    "readingTime": "14 min",
    "difficulty": "进阶",
    "kind": "engineering-note",
    "conceptTags": [
      "evm"
    ],
    "relatedProjectIds": [],
    "recommendedSlugs": [
      "evm-call-proxy-patterns",
      "eip-erc-protocol-evolution"
    ],
    "suggestedQuestions": [
      "create2 在合约部署中解决什么问题？",
      "内联汇编在 EVM 工程里应该谨慎用在哪里？"
    ]
  },
  {
    "id": 9,
    "slug": "eip-erc-protocol-evolution",
    "title": "EIP 工程解读：从 ERC20 到 EIP7702 的协议演进与选择逻辑",
    "date": "2026-06-10",
    "summary": "梳理 ERC20/721/1155 的工程差异、EIP1559 的 gas 模型变革、EIP4337 账户抽象和 EIP7702 的 EOA 升级路径。",
    "tags": [
      "EIP",
      "ERC",
      "Ethereum",
      "Standards"
    ],
    "readingTime": "14 min",
    "difficulty": "进阶",
    "kind": "research",
    "conceptTags": [
      "evm",
      "api-design"
    ],
    "relatedProjectIds": [],
    "recommendedSlugs": [
      "evm-call-proxy-patterns",
      "evm-create2-assembly-lifecycle"
    ],
    "suggestedQuestions": [
      "ERC20 到 EIP7702 的演进反映了哪些工程取舍？",
      "协议标准如何影响钱包和 DApp 的设计？"
    ]
  },
  {
    "id": 10,
    "slug": "withdrawal-error-handling",
    "title": "提现错误处理机制：自动重试、补偿任务与人工复核",
    "date": "2026-06-18",
    "summary": "提现错误不能简单按失败重发处理，而要按链上事实是否确定分层：网络和节点问题自动重试，系统状态落后自动补偿，链上事实不确定或账务有风险时人工复核。",
    "tags": [
      "Web3",
      "Wallet",
      "Withdrawal",
      "Backend",
      "Security"
    ],
    "readingTime": "6 min",
    "difficulty": "项目拆解",
    "kind": "engineering-note",
    "conceptTags": [
      "wallet-backend",
      "api-design",
      "multi-chain",
      "signer-service"
    ],
    "relatedProjectIds": [
      1,
      2
    ],
    "recommendedSlugs": [
      "wallet-api-boundary",
      "wallet-sign-signer",
      "wallet-address-models",
      "market-services-data-flow"
    ],
    "suggestedQuestions": [
      "提现广播 timeout 时为什么不能直接重新发一笔？",
      "提现系统如何区分自动重试、自动补偿和人工复核？",
      "EVM nonce 和 BTC UTXO 在提现错误处理中有什么风险？"
    ]
  },
  {
    "id": 11,
    "slug": "mpc-wallet-sign-integration",
    "title": "wallet-sign 接入 MPC：一次签名安全边界升级的工程复盘",
    "date": "2026-06-19",
    "summary": "这次改造里，我把 wallet-sign 从本地私钥签名机收敛成 SignerBackend 调度层，并将 MPC 作为生产级签名后端接入，让完整私钥不再落在单点服务里。",
    "tags": [
      "Web3",
      "Wallet",
      "MPC",
      "TSS",
      "wallet-sign",
      "Security"
    ],
    "readingTime": "6 min",
    "difficulty": "项目拆解",
    "kind": "engineering-note",
    "conceptTags": [
      "mpc-tss",
      "signer-service",
      "wallet-backend",
      "multi-chain"
    ],
    "relatedProjectIds": [
      2,
      5
    ],
    "recommendedSlugs": [
      "wallet-sign-signer",
      "wallet-api-boundary",
      "wallet-address-models",
      "withdrawal-error-handling"
    ],
    "suggestedQuestions": [
      "这次 wallet-sign 接入 MPC 后，签名边界发生了什么变化？",
      "为什么我没有让 wallet-api 或 wallet-service 直接感知 MPC？",
      "MPC 接入后，SignerBackend 抽象解决了什么问题？"
    ]
  },
  {
    "id": 12,
    "slug": "aws-cloudhsm-wallet-sign-integration",
    "title": "wallet-sign 接入 AWS CloudHSM：一次生产级 HSM 签名架构复盘",
    "date": "2026-06-19",
    "summary": "这次改造里，我把 wallet-sign 从本地私钥签名升级为 AWS CloudHSM 支撑的生产级签名架构，让私钥在 HSM 内生成、不可导出，并通过 hsm-gateway 收敛 PKCS#11 复杂性。",
    "tags": [
      "Web3",
      "Wallet",
      "AWS",
      "CloudHSM",
      "HSM",
      "wallet-sign",
      "Security"
    ],
    "readingTime": "8 min",
    "difficulty": "项目拆解",
    "kind": "engineering-note",
    "conceptTags": [
      "signer-service",
      "wallet-backend",
      "multi-chain",
      "mpc-tss"
    ],
    "relatedProjectIds": [
      2,
      5
    ],
    "recommendedSlugs": [
      "mpc-wallet-sign-integration",
      "wallet-sign-signer",
      "wallet-api-boundary",
      "withdrawal-error-handling"
    ],
    "suggestedQuestions": [
      "这次 wallet-sign 接入 AWS CloudHSM 后，签名安全边界发生了什么变化？",
      "为什么要在 wallet-sign 和 CloudHSM 之间加 hsm-gateway？",
      "CloudHSM 签名失败时，为什么不能 fallback 到本地私钥？"
    ]
  },
  {
    "id": 13,
    "slug": "wallet-evolution-2026",
    "title": "2026 钱包发展趋势：从私钥管理到用户意图执行层",
    "date": "2026-06-21",
    "summary": "截至 2026 年 6 月，我对钱包演进的理解是：钱包正在从私钥管理工具，升级为多链资产入口、交易执行入口，以及身份、风控和账户抽象层。",
    "tags": [
      "Web3",
      "Wallet",
      "Account Abstraction",
      "MPC",
      "Chain Abstraction",
      "BTCFi"
    ],
    "readingTime": "6 min",
    "difficulty": "进阶",
    "kind": "research",
    "conceptTags": [
      "wallet-backend",
      "multi-chain",
      "mpc-tss",
      "evm",
      "signer-service"
    ],
    "relatedProjectIds": [
      1,
      2,
      5
    ],
    "recommendedSlugs": [
      "mpc-wallet-sign-integration",
      "aws-cloudhsm-wallet-sign-integration",
      "eip-erc-protocol-evolution",
      "wallet-api-boundary",
      "wallet-address-models",
      "withdrawal-error-handling"
    ],
    "suggestedQuestions": [
      "未来钱包为什么是用户意图执行层？",
      "账户抽象和链抽象分别会改变钱包后端的哪些模块？",
      "CEX 钱包和 Web3 钱包融合后，后端需要补齐哪些能力？"
    ]
  },
  {
    "id": 14,
    "slug": "thorchain-tss-attack-analysis",
    "title": "THORChain Asgard Vault 被攻击不是合约漏洞：TSS/MPC 实现缺陷的安全复盘",
    "date": "2026-06-21",
    "summary": "从 TSS/MPC 签名安全边界复盘 THORChain Asgard vault 攻击：旧版 GG20 实现的 Paillier 参数校验不足，让恶意节点逐步泄露 key material 并重构 vault 私钥。",
    "tags": [
      "Web3",
      "Security",
      "TSS",
      "MPC",
      "THORChain",
      "Cross-chain"
    ],
    "readingTime": "13 min",
    "difficulty": "进阶",
    "kind": "research",
    "conceptTags": [
      "mpc-tss",
      "signer-service",
      "multi-chain"
    ],
    "relatedProjectIds": [
      2,
      5
    ],
    "recommendedSlugs": [
      "mpc-wallet-sign-integration",
      "aws-cloudhsm-wallet-sign-integration",
      "wallet-sign-signer",
      "wallet-evolution-2026",
      "withdrawal-error-handling"
    ],
    "suggestedQuestions": [
      "THORChain 的攻击和普通 DEX 合约攻击有什么本质区别？",
      "GG20 TSS 的 Paillier 参数校验不足如何导致密钥泄露？",
      "为什么 THORChain 的 solvency checker 没有拦截这次攻击？",
      "TSS/MPC 系统设计中有哪些生产级安全边界容易被低估？",
      "这次攻击对 wallet-sign 接入 MPC 有什么警示？"
    ]
  },
  {
    "id": 15,
    "slug": "chainflip-cross-chain-dex-analysis",
    "title": "Chainflip 工程拆解：原生资产跨链兑换网络如何工作",
    "date": "2026-06-21",
    "summary": "Chainflip 不是传统 wrapped bridge，而是用 validator 网络、TSS vault、State Chain 和 JIT AMM 实现原生资产跨链兑换，把 BTC、ETH、SOL、USDC 等资产的跨链闪兑体验协议化。",
    "tags": [
      "Web3",
      "Wallet",
      "Cross-chain",
      "DEX",
      "MPC",
      "Liquidity"
    ],
    "readingTime": "8 min",
    "difficulty": "进阶",
    "kind": "research",
    "conceptTags": [
      "multi-chain",
      "mpc-tss",
      "wallet-backend",
      "signer-service"
    ],
    "relatedProjectIds": [
      1,
      2,
      5
    ],
    "recommendedSlugs": [
      "thorchain-tss-attack-analysis",
      "wallet-evolution-2026",
      "mpc-wallet-sign-integration",
      "wallet-api-boundary",
      "wallet-address-models"
    ],
    "suggestedQuestions": [
      "Chainflip 和普通跨链桥的本质区别是什么？",
      "Chainflip 的 JIT AMM 为什么适合跨链兑换？",
      "钱包接入 Chainflip 这类协议时，后端要处理哪些风险？"
    ]
  },
  {
    "id": 16,
    "slug": "new-chain-integration-checklist",
    "title": "钱包系统上线一条新链，需要调研什么",
    "date": "2026-06-21",
    "summary": "上线一条新链不能只看能不能转账，而要系统调研链模型、地址体系、签名交易、充值扫链、提现构建、手续费、归集、节点、异常、风控、安全、账务和测试。",
    "tags": [
      "Web3",
      "Wallet",
      "Backend",
      "Multi-chain",
      "Operations"
    ],
    "readingTime": "8 min",
    "difficulty": "项目拆解",
    "kind": "engineering-note",
    "conceptTags": [
      "wallet-backend",
      "multi-chain",
      "signer-service",
      "api-design"
    ],
    "relatedProjectIds": [
      1,
      2
    ],
    "recommendedSlugs": [
      "wallet-api-boundary",
      "wallet-address-models",
      "wallet-sign-signer",
      "withdrawal-error-handling",
      "wallet-evolution-2026"
    ],
    "suggestedQuestions": [
      "钱包系统上线一条新链前，为什么不能只测试转账？",
      "Account 模型和 UTXO 模型会怎样影响充值、提现和归集？",
      "新链接入时，账务和对账为什么必须提前设计？"
    ]
  },
  {
    "id": 17,
    "slug": "lubian-weak-private-key-op-return",
    "title": "LuBian 事件复盘：弱私钥熵与 BTC OP_RETURN 链上留言",
    "date": "2026-06-21",
    "summary": "从钱包 key generation 安全角度复盘 LuBian：BTC 私钥生成熵不足会让地址可枚举，OP_RETURN 链上留言只是事故后的链上痕迹。",
    "tags": [
      "Web3",
      "Security",
      "Bitcoin",
      "Wallet",
      "OP_RETURN"
    ],
    "readingTime": "6 min",
    "difficulty": "进阶",
    "kind": "research",
    "conceptTags": [
      "wallet-backend",
      "signer-service",
      "multi-chain"
    ],
    "relatedProjectIds": [
      1,
      2
    ],
    "recommendedSlugs": [
      "wallet-sign-signer",
      "wallet-address-models",
      "new-chain-integration-checklist",
      "withdrawal-error-handling"
    ],
    "suggestedQuestions": [
      "LuBian 事件为什么是私钥生成安全事故？",
      "BTC OP_RETURN 链上留言是怎么工作的？",
      "钱包系统为什么不能自研随机数或 keygen 算法？"
    ]
  },
  {
    "id": 18,
    "slug": "kelpdao-layerzero-dvn-verification-failure",
    "title": "KelpDAO 事件复盘：LayerZero 单 DVN 与跨链验证路径失效",
    "date": "2026-06-21",
    "summary": "从跨链验证路径角度复盘 KelpDAO：问题不是普通合约漏洞，而是单 DVN、RPC 可信边界和源链事实验证失效导致目标链释放 rsETH。",
    "tags": [
      "Web3",
      "Security",
      "Cross-chain",
      "LayerZero",
      "Bridge",
      "DeFi"
    ],
    "readingTime": "6 min",
    "difficulty": "进阶",
    "kind": "research",
    "conceptTags": [
      "multi-chain",
      "wallet-backend",
      "mpc-tss"
    ],
    "relatedProjectIds": [
      1,
      5
    ],
    "recommendedSlugs": [
      "chainflip-cross-chain-dex-analysis",
      "thorchain-tss-attack-analysis",
      "wallet-evolution-2026",
      "new-chain-integration-checklist"
    ],
    "suggestedQuestions": [
      "KelpDAO 事件为什么是跨链验证路径失败？",
      "LayerZero DVN 单点配置有什么风险？",
      "为什么 Aave 没被直接攻击却会被波及？"
    ]
  },
  {
    "id": 19,
    "slug": "evm-internal-transfer-deposit-indexer",
    "title": "EVM 充值扫链进阶：如何识别 Internal Txns 原生币入账",
    "date": "2026-06-23",
    "summary": "EVM Internal Native Transfer 不会出现在外层 tx.to，也不一定出现在 receipt logs。交易所要识别这类充值，本质是解析 EVM 的 CALL 执行树，通过 debug_traceTransaction 或 trace_transaction 找到 value > 0 且 to 命中平台充值地址的调用节点。",
    "tags": [
      "Web3",
      "Wallet",
      "Backend",
      "Indexer",
      "EVM",
      "Bridge"
    ],
    "readingTime": "5 min",
    "difficulty": "项目拆解",
    "kind": "engineering-note",
    "conceptTags": [
      "wallet-backend",
      "multi-chain",
      "api-design"
    ],
    "relatedProjectIds": [
      1,
      2
    ],
    "recommendedSlugs": [
      "new-chain-integration-checklist",
      "wallet-api-boundary",
      "wallet-address-models",
      "withdrawal-error-handling",
      "cex-evm-wallet-deposit-withdrawal-loop"
    ],
    "suggestedQuestions": [
      "Internal Native Transfer 怎么通过 CALL 树解析？",
      "为什么 receipt logs 看不到原生币内部转账？",
      "ETH 普通充值、ERC20 和 Internal ETH 充值分别应该看哪里？"
    ]
  },
  {
    "id": 20,
    "slug": "cex-evm-wallet-deposit-withdrawal-loop",
    "title": "从充值到提现：我完整跑通了一条交易所 EVM 钱包链路",
    "date": "2026-06-23",
    "summary": "这篇复盘记录我如何跑通交易所钱包充值提现闭环：把一条 EVM 链从地址生成、充值扫链、余额入账、提现冻结、交易构建、签名广播、receipt 确认到业务通知串成完整资金链路。",
    "tags": [
      "Web3",
      "Wallet",
      "Backend",
      "Exchange Wallet",
      "EVM"
    ],
    "readingTime": "8 min",
    "difficulty": "项目拆解",
    "kind": "engineering-note",
    "conceptTags": [
      "wallet-backend",
      "multi-chain",
      "api-design",
      "evm"
    ],
    "relatedProjectIds": [
      1,
      2
    ],
    "recommendedSlugs": [
      "evm-internal-transfer-deposit-indexer",
      "withdrawal-error-handling",
      "new-chain-integration-checklist",
      "wallet-api-boundary",
      "wallet-sign-signer"
    ],
    "suggestedQuestions": [
      "交易所钱包充值提现闭环是什么？",
      "为什么 broadcasted 不等于提现成功？",
      "提现时 available_balance 和 lock_balance 应该怎么变化？"
    ]
  },
  {
    "id": 21,
    "slug": "bridge-liquidity-after-market-crash",
    "title": "市场暴跌后，为什么跨链桥和跨链兑换会变难用",
    "date": "2026-06-24",
    "summary": "市场暴跌后，跨链桥和跨链兑换的流动性会变差，本质是单边逃离、LP 撤流动性、做市商扩大价差、跨链库存失衡和价格波动风险同时发生。钱包后端不能只展示 quote，而要把跨链交易建模成可观测、可解释、可补偿的异步状态机。",
    "tags": [
      "Web3",
      "Wallet",
      "Cross-chain",
      "Liquidity",
      "Bridge",
      "Backend"
    ],
    "readingTime": "9 min",
    "difficulty": "进阶",
    "kind": "research",
    "conceptTags": [
      "wallet-backend",
      "multi-chain",
      "api-design"
    ],
    "relatedProjectIds": [
      1,
      2,
      5
    ],
    "recommendedSlugs": [
      "chainflip-cross-chain-dex-analysis",
      "wallet-evolution-2026",
      "new-chain-integration-checklist",
      "cex-evm-wallet-deposit-withdrawal-loop",
      "thorchain-tss-attack-analysis"
    ],
    "suggestedQuestions": [
      "市场暴跌后为什么桥接流动性会变差？",
      "跨链库存失衡会怎样影响桥和跨链兑换报价？",
      "钱包后端如何在流动性变差时兜住跨链体验？"
    ]
  },
  {
    "id": 22,
    "slug": "bitcoin-utxo-ordinals-runes-indexer",
    "title": "Bitcoin 区块里都是 UTXO，为什么还能有 NFT 和 Token",
    "date": "2026-06-24",
    "summary": "Bitcoin 本身没有账户模型、智能合约 NFT 或 ERC20 余额表，但 UTXO 交易可以携带 OP_RETURN、Taproot witness 和 inscription 数据，再由 Ordinals、BRC-20、Runes 等协议和链下索引器解释成 NFT 或 Token 状态。",
    "tags": [
      "Bitcoin",
      "UTXO",
      "Ordinals",
      "Runes",
      "Indexer",
      "Wallet"
    ],
    "readingTime": "7 min",
    "difficulty": "进阶",
    "kind": "research",
    "conceptTags": [
      "wallet-backend",
      "multi-chain",
      "signer-service"
    ],
    "relatedProjectIds": [
      1,
      2
    ],
    "recommendedSlugs": [
      "wallet-address-models",
      "lubian-weak-private-key-op-return",
      "new-chain-integration-checklist",
      "wallet-evolution-2026",
      "wallet-sign-signer"
    ],
    "suggestedQuestions": [
      "Bitcoin 都是 UTXO 交易，为什么还能有 NFT 和 Token？",
      "Ordinals、BRC-20 和 Runes 分别依赖什么数据结构？",
      "BTC 钱包为什么需要链下索引器才能展示铭文和 Rune 资产？"
    ]
  },
  {
    "id": 23,
    "slug": "web3-narrative-participation-framework",
    "title": "进入 Web3 新叙事的四种方式：RWA、Perp DEX 与稳定币支付",
    "date": "2026-06-29",
    "summary": "进入一个 Web3 叙事不等于购买名字最响的代币。本文用用户体验、资金参与、股权或代币价值捕获、工程建设四层框架，对比 RWA、Perp DEX 与稳定币支付的系统结构、参与方式和风险边界。",
    "tags": [
      "Web3",
      "RWA",
      "Perp DEX",
      "Stablecoin",
      "Builder",
      "Wallet"
    ],
    "readingTime": "5 min",
    "difficulty": "进阶",
    "kind": "research",
    "conceptTags": [
      "wallet-backend",
      "api-design",
      "evm",
      "multi-chain"
    ],
    "relatedProjectIds": [
      1,
      3
    ],
    "recommendedSlugs": [
      "rwa-tokenized-stocks-structure",
      "perp-dex-user-capital-builder",
      "stablecoin-x402-agent-payments",
      "wallet-evolution-2026",
      "wallet-api-boundary"
    ],
    "suggestedQuestions": [
      "进入一个 Web3 叙事有哪些不同方式？",
      "为什么购买项目代币不等于分享项目收入？",
      "RWA、Perp DEX 和稳定币支付分别有哪些建设机会？"
    ]
  },
  {
    "id": 24,
    "slug": "rwa-tokenized-stocks-structure",
    "title": "RWA 与美股上链：你持有的究竟是什么",
    "date": "2026-06-29",
    "summary": "代币化美股不是把股票直接变成 ERC20。本文从发行实体、SPV、托管资产、结构化票据、链上 Token 和赎回权拆解 RWA 产品，并分析钱包接入这类资产时需要处理的合规、状态和对账边界。",
    "tags": [
      "Web3",
      "RWA",
      "Tokenized Stocks",
      "Wallet",
      "Compliance",
      "Backend"
    ],
    "readingTime": "6 min",
    "difficulty": "进阶",
    "kind": "research",
    "conceptTags": [
      "wallet-backend",
      "multi-chain",
      "evm",
      "api-design"
    ],
    "relatedProjectIds": [
      1,
      2
    ],
    "recommendedSlugs": [
      "web3-narrative-participation-framework",
      "wallet-evolution-2026",
      "wallet-api-boundary",
      "new-chain-integration-checklist",
      "stablecoin-x402-agent-payments"
    ],
    "suggestedQuestions": [
      "代币化美股持有人拥有的是股票还是经济敞口？",
      "RWA 产品里的 SPV、托管机构和链上 Token 分别负责什么？",
      "钱包接入受限 RWA 资产时需要处理哪些状态和风险？"
    ]
  },
  {
    "id": 25,
    "slug": "perp-dex-user-capital-builder",
    "title": "Perp DEX 参与路径：从交易用户到 Builder",
    "date": "2026-06-29",
    "summary": "Perp DEX 不只是一个可以买卖永续合约的前端。本文从保证金、Funding、清算、订单状态和 API 工具拆解其资金流，并区分交易用户、Vault 资金、代币持有人与 Builder 的收益来源和风险。",
    "tags": [
      "Web3",
      "Perp DEX",
      "Trading",
      "Hyperliquid",
      "API",
      "Risk"
    ],
    "readingTime": "6 min",
    "difficulty": "进阶",
    "kind": "research",
    "conceptTags": [
      "api-design",
      "go-infra",
      "evm",
      "wallet-backend"
    ],
    "relatedProjectIds": [
      3
    ],
    "recommendedSlugs": [
      "web3-narrative-participation-framework",
      "market-services-data-flow",
      "chainflip-cross-chain-dex-analysis",
      "bridge-liquidity-after-market-crash",
      "wallet-evolution-2026"
    ],
    "suggestedQuestions": [
      "Perp DEX 里的保证金、Funding 和清算如何形成完整资金流？",
      "为什么 Perp DEX 交易量增长不等于平台代币捕获收入？",
      "开发者如何通过 API 和 Builder Codes 参与 Perp DEX？"
    ]
  },
  {
    "id": 26,
    "slug": "stablecoin-x402-agent-payments",
    "title": "稳定币与 AI Agent 支付：x402 如何让 API 自主结算",
    "date": "2026-06-29",
    "summary": "x402 把 HTTP 402、钱包签名、支付验证和链上结算组合成按次付费协议，让人类客户端和 AI Agent 可以为 API 自动支付稳定币。本文拆解其调用流程、钱包权限、商户账务和失败恢复边界。",
    "tags": [
      "Web3",
      "Stablecoin",
      "x402",
      "AI Agent",
      "Payments",
      "API"
    ],
    "readingTime": "6 min",
    "difficulty": "进阶",
    "kind": "research",
    "conceptTags": [
      "wallet-backend",
      "api-design",
      "evm",
      "signer-service"
    ],
    "relatedProjectIds": [
      1,
      2,
      3
    ],
    "recommendedSlugs": [
      "web3-narrative-participation-framework",
      "wallet-api-boundary",
      "wallet-sign-signer",
      "cex-evm-wallet-deposit-withdrawal-loop",
      "wallet-evolution-2026"
    ],
    "suggestedQuestions": [
      "x402 如何让 AI Agent 自动为 API 支付稳定币？",
      "支付验证成功为什么不等于商户业务已经履约？",
      "Agent 钱包需要哪些额度、白名单和审计控制？"
    ]
  },
  {
    "id": 27,
    "slug": "codex-ai-workflow-system-retrospective",
    "title": "从重复任务到可恢复工作流：我的 Codex、Skill、Automation 与 MCP 实践",
    "date": "2026-07-03",
    "summary": "这篇复盘记录我如何把钱包工程验证、公众号增量同步和每日 Web3 研究，从一次性 AI 对话沉淀成三种可重复、可验证、可恢复的工作流，并用 MCP 和 Obsidian 建立知识回流。",
    "tags": [
      "AI Engineering",
      "Codex",
      "Workflow",
      "Automation",
      "MCP",
      "Obsidian"
    ],
    "readingTime": "10 min",
    "difficulty": "项目拆解",
    "kind": "learning-log",
    "conceptTags": [
      "ai-engineering",
      "wallet-backend",
      "api-design",
      "go-infra"
    ],
    "relatedProjectIds": [
      1,
      2,
      3
    ],
    "recommendedSlugs": [
      "cex-evm-wallet-deposit-withdrawal-loop",
      "wallet-api-boundary",
      "market-services-data-flow",
      "stablecoin-x402-agent-payments",
      "wallet-evolution-2026"
    ],
    "suggestedQuestions": [
      "钱包验证 loop、公众号 Skill 和每日 Automation 有什么区别？",
      "Skill、Automation、MCP 和 Obsidian 在工作流中分别负责什么？",
      "如何把一次性 AI 对话变成可恢复、可验证的工程工作流？"
    ]
  },
  {
    "id": 28,
    "slug": "multi-chain-wallet-resource-state",
    "title": "钱包后端不能隐藏的资源状态：Nonce、UTXO、Blockhash 与 Object Version",
    "date": "2026-07-03",
    "summary": "多链钱包可以统一转账、签名和广播的业务语义，但不能隐藏决定交易唯一性、时效性和可执行性的资源状态。这篇文章用 EVM nonce、ERC-4337 nonce key、BTC UTXO、Solana blockhash 和 Sui object version，复盘资源如何解析、预占和冻结，以及资源过期后为什么需要重新构建和签名。",
    "tags": [
      "Web3",
      "Wallet",
      "Multi-chain",
      "Nonce",
      "UTXO",
      "Solana",
      "Sui"
    ],
    "readingTime": "6 min",
    "difficulty": "项目拆解",
    "kind": "engineering-note",
    "conceptTags": [
      "wallet-backend",
      "multi-chain",
      "signer-service",
      "api-design"
    ],
    "relatedProjectIds": [
      1,
      2
    ],
    "recommendedSlugs": [
      "new-chain-integration-checklist",
      "wallet-address-models",
      "wallet-api-boundary",
      "wallet-sign-signer",
      "withdrawal-error-handling",
      "eip-erc-protocol-evolution"
    ],
    "suggestedQuestions": [
      "为什么多链钱包不能把 nonce、UTXO、blockhash 和 objectRef 全部藏在 adaptor 里？",
      "资源过期后为什么需要重新构建和签名？",
      "wallet-service、wallet-api、wallet-sign 三个钱包服务分别负责哪一层资源状态？"
    ]
  },
  {
    "id": 29,
    "slug": "erc4337-useroperation-lifecycle",
    "title": "ERC-4337 工程拆解：一笔 UserOperation 如何验证、支付 Gas 并进入链上",
    "date": "2026-07-07",
    "summary": "从钱包后端视角拆解一笔 UserOperation 如何经过 nonce 分配、账户签名、Bundler 模拟、Paymaster 验证、EntryPoint 执行和 Gas 结算，并说明账户抽象为什么没有消除状态机。",
    "tags": [
      "Web3",
      "Wallet",
      "ERC-4337",
      "Account Abstraction",
      "Bundler",
      "Paymaster"
    ],
    "readingTime": "8 min",
    "difficulty": "项目拆解",
    "kind": "engineering-note",
    "conceptTags": [
      "wallet-backend",
      "signer-service",
      "api-design",
      "evm"
    ],
    "relatedProjectIds": [
      1,
      2
    ],
    "recommendedSlugs": [
      "multi-chain-wallet-resource-state",
      "wallet-api-boundary",
      "wallet-sign-signer",
      "eip-erc-protocol-evolution",
      "wallet-evolution-2026",
      "withdrawal-error-handling"
    ],
    "suggestedQuestions": [
      "UserOperation 已经签名，为什么 Bundler 还需要模拟验证？",
      "ERC-4337 的 nonce key 和 sequence 如何支持并行操作？",
      "Paymaster 支付 Gas 后，钱包后端需要记录哪些资金状态？"
    ]
  },
  {
    "id": 30,
    "slug": "minimal-multi-agent-coding-workflow",
    "title": "从单 Agent 到最小 Multi-Agent：我的 AI Coding 工作流进化",
    "date": "2026-07-09",
    "summary": "这篇成长日志记录我如何从让 AI 直接帮我写代码，进化到用 Planner、Worker、Reviewer 三个角色组织复杂 Coding 任务，让 AI Coding 变成有边界、有交接、有审查的工程流程。",
    "tags": [
      "AI Engineering",
      "Codex",
      "Multi-Agent",
      "Workflow",
      "Coding"
    ],
    "readingTime": "6 min",
    "difficulty": "项目拆解",
    "kind": "learning-log",
    "conceptTags": [
      "ai-engineering",
      "go-infra",
      "api-design"
    ],
    "relatedProjectIds": [
      1,
      2,
      3
    ],
    "recommendedSlugs": [
      "codex-ai-workflow-system-retrospective",
      "erc4337-useroperation-lifecycle",
      "cex-evm-wallet-deposit-withdrawal-loop",
      "wallet-api-boundary"
    ],
    "suggestedQuestions": [
      "为什么最小 Multi-Agent 只需要 Planner、Worker 和 Reviewer？",
      "Multi-Agent Coding 和普通 AI 写代码有什么区别？",
      "什么时候应该使用 Multi-Agent，什么时候不应该？"
    ]
  }
]

export const articleSummaries: ArticleSummary[] = [
  {
    "id": 1,
    "slug": "api-system-calls",
    "title": "API 到底是什么？从钱包后端项目理解系统调用",
    "date": "2026-05-14",
    "summary": "作为基础补充，解释 API 为什么是系统能力边界；核心工程用法已在 wallet-api 职责边界文章中展开。",
    "tags": [
      "API",
      "Backend",
      "System Design",
      "Wallet"
    ],
    "readingTime": "8 min",
    "difficulty": "基础",
    "kind": "engineering-note"
  },
  {
    "id": 2,
    "slug": "http-rpc-grpc",
    "title": "HTTP、RPC、gRPC 的区别与项目使用场景",
    "date": "2026-05-16",
    "summary": "作为基础补充，解释 HTTP、RPC、gRPC 的边界；在钱包工程里重点落到 wallet-api 对外 HTTP、wallet-sign 内部 gRPC。",
    "tags": [
      "HTTP",
      "RPC",
      "gRPC",
      "Backend"
    ],
    "readingTime": "10 min",
    "difficulty": "进阶",
    "kind": "engineering-note"
  },
  {
    "id": 3,
    "slug": "wallet-api-boundary",
    "title": "wallet-api：多链钱包后端 API 的职责边界",
    "date": "2026-05-19",
    "summary": "梳理多链钱包 API 服务如何组织链配置、接口入口、节点 RPC 转换、交易构建、错误处理和签名服务协作。",
    "tags": [
      "Web3",
      "Wallet",
      "Go",
      "API"
    ],
    "readingTime": "12 min",
    "difficulty": "项目拆解",
    "kind": "engineering-note"
  },
  {
    "id": 4,
    "slug": "wallet-sign-signer",
    "title": "wallet-sign：多链签名机为什么要独立设计",
    "date": "2026-05-21",
    "summary": "从安全边界、私钥管理、离线签名、批量签名和多链差异角度，拆解签名机在钱包系统中的位置。",
    "tags": [
      "Wallet",
      "Signer",
      "Security",
      "Multi-chain"
    ],
    "readingTime": "12 min",
    "difficulty": "项目拆解",
    "kind": "engineering-note"
  },
  {
    "id": 5,
    "slug": "market-services-data-flow",
    "title": "market-services：Go 行情服务如何组织数据流",
    "date": "2026-05-24",
    "summary": "从 HTTP、gRPC、Redis、PostgreSQL、行情同步和 Dashboard API，拆解一个 Go 后端行情服务如何运行。",
    "tags": [
      "Go",
      "Market",
      "Backend",
      "Redis"
    ],
    "readingTime": "12 min",
    "difficulty": "项目拆解",
    "kind": "engineering-note"
  },
  {
    "id": 6,
    "slug": "wallet-address-models",
    "title": "BTC、ETH、Solana 地址生成与签名模型对比",
    "date": "2026-05-27",
    "summary": "对比 UTXO 模型、账户模型、HD 钱包路径、地址格式和不同链的签名逻辑差异，理解多链钱包为什么需要抽象。",
    "tags": [
      "BTC",
      "ETH",
      "Solana",
      "Multi-chain"
    ],
    "readingTime": "12 min",
    "difficulty": "进阶",
    "kind": "engineering-note"
  },
  {
    "id": 7,
    "slug": "evm-call-proxy-patterns",
    "title": "合约调用与代理升级：从 delegatecall 到钻石代理的工程实践",
    "date": "2026-06-02",
    "summary": "拆解 call / delegatecall / staticcall 的底层差异、透明代理 vs UUPS vs 钻石代理的取舍逻辑，以及不可升级合约的升级策略。",
    "tags": [
      "Solidity",
      "EVM",
      "Proxy",
      "Upgradeability"
    ],
    "readingTime": "14 min",
    "difficulty": "进阶",
    "kind": "engineering-note"
  },
  {
    "id": 8,
    "slug": "evm-create2-assembly-lifecycle",
    "title": "EVM 深度工程：create2、内联汇编与合约生命周期管理",
    "date": "2026-06-06",
    "summary": "深入 create2 确定性部署、Solidity 内联汇编的内存模型、合约自毁的边界条件和函数选择器的底层工作机制。",
    "tags": [
      "Solidity",
      "EVM",
      "Assembly",
      "create2"
    ],
    "readingTime": "14 min",
    "difficulty": "进阶",
    "kind": "engineering-note"
  },
  {
    "id": 9,
    "slug": "eip-erc-protocol-evolution",
    "title": "EIP 工程解读：从 ERC20 到 EIP7702 的协议演进与选择逻辑",
    "date": "2026-06-10",
    "summary": "梳理 ERC20/721/1155 的工程差异、EIP1559 的 gas 模型变革、EIP4337 账户抽象和 EIP7702 的 EOA 升级路径。",
    "tags": [
      "EIP",
      "ERC",
      "Ethereum",
      "Standards"
    ],
    "readingTime": "14 min",
    "difficulty": "进阶",
    "kind": "research"
  },
  {
    "id": 10,
    "slug": "withdrawal-error-handling",
    "title": "提现错误处理机制：自动重试、补偿任务与人工复核",
    "date": "2026-06-18",
    "summary": "提现错误不能简单按失败重发处理，而要按链上事实是否确定分层：网络和节点问题自动重试，系统状态落后自动补偿，链上事实不确定或账务有风险时人工复核。",
    "tags": [
      "Web3",
      "Wallet",
      "Withdrawal",
      "Backend",
      "Security"
    ],
    "readingTime": "6 min",
    "difficulty": "项目拆解",
    "kind": "engineering-note"
  },
  {
    "id": 11,
    "slug": "mpc-wallet-sign-integration",
    "title": "wallet-sign 接入 MPC：一次签名安全边界升级的工程复盘",
    "date": "2026-06-19",
    "summary": "这次改造里，我把 wallet-sign 从本地私钥签名机收敛成 SignerBackend 调度层，并将 MPC 作为生产级签名后端接入，让完整私钥不再落在单点服务里。",
    "tags": [
      "Web3",
      "Wallet",
      "MPC",
      "TSS",
      "wallet-sign",
      "Security"
    ],
    "readingTime": "6 min",
    "difficulty": "项目拆解",
    "kind": "engineering-note"
  },
  {
    "id": 12,
    "slug": "aws-cloudhsm-wallet-sign-integration",
    "title": "wallet-sign 接入 AWS CloudHSM：一次生产级 HSM 签名架构复盘",
    "date": "2026-06-19",
    "summary": "这次改造里，我把 wallet-sign 从本地私钥签名升级为 AWS CloudHSM 支撑的生产级签名架构，让私钥在 HSM 内生成、不可导出，并通过 hsm-gateway 收敛 PKCS#11 复杂性。",
    "tags": [
      "Web3",
      "Wallet",
      "AWS",
      "CloudHSM",
      "HSM",
      "wallet-sign",
      "Security"
    ],
    "readingTime": "8 min",
    "difficulty": "项目拆解",
    "kind": "engineering-note"
  },
  {
    "id": 13,
    "slug": "wallet-evolution-2026",
    "title": "2026 钱包发展趋势：从私钥管理到用户意图执行层",
    "date": "2026-06-21",
    "summary": "截至 2026 年 6 月，我对钱包演进的理解是：钱包正在从私钥管理工具，升级为多链资产入口、交易执行入口，以及身份、风控和账户抽象层。",
    "tags": [
      "Web3",
      "Wallet",
      "Account Abstraction",
      "MPC",
      "Chain Abstraction",
      "BTCFi"
    ],
    "readingTime": "6 min",
    "difficulty": "进阶",
    "kind": "research"
  },
  {
    "id": 14,
    "slug": "thorchain-tss-attack-analysis",
    "title": "THORChain Asgard Vault 被攻击不是合约漏洞：TSS/MPC 实现缺陷的安全复盘",
    "date": "2026-06-21",
    "summary": "从 TSS/MPC 签名安全边界复盘 THORChain Asgard vault 攻击：旧版 GG20 实现的 Paillier 参数校验不足，让恶意节点逐步泄露 key material 并重构 vault 私钥。",
    "tags": [
      "Web3",
      "Security",
      "TSS",
      "MPC",
      "THORChain",
      "Cross-chain"
    ],
    "readingTime": "13 min",
    "difficulty": "进阶",
    "kind": "research"
  },
  {
    "id": 15,
    "slug": "chainflip-cross-chain-dex-analysis",
    "title": "Chainflip 工程拆解：原生资产跨链兑换网络如何工作",
    "date": "2026-06-21",
    "summary": "Chainflip 不是传统 wrapped bridge，而是用 validator 网络、TSS vault、State Chain 和 JIT AMM 实现原生资产跨链兑换，把 BTC、ETH、SOL、USDC 等资产的跨链闪兑体验协议化。",
    "tags": [
      "Web3",
      "Wallet",
      "Cross-chain",
      "DEX",
      "MPC",
      "Liquidity"
    ],
    "readingTime": "8 min",
    "difficulty": "进阶",
    "kind": "research"
  },
  {
    "id": 16,
    "slug": "new-chain-integration-checklist",
    "title": "钱包系统上线一条新链，需要调研什么",
    "date": "2026-06-21",
    "summary": "上线一条新链不能只看能不能转账，而要系统调研链模型、地址体系、签名交易、充值扫链、提现构建、手续费、归集、节点、异常、风控、安全、账务和测试。",
    "tags": [
      "Web3",
      "Wallet",
      "Backend",
      "Multi-chain",
      "Operations"
    ],
    "readingTime": "8 min",
    "difficulty": "项目拆解",
    "kind": "engineering-note"
  },
  {
    "id": 17,
    "slug": "lubian-weak-private-key-op-return",
    "title": "LuBian 事件复盘：弱私钥熵与 BTC OP_RETURN 链上留言",
    "date": "2026-06-21",
    "summary": "从钱包 key generation 安全角度复盘 LuBian：BTC 私钥生成熵不足会让地址可枚举，OP_RETURN 链上留言只是事故后的链上痕迹。",
    "tags": [
      "Web3",
      "Security",
      "Bitcoin",
      "Wallet",
      "OP_RETURN"
    ],
    "readingTime": "6 min",
    "difficulty": "进阶",
    "kind": "research"
  },
  {
    "id": 18,
    "slug": "kelpdao-layerzero-dvn-verification-failure",
    "title": "KelpDAO 事件复盘：LayerZero 单 DVN 与跨链验证路径失效",
    "date": "2026-06-21",
    "summary": "从跨链验证路径角度复盘 KelpDAO：问题不是普通合约漏洞，而是单 DVN、RPC 可信边界和源链事实验证失效导致目标链释放 rsETH。",
    "tags": [
      "Web3",
      "Security",
      "Cross-chain",
      "LayerZero",
      "Bridge",
      "DeFi"
    ],
    "readingTime": "6 min",
    "difficulty": "进阶",
    "kind": "research"
  },
  {
    "id": 19,
    "slug": "evm-internal-transfer-deposit-indexer",
    "title": "EVM 充值扫链进阶：如何识别 Internal Txns 原生币入账",
    "date": "2026-06-23",
    "summary": "EVM Internal Native Transfer 不会出现在外层 tx.to，也不一定出现在 receipt logs。交易所要识别这类充值，本质是解析 EVM 的 CALL 执行树，通过 debug_traceTransaction 或 trace_transaction 找到 value > 0 且 to 命中平台充值地址的调用节点。",
    "tags": [
      "Web3",
      "Wallet",
      "Backend",
      "Indexer",
      "EVM",
      "Bridge"
    ],
    "readingTime": "5 min",
    "difficulty": "项目拆解",
    "kind": "engineering-note"
  },
  {
    "id": 20,
    "slug": "cex-evm-wallet-deposit-withdrawal-loop",
    "title": "从充值到提现：我完整跑通了一条交易所 EVM 钱包链路",
    "date": "2026-06-23",
    "summary": "这篇复盘记录我如何跑通交易所钱包充值提现闭环：把一条 EVM 链从地址生成、充值扫链、余额入账、提现冻结、交易构建、签名广播、receipt 确认到业务通知串成完整资金链路。",
    "tags": [
      "Web3",
      "Wallet",
      "Backend",
      "Exchange Wallet",
      "EVM"
    ],
    "readingTime": "8 min",
    "difficulty": "项目拆解",
    "kind": "engineering-note"
  },
  {
    "id": 21,
    "slug": "bridge-liquidity-after-market-crash",
    "title": "市场暴跌后，为什么跨链桥和跨链兑换会变难用",
    "date": "2026-06-24",
    "summary": "市场暴跌后，跨链桥和跨链兑换的流动性会变差，本质是单边逃离、LP 撤流动性、做市商扩大价差、跨链库存失衡和价格波动风险同时发生。钱包后端不能只展示 quote，而要把跨链交易建模成可观测、可解释、可补偿的异步状态机。",
    "tags": [
      "Web3",
      "Wallet",
      "Cross-chain",
      "Liquidity",
      "Bridge",
      "Backend"
    ],
    "readingTime": "9 min",
    "difficulty": "进阶",
    "kind": "research"
  },
  {
    "id": 22,
    "slug": "bitcoin-utxo-ordinals-runes-indexer",
    "title": "Bitcoin 区块里都是 UTXO，为什么还能有 NFT 和 Token",
    "date": "2026-06-24",
    "summary": "Bitcoin 本身没有账户模型、智能合约 NFT 或 ERC20 余额表，但 UTXO 交易可以携带 OP_RETURN、Taproot witness 和 inscription 数据，再由 Ordinals、BRC-20、Runes 等协议和链下索引器解释成 NFT 或 Token 状态。",
    "tags": [
      "Bitcoin",
      "UTXO",
      "Ordinals",
      "Runes",
      "Indexer",
      "Wallet"
    ],
    "readingTime": "7 min",
    "difficulty": "进阶",
    "kind": "research"
  },
  {
    "id": 23,
    "slug": "web3-narrative-participation-framework",
    "title": "进入 Web3 新叙事的四种方式：RWA、Perp DEX 与稳定币支付",
    "date": "2026-06-29",
    "summary": "进入一个 Web3 叙事不等于购买名字最响的代币。本文用用户体验、资金参与、股权或代币价值捕获、工程建设四层框架，对比 RWA、Perp DEX 与稳定币支付的系统结构、参与方式和风险边界。",
    "tags": [
      "Web3",
      "RWA",
      "Perp DEX",
      "Stablecoin",
      "Builder",
      "Wallet"
    ],
    "readingTime": "5 min",
    "difficulty": "进阶",
    "kind": "research"
  },
  {
    "id": 24,
    "slug": "rwa-tokenized-stocks-structure",
    "title": "RWA 与美股上链：你持有的究竟是什么",
    "date": "2026-06-29",
    "summary": "代币化美股不是把股票直接变成 ERC20。本文从发行实体、SPV、托管资产、结构化票据、链上 Token 和赎回权拆解 RWA 产品，并分析钱包接入这类资产时需要处理的合规、状态和对账边界。",
    "tags": [
      "Web3",
      "RWA",
      "Tokenized Stocks",
      "Wallet",
      "Compliance",
      "Backend"
    ],
    "readingTime": "6 min",
    "difficulty": "进阶",
    "kind": "research"
  },
  {
    "id": 25,
    "slug": "perp-dex-user-capital-builder",
    "title": "Perp DEX 参与路径：从交易用户到 Builder",
    "date": "2026-06-29",
    "summary": "Perp DEX 不只是一个可以买卖永续合约的前端。本文从保证金、Funding、清算、订单状态和 API 工具拆解其资金流，并区分交易用户、Vault 资金、代币持有人与 Builder 的收益来源和风险。",
    "tags": [
      "Web3",
      "Perp DEX",
      "Trading",
      "Hyperliquid",
      "API",
      "Risk"
    ],
    "readingTime": "6 min",
    "difficulty": "进阶",
    "kind": "research"
  },
  {
    "id": 26,
    "slug": "stablecoin-x402-agent-payments",
    "title": "稳定币与 AI Agent 支付：x402 如何让 API 自主结算",
    "date": "2026-06-29",
    "summary": "x402 把 HTTP 402、钱包签名、支付验证和链上结算组合成按次付费协议，让人类客户端和 AI Agent 可以为 API 自动支付稳定币。本文拆解其调用流程、钱包权限、商户账务和失败恢复边界。",
    "tags": [
      "Web3",
      "Stablecoin",
      "x402",
      "AI Agent",
      "Payments",
      "API"
    ],
    "readingTime": "6 min",
    "difficulty": "进阶",
    "kind": "research"
  },
  {
    "id": 27,
    "slug": "codex-ai-workflow-system-retrospective",
    "title": "从重复任务到可恢复工作流：我的 Codex、Skill、Automation 与 MCP 实践",
    "date": "2026-07-03",
    "summary": "这篇复盘记录我如何把钱包工程验证、公众号增量同步和每日 Web3 研究，从一次性 AI 对话沉淀成三种可重复、可验证、可恢复的工作流，并用 MCP 和 Obsidian 建立知识回流。",
    "tags": [
      "AI Engineering",
      "Codex",
      "Workflow",
      "Automation",
      "MCP",
      "Obsidian"
    ],
    "readingTime": "10 min",
    "difficulty": "项目拆解",
    "kind": "learning-log"
  },
  {
    "id": 28,
    "slug": "multi-chain-wallet-resource-state",
    "title": "钱包后端不能隐藏的资源状态：Nonce、UTXO、Blockhash 与 Object Version",
    "date": "2026-07-03",
    "summary": "多链钱包可以统一转账、签名和广播的业务语义，但不能隐藏决定交易唯一性、时效性和可执行性的资源状态。这篇文章用 EVM nonce、ERC-4337 nonce key、BTC UTXO、Solana blockhash 和 Sui object version，复盘资源如何解析、预占和冻结，以及资源过期后为什么需要重新构建和签名。",
    "tags": [
      "Web3",
      "Wallet",
      "Multi-chain",
      "Nonce",
      "UTXO",
      "Solana",
      "Sui"
    ],
    "readingTime": "6 min",
    "difficulty": "项目拆解",
    "kind": "engineering-note"
  },
  {
    "id": 29,
    "slug": "erc4337-useroperation-lifecycle",
    "title": "ERC-4337 工程拆解：一笔 UserOperation 如何验证、支付 Gas 并进入链上",
    "date": "2026-07-07",
    "summary": "从钱包后端视角拆解一笔 UserOperation 如何经过 nonce 分配、账户签名、Bundler 模拟、Paymaster 验证、EntryPoint 执行和 Gas 结算，并说明账户抽象为什么没有消除状态机。",
    "tags": [
      "Web3",
      "Wallet",
      "ERC-4337",
      "Account Abstraction",
      "Bundler",
      "Paymaster"
    ],
    "readingTime": "8 min",
    "difficulty": "项目拆解",
    "kind": "engineering-note"
  },
  {
    "id": 30,
    "slug": "minimal-multi-agent-coding-workflow",
    "title": "从单 Agent 到最小 Multi-Agent：我的 AI Coding 工作流进化",
    "date": "2026-07-09",
    "summary": "这篇成长日志记录我如何从让 AI 直接帮我写代码，进化到用 Planner、Worker、Reviewer 三个角色组织复杂 Coding 任务，让 AI Coding 变成有边界、有交接、有审查的工程流程。",
    "tags": [
      "AI Engineering",
      "Codex",
      "Multi-Agent",
      "Workflow",
      "Coding"
    ],
    "readingTime": "6 min",
    "difficulty": "项目拆解",
    "kind": "learning-log"
  }
]
