/* eslint-disable */
// Generated by scripts/generate-radars.mjs. Do not edit by hand.

export interface RadarItem { title: string; summary: string; sourceUrl?: string }
export interface LearningSource { tier: 'tier1' | 'tier2'; role: 'event' | 'mechanism'; kind: string; name: string; url: string; publishedAt?: string }
export interface LearningBrief { id: string; domain: 'ai' | 'web3'; topic: string; title: string; whatHappened: string; mechanism: string; workedExample: string; whyItMatters: string; risksAndLimits: string[]; sources: LearningSource[]; nextQuestions: string[] }
export interface LearningDeepDive extends LearningBrief { basedOnBriefId: string }
export interface DailyRadar { date: string; slug: string; snapshotId: string; asOf: string; origin: 'research'; publicationState: 'published'; title: string; summary: string; reviewStatus: 'automated'; generatedAt: string; sourceSections: string[]; missingSections: string[]; marketSignals: RadarItem[]; aiTip?: RadarItem; web3Design?: RadarItem; vibeProject?: RadarItem; readingPick?: RadarItem; sourceUrls: string[]; relatedProjectSlugs: string[]; schemaVersion?: 2; editionMode?: 'daily' | 'backfill'; researchedAt?: string; publish?: true; briefs?: LearningBrief[]; deepDive?: LearningDeepDive }
export interface RadarIndexItem { title: string }
export interface LearningBriefIndexItem { id: string; domain: 'ai' | 'web3'; topic: string; title: string }
export interface RadarIndexEntry { date: string; slug: string; snapshotId: string; asOf: string; title: string; summary: string; schemaVersion?: 2; editionMode?: 'daily' | 'backfill'; briefs?: LearningBriefIndexItem[]; deepDive?: { id: string; title: string; basedOnBriefId: string }; marketSignals: RadarIndexItem[]; aiTip?: RadarIndexItem; web3Design?: RadarIndexItem; vibeProject?: RadarIndexItem; readingPick?: RadarIndexItem }

export const radarIndex: RadarIndexEntry[] = [
  {
    "date": "2026-08-13",
    "slug": "2026-08-13",
    "snapshotId": "learning-2026-08-13-34d6285dd374d3b6",
    "asOf": "2026-08-13T00:02:17.000Z",
    "title": "学习雷达 · 2026-08-13",
    "summary": "AI 关注可恢复审批与推理服务可靠性；Web3 关注源码复现边界和分布式数据可用性恢复。",
    "schemaVersion": 2,
    "editionMode": "daily",
    "briefs": [
      {
        "id": "ai-durable-runstate-input",
        "domain": "ai",
        "topic": "agent",
        "title": "Agents SDK 0.20：恢复任务前先恢复调用身份"
      },
      {
        "id": "ai-vllm-serving-reliability",
        "domain": "ai",
        "topic": "model_inference",
        "title": "vLLM 0.27：首请求延迟与故障恢复要分别门禁"
      },
      {
        "id": "web3-sui-source-reproduction",
        "domain": "web3",
        "topic": "onchain_infrastructure",
        "title": "Sui testnet 1.77.2：源码验证要绑定发布工具链"
      },
      {
        "id": "web3-rowdas-reconstruction",
        "domain": "web3",
        "topic": "protocol",
        "title": "EIP-8371：把 Blob 重建从超级节点摊到行子网"
      }
    ],
    "deepDive": {
      "id": "deep-ai-durable-approval-state",
      "title": "专题：可恢复审批必须绑定状态、调用与副作用",
      "basedOnBriefId": "ai-durable-runstate-input"
    },
    "marketSignals": []
  },
  {
    "date": "2026-08-12",
    "slug": "2026-08-12",
    "snapshotId": "learning-2026-08-12-802ca3adfabc99c8",
    "asOf": "2026-08-12T05:27:51.000Z",
    "title": "学习雷达 · 2026-08-12",
    "summary": "AI 关注生成器—评估器闭环与长任务使用边界；Web3 关注隐私资产执行路径和账户认证协议。",
    "schemaVersion": 2,
    "editionMode": "backfill",
    "briefs": [
      {
        "id": "ai-generator-evaluator-loop",
        "domain": "ai",
        "topic": "agent",
        "title": "长任务 Harness：生成器与评估器要分工"
      },
      {
        "id": "ai-long-horizon-adoption",
        "domain": "ai",
        "topic": "data",
        "title": "Agent 使用研究：任务时长只是方向性估计"
      },
      {
        "id": "web3-zcash-execution-boundary",
        "domain": "web3",
        "topic": "wallet_cex",
        "title": "Ledger Live 4.15：隐私资产路径要单独门禁"
      },
      {
        "id": "web3-canonical-authenticator",
        "domain": "web3",
        "topic": "protocol",
        "title": "EIP-8130：把账户认证从任意代码中拆出"
      }
    ],
    "deepDive": {
      "id": "deep-web3-eip8130-auth",
      "title": "专题：从认证器到会话权限的完整状态机",
      "basedOnBriefId": "web3-canonical-authenticator"
    },
    "marketSignals": []
  },
  {
    "date": "2026-08-11",
    "slug": "2026-08-11",
    "snapshotId": "learning-2026-08-11-1b2e89b6a2014ce0",
    "asOf": "2026-08-12T05:27:51.000Z",
    "title": "学习雷达 · 2026-08-11",
    "summary": "AI 关注可恢复 Agent 与评测失效；Web3 关注机密代币可观测性和 Lightning 迁移边界。",
    "schemaVersion": 2,
    "editionMode": "backfill",
    "briefs": [
      {
        "id": "ai-managed-agent-boundaries",
        "domain": "ai",
        "topic": "agent",
        "title": "Managed Agents：把大脑、双手与会话拆开"
      },
      {
        "id": "ai-evaluation-signal-decay",
        "domain": "ai",
        "topic": "evaluation",
        "title": "AI-resistant Eval：旧考题会失去区分能力"
      },
      {
        "id": "web3-confidential-token-observability",
        "domain": "web3",
        "topic": "onchain_infrastructure",
        "title": "Agave 4.2：机密代币意图进入节点可观测面"
      },
      {
        "id": "web3-lightning-migration-recovery",
        "domain": "web3",
        "topic": "l2",
        "title": "lnd 0.21.2 RC：迁移失败必须可恢复"
      }
    ],
    "deepDive": {
      "id": "deep-ai-recoverable-agents",
      "title": "专题：可恢复 Agent 的最小结构",
      "basedOnBriefId": "ai-managed-agent-boundaries"
    },
    "marketSignals": []
  },
  {
    "date": "2026-08-10",
    "slug": "2026-08-10",
    "snapshotId": "learning-2026-08-10-2e30ddbe6dfe7ed5",
    "asOf": "2026-08-12T05:27:51.000Z",
    "title": "学习雷达 · 2026-08-10",
    "summary": "AI 关注实时推理关键路径与可证据化改进闭环；Web3 关注签名降级防线与清晰签名上下文。",
    "schemaVersion": 2,
    "editionMode": "backfill",
    "briefs": [
      {
        "id": "ai-realtime-critical-path",
        "domain": "ai",
        "topic": "model_inference",
        "title": "实时语音 AI：先保护连续媒体关键路径"
      },
      {
        "id": "ai-evidence-improvement-loop",
        "domain": "ai",
        "topic": "evaluation",
        "title": "Agent 改进闭环：先把专家纠错变成证据"
      },
      {
        "id": "web3-signature-fail-closed",
        "domain": "web3",
        "topic": "security",
        "title": "OpenZeppelin 5.7：签名与权限不能静默降级"
      },
      {
        "id": "web3-clear-signing-context",
        "domain": "web3",
        "topic": "wallet_cex",
        "title": "ERC-7730：清晰签名必须绑定链与合约上下文"
      }
    ],
    "deepDive": {
      "id": "deep-ai-realtime-architecture",
      "title": "专题：把实时 AI 拆成快路径、异步工作与可恢复状态",
      "basedOnBriefId": "ai-realtime-critical-path"
    },
    "marketSignals": []
  },
  {
    "date": "2026-08-09",
    "slug": "2026-08-09",
    "snapshotId": "learning-2026-08-09-3eb942f463c3d8ab",
    "asOf": "2026-08-09T03:36:30.000Z",
    "title": "每日研究雷达 · 2026-08-09",
    "summary": "聚焦 lnd 迁移修复、专家纠错 Eval、清晰签名、Qwen Code 与多 Agent 研究边界。",
    "marketSignals": [
      {
        "title": "lnd 0.21.2-beta.rc1 修补迁移失败与图同步内存边界"
      }
    ],
    "aiTip": {
      "title": "把专家纠错沉淀成定向 Eval，再给 Agent 有边界的修复任务"
    },
    "web3Design": {
      "title": "签名前把调用数据翻译为与链和合约绑定的人类意图"
    },
    "vibeProject": {
      "title": "Qwen Code 0.21.8 · 并行提速前先封住信任继承"
    },
    "readingPick": {
      "title": "How we built our multi-agent research system"
    }
  },
  {
    "date": "2026-08-08",
    "slug": "2026-08-08",
    "snapshotId": "learning-2026-08-08-78d9ba3a970af50b",
    "asOf": "2026-08-09T03:36:00.000Z",
    "title": "每日研究雷达 · 2026-08-08",
    "summary": "聚焦 Algorand 后量子账户预览、长任务 Agent 闭环、跨链地址、Spec Kit 与 Agent 工作研究。",
    "marketSignals": [
      {
        "title": "Algorand BetaNet 5.0.0 预演 Falcon-1024 后量子账户"
      }
    ],
    "aiTip": {
      "title": "让长任务 Agent 在生成、评估和上下文重置之间形成闭环"
    },
    "web3Design": {
      "title": "跨链地址必须把链语境与账户字节绑定成同一对象"
    },
    "vibeProject": {
      "title": "GitHub Spec Kit 0.16.1 · 把 Agent 开发交接变成可审阅规格"
    },
    "readingPick": {
      "title": "How agents are transforming work"
    }
  },
  {
    "date": "2026-08-07",
    "slug": "2026-08-07",
    "snapshotId": "learning-2026-08-07-6473e0cf19c707ff",
    "asOf": "2026-08-06T23:04:03.000Z",
    "title": "每日研究雷达 · 2026-08-07",
    "summary": "聚焦 Nethermind ABI 内存硬化、viem EIP-712 类型校验、欧盟加密服务治理限制、评测资源噪声、P-256 钱包授权分层、Pi，以及 agentic AI 科研软件验证。",
    "marketSignals": [
      {
        "title": "Nethermind 1.39.3 封住畸形 ABI 输入的超大内存分配路径"
      },
      {
        "title": "viem 2.55.11 拒绝 EIP-712 裸写 uint 与 int"
      },
      {
        "title": "欧盟扩展加密资产服务实体的治理控制限制"
      }
    ],
    "aiTip": {
      "title": "把评测容器的资源保证值与硬终止上限分开校准"
    },
    "web3Design": {
      "title": "把 P-256 硬件密钥接入拆成链能力、验签与账户授权三层"
    },
    "vibeProject": {
      "title": "Pi · 可组合的 coding agent 最小运行时"
    },
    "readingPick": {
      "title": "Scientific computing in the age of agentic AI"
    }
  },
  {
    "date": "2026-08-06",
    "slug": "2026-08-06",
    "snapshotId": "learning-2026-08-06-64d6b12d27f6b9af",
    "asOf": "2026-08-05T23:04:21.000Z",
    "title": "每日研究雷达 · 2026-08-06",
    "summary": "聚焦 Safe Guard 防误配、合约注册表控制面、Foundry Upgrades 编译器门槛、程序化工具调用、原生密钥迁移、OpenCode，以及数据湖在线点查。",
    "marketSignals": [
      {
        "title": "Safe Wallet 为旧版 Safe 的 Guard 配置增加客户端检查"
      },
      {
        "title": "Parity Contract Dependency Manager 明确注册表控制面"
      },
      {
        "title": "OpenZeppelin Foundry Upgrades 补丁版提高 Solidity 下限"
      }
    ],
    "aiTip": {
      "title": "只把可判定的数据归并交给程序化工具调用"
    },
    "web3Design": {
      "title": "把签名算法迁移建模为不可逆控制权切换"
    },
    "vibeProject": {
      "title": "OpenCode · 多端可扩展 coding agent 运行时"
    },
    "readingPick": {
      "title": "Indexing the Data Lake for Online Point Queries"
    }
  },
  {
    "date": "2026-08-05",
    "slug": "2026-08-05",
    "snapshotId": "learning-2026-08-05-d358b752f1b6123a",
    "asOf": "2026-08-04T23:03:11.000Z",
    "title": "每日研究雷达 · 2026-08-05",
    "summary": "聚焦 Solana 分阶段升级、Sui 可复现构建、NEAR 出站缓冲隔离、agent 轨迹分级、EOA 代码委托、Crush，以及可审计的 agent harness。",
    "marketSignals": [
      {
        "title": "Solana Agave 4.2 将多项主网变化拆成 feature gate"
      },
      {
        "title": "Sui testnet v1.77.1 收紧源码复现的工具链与依赖身份"
      },
      {
        "title": "NEAR 2.13.3 用分层出站缓冲限制隔离慢连接"
      }
    ],
    "aiTip": {
      "title": "把结果正确与工具过程合规分开评分"
    },
    "web3Design": {
      "title": "把 EOA 代码委托视为持续存在的账户迁移"
    },
    "vibeProject": {
      "title": "Crush · 可切换模型与权限审阅的终端 coding agent"
    },
    "readingPick": {
      "title": "The harness is all you need (mostly)"
    }
  },
  {
    "date": "2026-08-04",
    "slug": "2026-08-04",
    "snapshotId": "learning-2026-08-04-61ca80e6c9a8f1a2",
    "asOf": "2026-08-04T01:46:53.000Z",
    "title": "每日研究雷达 · 2026-08-04",
    "summary": "聚焦 Chainlink 遥测与批处理、Polkadot collator 信誉修复、Celestia CheckTx 限制、受限 agent 写入、沙箱钱包、Gemini CLI，以及条件化最小权限。",
    "marketSignals": [
      {
        "title": "Chainlink Node v2.58.0 调整遥测与批量发送默认值"
      },
      {
        "title": "Polkadot SDK 补丁修正 collator 信誉归因"
      },
      {
        "title": "Celestia Corto 版本在 CheckTx 限制消息数量"
      }
    ],
    "aiTip": {
      "title": "让模型产出结构化意图，由确定性 handler 执行写入"
    },
    "web3Design": {
      "title": "把 agent 资产与 owner 账户做单向隔离"
    },
    "vibeProject": {
      "title": "Gemini CLI · 终端开源 coding agent"
    },
    "readingPick": {
      "title": "用条件把最小权限收紧到服务、工具与时间"
    }
  },
  {
    "date": "2026-08-03",
    "slug": "2026-08-03",
    "snapshotId": "learning-2026-08-03-fc539b3a312b293b",
    "asOf": "2026-08-03T02:14:03.000Z",
    "title": "每日研究雷达 · 2026-08-03",
    "summary": "聚焦 Coinbase 资金工作流事故、以太坊 agent 安全分诊、SEC 加密监管议程、stacked PR 迁移、模块化智能账户、Cline，以及依赖更新信噪比分流。",
    "marketSignals": [
      {
        "title": "Coinbase 共享入口故障暂停多类资金工作流"
      },
      {
        "title": "以太坊协议安全 agent 的瓶颈是可复现分诊"
      },
      {
        "title": "SEC 议程覆盖加密融资、托管与链上代币化证券"
      }
    ],
    "aiTip": {
      "title": "把大型迁移拆成有依赖关系的短会话与小 PR 栈"
    },
    "web3Design": {
      "title": "把账户验证、执行与约束拆成可清点模块"
    },
    "vibeProject": {
      "title": "Cline · 多客户端开源 coding agent"
    },
    "readingPick": {
      "title": "分组普通依赖更新，同时保留安全修复快车道"
    }
  },
  {
    "date": "2026-08-02",
    "slug": "2026-08-02",
    "snapshotId": "learning-2026-08-02-71a3c80853f45e57",
    "asOf": "2026-08-01T23:04:00.000Z",
    "title": "每日研究雷达 · 2026-08-02",
    "summary": "聚焦以太坊客户端安全升级与 RPC 边界、Avalanche Helicon 测试网窗口、低成本原型比较、无地址签名者表示、Agent 会话审计，以及 Spotify 队列事故复盘。",
    "marketSignals": [
      {
        "title": "Lighthouse v8.2.1 要求主网节点优先升级"
      },
      {
        "title": "Nethermind 1.39.2 同时改变安全与日志查询边界"
      },
      {
        "title": "Avalanche Helicon 仅在 Fuji 提供升级验证窗口"
      }
    ],
    "aiTip": {
      "title": "实现前并排比较多个低成本原型"
    },
    "web3Design": {
      "title": "用验证器与公钥材料表示没有链上地址的签名者"
    },
    "vibeProject": {
      "title": "Entire CLI · 把 Agent 会话检查点纳入 Git 审阅"
    },
    "readingPick": {
      "title": "Spotify 视频播客摄取事故复盘"
    }
  },
  {
    "date": "2026-08-01",
    "slug": "2026-08-01",
    "snapshotId": "learning-2026-08-01-bc458e68175f1a4c",
    "asOf": "2026-08-03T02:08:54.000Z",
    "title": "每日研究雷达 · 2026-08-01",
    "summary": "聚焦 OP Stack 交易入口与证明迁移、Cosmos 密钥升级、俄罗斯加密流通框架、agent 结果成本、可衰减钱包权限、Codex CLI，以及代码搜索热路径优化。",
    "marketSignals": [
      {
        "title": "op-reth 2.4.1 改变交易池入口与历史证明迁移边界"
      },
      {
        "title": "Cosmos SDK 0.55 把共识密钥轮换变成链级升级事项"
      },
      {
        "title": "俄罗斯加密流通框架保留境内支付禁令"
      }
    ],
    "aiTip": {
      "title": "用可验收结果衡量 agent 单位成本"
    },
    "web3Design": {
      "title": "把自动执行权限做成可衰减、可过期的类型化授权"
    },
    "vibeProject": {
      "title": "OpenAI Codex CLI · 本地开源 coding agent"
    },
    "readingPick": {
      "title": "GitHub 代码搜索的无分支大小写折叠优化"
    }
  },
  {
    "date": "2026-07-31",
    "slug": "2026-07-31",
    "snapshotId": "learning-2026-07-31-6c250c1127f20e68",
    "asOf": "2026-07-31T03:33:25.000Z",
    "title": "每日研究雷达 · 2026-07-31",
    "summary": "聚焦 Prysm 与 Gaia 节点升级、Aptos 私有热修、Agent 评测难度梯度、交易内一次性动作证明、Lightning Wavelength，以及 AI 推动的工作任务跨界。",
    "marketSignals": [
      {
        "title": "Prysm v7.1.8 修复 attestation 传播与验证者及时签名"
      },
      {
        "title": "Gaia v27.6.0 扩大 CosmWasm 合约上限与查询能力"
      },
      {
        "title": "Aptos v1.48.5 私有热修要求验证者与全节点升级"
      }
    ],
    "aiTip": {
      "title": "把同一评测问题做成可调信息量的难度梯度"
    },
    "web3Design": {
      "title": "用交易内一次性动作证明收紧 Agent 授权"
    },
    "vibeProject": {
      "title": "Wavelength · 自托管 Bitcoin 与 Lightning 统一开发栈"
    },
    "readingPick": {
      "title": "How AI is expanding what people do at work"
    }
  },
  {
    "date": "2026-07-30",
    "slug": "2026-07-30",
    "snapshotId": "learning-2026-07-30-d870cf2123031ace",
    "asOf": "2026-07-29T23:03:23.000Z",
    "title": "每日研究雷达 · 2026-07-30",
    "summary": "聚焦 Erigon RPC 内存泄漏修复、Sui 索引与分叉恢复、Eclair BOLT12 风险收敛、Agent 评测出网负向测试、授权快照根设计，以及编码 Agent 沙箱 nono。",
    "marketSignals": [
      {
        "title": "Erigon 3.5.4 修复 RPC gzip 路径的原生内存泄漏"
      },
      {
        "title": "Sui mainnet v1.76.1 加入一次性 RPC 重建索引"
      },
      {
        "title": "Eclair 0.14.1 撤回 BOLT12 blinded path 费用折扣"
      }
    ],
    "aiTip": {
      "title": "把 Agent 评测环境的禁止出网做成负向测试"
    },
    "web3Design": {
      "title": "用有时效的授权快照根固定签名策略状态"
    },
    "vibeProject": {
      "title": "nono · 编码 Agent 的进程级权限沙箱"
    }
  },
  {
    "date": "2026-07-29",
    "slug": "2026-07-29",
    "snapshotId": "learning-2026-07-29-2c4dcf92f5a7342d",
    "asOf": "2026-07-28T23:02:17.000Z",
    "title": "每日研究雷达 · 2026-07-29",
    "summary": "聚焦 Besu 安全升级与 RPC 边界、Zcash Ironwood 激活、MiCA 人员能力责任、Agent 委派收益门、智能账户调用准备协议、Sandbox Agent，以及一次前沿实验室 Agent 入侵复盘。",
    "marketSignals": [
      {
        "title": "Besu 26.7.1 修复安全漏洞并改变 RPC 资源边界"
      },
      {
        "title": "Zcash Ironwood 已越过主网激活高度"
      },
      {
        "title": "ESMA 的 MiCA 人员能力指引开始适用"
      }
    ],
    "aiTip": {
      "title": "为 Agent 编排加入可审计的委派收益门"
    },
    "web3Design": {
      "title": "把智能账户差异收敛到准备、签名与提交协议"
    },
    "vibeProject": {
      "title": "Sandbox Agent · 编码 Agent 的统一隔离运行接口"
    },
    "readingPick": {
      "title": "Anatomy of a Frontier Lab Agent Intrusion"
    }
  },
  {
    "date": "2026-07-28",
    "slug": "2026-07-28",
    "snapshotId": "learning-2026-07-28-90554d0bcd1f8825",
    "asOf": "2026-07-27T23:03:30.000Z",
    "title": "每日研究雷达 · 2026-07-28",
    "summary": "聚焦 Geth 新节点资源基线、Cosmos SDK 状态破坏型安全升级、加纳支付许可警示、Agent 证据收窄协议、账户认证迁移、agent-browser，以及可验证的 AI 编程闭环。",
    "marketSignals": [
      {
        "title": "Geth 1.17.5 改变新节点内存与数据库默认值"
      },
      {
        "title": "Cosmos SDK 0.53.8 安全修复需要链级协调升级"
      },
      {
        "title": "加纳央行警示 Freedom Coin 未获银行与支付许可"
      }
    ],
    "aiTip": {
      "title": "把 Agent 工具说明写成从差异到裁决的证据收窄协议"
    },
    "web3Design": {
      "title": "让签名有效性随账户当前认证状态失效"
    },
    "vibeProject": {
      "title": "agent-browser · 面向编码 Agent 的受控浏览器自动化"
    },
    "readingPick": {
      "title": "The harness is all you need (mostly)"
    }
  },
  {
    "date": "2026-07-27",
    "slug": "2026-07-27",
    "snapshotId": "learning-2026-07-27-b2cf31122a291e9d",
    "asOf": "2026-07-26T23:04:00.000Z",
    "title": "每日研究雷达 · 2026-07-27",
    "summary": "聚焦 Zilliqa 链特定硬件签名泄露、Zebra 日志与 reorg 一致性修复、Solana 资源费提案、编码评测质检、Agent 隔离子钱包、VibeTunnel 远程终端，以及症状评估代理的证据链。",
    "marketSignals": [
      {
        "title": "Zilliqa 暂停旧版非 EVM 网络交易以处置 Ledger 应用签名泄露"
      },
      {
        "title": "Zebra 6.2.2 修补日志安全与 reorg 期间的 RPC 读一致性"
      },
      {
        "title": "Solana 接受资源费提案但尚无主网激活 epoch"
      }
    ],
    "aiTip": {
      "title": "先质检评测任务的一致性，再比较 Agent 分数"
    },
    "web3Design": {
      "title": "用单向所有权的隔离子钱包限制自动化 Agent 的资产爆炸半径"
    },
    "vibeProject": {
      "title": "VibeTunnel · 在浏览器中观察和接管真实终端会话"
    },
    "readingPick": {
      "title": "SymptomAI 如何评估日常症状对话中的追问策略"
    }
  },
  {
    "date": "2026-07-26",
    "slug": "2026-07-26",
    "snapshotId": "learning-2026-07-26-be60ca9c671cb093",
    "asOf": "2026-07-25T23:02:22.000Z",
    "title": "每日研究雷达 · 2026-07-26",
    "summary": "聚焦 Triple-A 多链热钱包异常流出、欧盟对俄制裁中的加密服务限制、Core Lightning 通道校验、新鲜度探针、可组合交易、Coder 远程开发环境，以及量子纠错的在线学习闭环。",
    "marketSignals": [
      {
        "title": "Triple-A 多链热钱包出现约 970 万美元疑似异常流出"
      },
      {
        "title": "欧盟扩展对俄制裁中的加密服务限制"
      },
      {
        "title": "Core Lightning 拒绝复用既有资金输出点的通道"
      }
    ],
    "aiTip": {
      "title": "给检索上下文设置新鲜度门槛与只读实时探针"
    },
    "web3Design": {
      "title": "把交易操作、签名角色与费用赞助拆成独立可签组件"
    },
    "vibeProject": {
      "title": "Coder · 自托管远程开发环境与编码 Agent 基础设施"
    },
    "readingPick": {
      "title": "Towards a quantum computer that learns from its errors"
    }
  },
  {
    "date": "2026-07-25",
    "slug": "2026-07-25",
    "snapshotId": "learning-2026-07-25-0a04e198ae39064b",
    "asOf": "2026-07-24T23:04:00.000Z",
    "title": "每日研究雷达 · 2026-07-25",
    "summary": "聚焦 Cardano Wallet 密钥存储升级、Stacks 主网升级窗口、Elastos 主链恢复、可执行架构约束、不可信解码器隔离、GitHub Agentic Workflows，以及 Dependabot 依赖冷却期。",
    "marketSignals": [
      {
        "title": "Cardano Wallet 升级根密钥存储并收紧随机源"
      },
      {
        "title": "Stacks 的 Bitcoin Staking 投票通过并进入主网激活窗口"
      },
      {
        "title": "Elastos 主链因共识级价值溢出问题暂停并准备协调回滚"
      }
    ],
    "aiTip": {
      "title": "把架构评审意见升级为带修复指令的可执行约束"
    },
    "web3Design": {
      "title": "把不可信载荷解码与可信身份验证拆成两个故障域"
    },
    "vibeProject": {
      "title": "GitHub Agentic Workflows · 可版本化的 Agent 工作流编译与安全边界"
    },
    "readingPick": {
      "title": "The case for a cooldown: Why Dependabot now waits before issuing version updates"
    }
  },
  {
    "date": "2026-07-24",
    "slug": "2026-07-24",
    "snapshotId": "learning-2026-07-24-eee4cd123bc3d11d",
    "asOf": "2026-07-23T23:05:00.000Z",
    "title": "每日研究雷达 · 2026-07-24",
    "summary": "聚焦第三方托管桥风险、俄罗斯加密资产流通规则、高管社交账号劫持、Agent 结果与轨迹双重评测、并发 nonce 域，以及本地代码图谱与 AI 时代的变更定价。",
    "marketSignals": [
      {
        "title": "AFX 自营 USDC 托管桥遭利用"
      },
      {
        "title": "俄罗斯拟将加密货币持有、交易与跨境结算纳入许可体系"
      },
      {
        "title": "Robinhood CEO 的 X 账号被劫持并推广假迷因币"
      }
    ],
    "aiTip": {
      "title": "把 Agent 评测拆成结果状态与执行轨迹两套断言"
    },
    "web3Design": {
      "title": "用显式 nonce 域解除同一账户下无关操作的全局串行"
    },
    "vibeProject": {
      "title": "GitNexus · 本地代码知识图谱与 Agent 影响分析"
    },
    "readingPick": {
      "title": "The cost of saying yes has changed"
    }
  },
  {
    "date": "2026-07-23",
    "slug": "2026-07-23",
    "snapshotId": "learning-2026-07-23-6cbe41340fdd54b4",
    "asOf": "2026-07-22T23:02:51.000Z",
    "title": "每日研究雷达 · 2026-07-23",
    "summary": "聚焦共识客户端安全升级、故障证明进程治理、测试网协议变更、Agent PR 风险路由、不可逆密钥迁移，以及本地任务规格管理。",
    "marketSignals": [
      {
        "title": "Lighthouse v8.2.1 将主网信标节点升级列为高优先级安全事项"
      },
      {
        "title": "op-challenger v1.9.4 收束超时后的 VM 进程残留"
      },
      {
        "title": "Avalanche Helicon 在 Fuji 排定六项协议变更"
      }
    ],
    "aiTip": {
      "title": "用多信号置信度路由 Agent PR"
    },
    "web3Design": {
      "title": "把不可逆签名算法迁移建模为独立密钥状态机"
    },
    "vibeProject": {
      "title": "Backlog.md · 仓库内的 Agent 任务规格与审阅工作流"
    },
    "readingPick": {
      "title": "Towards demystifying the creativity of diffusion models"
    }
  },
  {
    "date": "2026-07-22",
    "slug": "2026-07-22",
    "snapshotId": "learning-2026-07-22-d1fe7a2763b1f1a3",
    "asOf": "2026-07-21T23:03:47.000Z",
    "title": "每日研究雷达 · 2026-07-22",
    "summary": "聚焦资金基础设施恢复隔离、跨链池安全事件、可验证提示词构建、Agent 签名策略，以及多 Agent 工作树隔离。",
    "marketSignals": [
      {
        "title": "Coinbase 网关配置冲突暴露恢复路径的循环依赖"
      },
      {
        "title": "Aptos 测试网要求采用未公开源码的私有热修复"
      },
      {
        "title": "Allbridge Core 事件凸显跨链稳定币池定价风险"
      }
    ],
    "aiTip": {
      "title": "把生产提示词编译成可验证的不可变产物"
    },
    "web3Design": {
      "title": "用策略哈希把 Agent 签名权收敛为可撤销额度"
    },
    "vibeProject": {
      "title": "Claude Squad · 用 worktree 隔离多个终端编码 Agent"
    }
  },
  {
    "date": "2026-07-21",
    "slug": "2026-07-21",
    "snapshotId": "learning-2026-07-21-f4d1015c43de46ba",
    "asOf": "2026-07-20T23:03:40.000Z",
    "title": "每日研究雷达 · 2026-07-21",
    "summary": "聚焦协议升级与监管核验、Agent 凭证绑定的出网代理、钱包调用准备协议，以及可验证的 AI 工具用量治理。",
    "marketSignals": [
      {
        "title": "NEAR 协议版本 86 进入升级投票窗口"
      },
      {
        "title": "Sui devnet 为有网络认证结果的分叉增加自动恢复"
      },
      {
        "title": "MiCA 过渡期结束后中央登记成为公开核验入口"
      }
    ],
    "aiTip": {
      "title": "把 Agent 出网白名单改造成凭证绑定的能力代理"
    },
    "web3Design": {
      "title": "用 prepare → sign → submit 隔离账户编码与签名执行"
    },
    "vibeProject": {
      "title": "OpenUsage · 多种 AI 编码工具的本地用量仪表盘"
    },
    "readingPick": {
      "title": "AI Mania Is Eviscerating Global Decision-Making"
    }
  },
  {
    "date": "2026-07-20",
    "slug": "2026-07-20",
    "snapshotId": "learning-2026-07-20-341250f6eca21a59",
    "asOf": "2026-07-20T00:48:39.000Z",
    "title": "每日研究雷达 · 2026-07-20",
    "summary": "关注 Bitcoin 共识形式化验证与节点维护修复、以任务锚点约束 Agent 工具轨迹，以及为钱包扫描器提供最小只读内核视图。",
    "marketSignals": [
      {
        "title": "Bitcoin 协议形式化验证开始落到可运行组件"
      },
      {
        "title": "Bitcoin Core 30.3/29.4 修复链状态异常磁盘重写"
      },
      {
        "title": "LND 封堵辅助资产通道的不安全 RBF 关闭路径"
      }
    ],
    "aiTip": {
      "title": "让 Agent 从任务锚点收窄证据"
    },
    "web3Design": {
      "title": "为钱包扫描器提供最小只读内核视图"
    },
    "vibeProject": {
      "title": "Grok Build · 可检查的 Rust 编码 Agent Harness 与 TUI"
    },
    "readingPick": {
      "title": "Autoconf’s revenge: ad-hoc shell templates"
    }
  },
  {
    "date": "2026-07-19",
    "slug": "2026-07-19",
    "snapshotId": "learning-2026-07-19-6790f5d58720937a",
    "asOf": "2026-07-19T07:11:15.000Z",
    "title": "每日研究雷达 · 2026-07-19",
    "summary": "关注 MiCA 过渡期结束后的有序退出、可复现的 Agent 评测记录、可缩减的钱包执行权限，以及为 Agent API 支付设计的 HTTP 中间件。",
    "marketSignals": [
      {
        "title": "MiCA 过渡期结束后的有序退出成为运营要求"
      },
      {
        "title": "监管预期从注册状态延伸到产品退出流程"
      }
    ],
    "aiTip": {
      "title": "让每次 Agent 评测保留“主张—环境—证据”记录"
    },
    "web3Design": {
      "title": "ERC-7715 的可缩减执行权限"
    },
    "vibeProject": {
      "title": "Faremeter · 面向 HTTP 服务的机器间小额支付"
    },
    "readingPick": {
      "title": "Introducing Precursor: detecting agentic behavior with continuous client-side signals"
    }
  },
  {
    "date": "2026-07-18",
    "slug": "2026-07-18",
    "snapshotId": "learning-2026-07-18-62af3492a89ed061",
    "asOf": "2026-07-18T01:47:07.000Z",
    "title": "每日研究雷达 · 2026-07-18",
    "summary": "关注稳定币机构接入、Agent 的公开 URL 预检、策略绑定的钱包代理授权，以及团队级编码代理的可控交付。",
    "marketSignals": [
      {
        "title": "稳定币供给与现货成交量同步收缩"
      },
      {
        "title": "BNY 将 USDC 托管、铸造与赎回接入机构工作流"
      },
      {
        "title": "Standard Chartered 推出面向合格机构的 USDC 进出通道"
      }
    ],
    "aiTip": {
      "title": "以“已知公开 URL”作为 Agent 自动抓取前置条件"
    },
    "web3Design": {
      "title": "ERC-8196 将代理授权绑定为可验证策略"
    },
    "vibeProject": {
      "title": "Cursor · 团队级编码代理工作流"
    },
    "readingPick": {
      "title": "GPT-5.6: Frontier intelligence that scales with your ambition"
    }
  },
  {
    "date": "2026-07-17",
    "slug": "2026-07-17",
    "snapshotId": "learning-2026-07-17-65d2aa18f58de613",
    "asOf": "2026-07-17T01:25:53.000Z",
    "title": "每日研究雷达 · 2026-07-17",
    "summary": "聚焦 AI 安全分诊与提示注入回归测试、钱包批量调用和隐私模块化，以及链上基础设施的可复核安全边界。",
    "marketSignals": [
      {
        "title": "AI 安全研究强调可复核的漏洞分诊"
      },
      {
        "title": "Clear Signing 正走向共享安全基础设施"
      },
      {
        "title": "libp2p 公开漏洞应进入节点依赖门禁"
      }
    ],
    "aiTip": {
      "title": "将提示注入防护变成可回归的攻击用例集"
    },
    "web3Design": {
      "title": "EIP-5792 以能力协商分离应用意图与钱包实现"
    },
    "vibeProject": {
      "title": "Kohaku · 模块化的钱包隐私能力试验场"
    },
    "readingPick": {
      "title": "The next great wallet will be private"
    }
  },
  {
    "date": "2026-07-16",
    "slug": "2026-07-16",
    "snapshotId": "learning-2026-07-16-d9c71fbd8e3b9248",
    "asOf": "2026-07-16T09:22:02.000Z",
    "title": "每日研究雷达 · 2026-07-16",
    "summary": "关注美英稳定币协作与美国加密资产分类解释，把 AI 评测变成可复跑实验，并用多钱包发现机制明确签名边界。",
    "marketSignals": [
      {
        "title": "美英将跨境稳定币活动纳入联合工作项"
      },
      {
        "title": "SEC 与 CFTC 的加密资产分类解释已生效"
      },
      {
        "title": "节点软件分发是钱包基础设施的供应链风险面"
      }
    ],
    "aiTip": {
      "title": "用五次固定条件运行检查评测稳定性"
    },
    "web3Design": {
      "title": "EIP-6963 用事件循环处理多钱包发现"
    },
    "vibeProject": {
      "title": "Trust Wallet Core · 可嵌入的多链钱包底层库"
    },
    "readingPick": {
      "title": "U.S.-UK Transatlantic Taskforce for the Markets of the Future"
    }
  },
  {
    "date": "2026-07-15",
    "slug": "2026-07-15",
    "snapshotId": "learning-2026-07-15-1abdc7683bc10276",
    "asOf": "2026-07-15T02:30:00.000Z",
    "title": "每日研究雷达 · 2026-07-15",
    "summary": "关注美英稳定币监管协作、AI 判别性实验、Bitcoin PSBT 签名边界，以及给 AI 生成 SQL 增加确定性检查。",
    "marketSignals": [
      {
        "title": "实时币价统一使用可读行情入口"
      },
      {
        "title": "美英发布数字资产市场合作建议"
      },
      {
        "title": "美英继续推进稳定币监管协调"
      }
    ],
    "aiTip": {
      "title": "假设账本与判别性实验"
    },
    "web3Design": {
      "title": "Bitcoin PSBT 把签名上下文变成可校验的数据契约"
    },
    "vibeProject": {
      "title": "sqlsure · AI 生成 SQL 的确定性语义闸门"
    },
    "readingPick": {
      "title": "Fragments · July 6"
    }
  },
  {
    "date": "2026-07-14",
    "slug": "2026-07-14",
    "snapshotId": "learning-2026-07-14-329cfc365c409e51",
    "asOf": "2026-07-14T08:24:48.000Z",
    "title": "每日研究雷达 · 2026-07-14",
    "summary": "修正并交叉核验 BTC/ETH 价格快照，同时关注 CPI 波动、AI 上下文交接、Sui Object Reference 与本地编码记忆。",
    "marketSignals": [
      {
        "title": "BTC 交易所 K 线快照为 62,153.89 美元"
      },
      {
        "title": "ETH 价格已更正为约 1,765 美元"
      },
      {
        "title": "CPI 是确定的波动事件，不是方向信号"
      }
    ],
    "aiTip": {
      "title": "Context Handoff 上下文交接包"
    },
    "web3Design": {
      "title": "Sui Object Reference 把可花费状态变成认证引用"
    },
    "vibeProject": {
      "title": "Recall · 本地优先的编码会话交接记忆"
    },
    "readingPick": {
      "title": "Finally, finance's digital transformation"
    }
  },
  {
    "date": "2026-07-13",
    "slug": "2026-07-13",
    "snapshotId": "learning-2026-07-13-31cd7c63e57fd525",
    "asOf": "2026-07-13T01:15:00.000Z",
    "title": "每日研究雷达 · 2026-07-13",
    "summary": "关注地缘风险下的加密市场、反例驱动的 AI 验收、ERC-4337 多通道 nonce，以及可审计的 Agent PR 证据包。",
    "marketSignals": [
      {
        "title": "地缘风险尚未触发加密市场剧烈重定价"
      },
      {
        "title": "行业消息需要按证据等级处理"
      }
    ],
    "aiTip": {
      "title": "反例驱动验收"
    },
    "web3Design": {
      "title": "ERC-4337 的 key + sequence nonce"
    },
    "vibeProject": {
      "title": "Agent PR 证据包"
    },
    "readingPick": {
      "title": "Not Every Workflow Is An Agent"
    }
  }
]

export const latestRadars: DailyRadar[] = [
  {
    "date": "2026-08-13",
    "slug": "2026-08-13",
    "title": "学习雷达 · 2026-08-13",
    "summary": "AI 关注可恢复审批与推理服务可靠性；Web3 关注源码复现边界和分布式数据可用性恢复。",
    "publish": true,
    "reviewStatus": "automated",
    "schemaVersion": 2,
    "editionMode": "daily",
    "researchedAt": "2026-08-13T00:02:17.000Z",
    "generatedAt": "2026-08-13T00:02:17.000Z",
    "sourceSections": [
      "ai",
      "web3",
      "deepDive"
    ],
    "missingSections": [],
    "briefs": [
      {
        "id": "ai-durable-runstate-input",
        "domain": "ai",
        "topic": "agent",
        "title": "Agents SDK 0.20：恢复任务前先恢复调用身份",
        "whatHappened": "OpenAI 在 2026-08-11 发布 Agents Python SDK 0.20.0，加入可持久化待处理输入的 RunState.add_input，并修复恢复流程中工具审批、Guardrail 结果和会话状态的身份绑定；发布说明同时提示 MCP v2 会影响自定义 HTTP transport。",
        "mechanism": "暂停点被序列化为 RunState，待审批工具调用保留具体 call id；新输入先持久化并通过 Guardrail，再进入恢复后的模型调用。审批只对原调用生效，避免把旧决定套到参数相似但身份不同的新调用。",
        "workedExample": "发布 Agent 在写入前暂停，把 RunState、调用 id 与业务幂等键保存；审阅者补充来源后通过 add_input 写入修订，再只批准该次调用。进程重启后恢复同一状态，不重新生成另一条发布动作。",
        "whyItMatters": "它把长任务恢复从‘重放聊天记录’提升为可核验的状态机，适合用来审视 Hermes 接管、ResearchOps 发布和其他带外部副作用的 Agent 流程。",
        "risksAndLimits": [
          "RunState 可包含应用上下文与运行元数据，若把密钥放进 context，序列化会扩大泄露面。",
          "0.20.0 改变隐式默认模型并迁移 MCP 依赖，自定义 transport 必须先做兼容测试或显式锁定版本。"
        ],
        "sources": [
          {
            "tier": "tier1",
            "role": "event",
            "kind": "official_release",
            "name": "OpenAI Agents Python SDK v0.20.0",
            "url": "https://github.com/openai/openai-agents-python/releases/tag/v0.20.0",
            "publishedAt": "2026-08-11T03:12:14.000Z"
          }
        ],
        "nextQuestions": [
          "恢复后的审批如何同时绑定调用 id、参数摘要和业务幂等键？",
          "哪些 RunState 字段可以持久化，哪些必须在恢复时重新注入？"
        ]
      },
      {
        "id": "ai-vllm-serving-reliability",
        "domain": "ai",
        "topic": "model_inference",
        "title": "vLLM 0.27：首请求延迟与故障恢复要分别门禁",
        "whatHappened": "vLLM 在 2026-08-10 发布 0.27.0，加入 JIT 与 Triton kernel 预热、面向 DP+EP 外部负载均衡部署的简化容错框架，以及 Rust 前端的健康、终止和发现控制；同时升级到 PyTorch 2.13，属于需要重建环境的兼容变化。",
        "mechanism": "预热把首次请求前的编译成本移到就绪阶段；健康与终止控制让外部负载均衡器识别不可服务实例；容错框架处理工作节点变化。三者分别约束冷启动、路由和执行状态，不能由一个平均延迟指标替代。",
        "workedExample": "推理集群升级时先在隔离实例加载同一模型并完成 kernel 预热，再运行固定正确性与延迟样本；随后主动终止一个 worker，验证健康状态、请求改道和未完成请求的错误边界后才扩大流量。",
        "whyItMatters": "它把‘模型快不快’拆成可部署的工程问题：首请求、稳态吞吐、故障转移和依赖兼容必须分别验收，才能避免只看单次 benchmark。",
        "risksAndLimits": [
          "发布说明中的性能改善来自特定模型、硬件和 kernel，不能直接外推到现有集群。",
          "升级 PyTorch、Triton 与平台 wheel 会改变 ABI 和编译缓存，回滚必须保留完整旧环境而不只是旧配置。"
        ],
        "sources": [
          {
            "tier": "tier1",
            "role": "event",
            "kind": "official_release",
            "name": "vLLM v0.27.0 release notes",
            "url": "https://github.com/vllm-project/vllm/releases/tag/v0.27.0",
            "publishedAt": "2026-08-10T21:18:11.000Z"
          }
        ],
        "nextQuestions": [
          "推理服务的 ready 信号应等待哪些预热和正确性检查完成？",
          "怎样把首请求延迟、稳态延迟与 worker 故障恢复写成独立 SLO？"
        ]
      },
      {
        "id": "web3-sui-source-reproduction",
        "domain": "web3",
        "topic": "onchain_infrastructure",
        "title": "Sui testnet 1.77.2：源码验证要绑定发布工具链",
        "whatHappened": "Mysten Labs 在北京时间 2026-08-13 05:28 发布 Sui testnet-v1.77.2；该测试网版本让 verify-source 按合约发布时记录的工具链重建源码，从包的发布元数据读取链上地址并输出核验元数据，同时修复 fatal ingestion error 后 checkpoint broadcaster 未及时退出的问题。",
        "mechanism": "验证器不再接受调用者单独传入 package id，而是把 original id、published-at、toolchain version 与重建二进制作为同一证据链；带注释的 Git tag 依赖也解析到其实际 commit，减少标签对象与源码提交混淆。",
        "workedExample": "审计 Move 包时只向 verify-source 提交源码路径，并保存 JSON 输出中的 original id、发布位置、工具链版本和 binary path；若本地重建产物与链上元数据不一致就停止，而不是切换工具链直到通过。",
        "whyItMatters": "钱包与交易所集成链上包时需要证明‘看到的源码’与‘实际发布字节’来自同一构建语境，这个变更提供了具体的供应链核验清单。",
        "risksAndLimits": [
          "这是 testnet 版本，不代表相同命令和协议变化已经进入 Sui mainnet。",
          "自动下载历史工具链仍需要校验发布物来源；旧 Move.lock 的 tag-object SHA 不会自动改正，必须显式更新依赖。"
        ],
        "sources": [
          {
            "tier": "tier1",
            "role": "event",
            "kind": "official_release",
            "name": "Sui testnet-v1.77.2 release notes",
            "url": "https://github.com/MystenLabs/sui/releases/tag/testnet-v1.77.2",
            "publishedAt": "2026-08-12T21:28:28.000Z"
          }
        ],
        "nextQuestions": [
          "链上包发布元数据最少应固定哪些编译器、依赖与地址字段？",
          "历史工具链下载与缓存如何验证签名并支持离线复现？"
        ]
      },
      {
        "id": "web3-rowdas-reconstruction",
        "domain": "web3",
        "topic": "protocol",
        "title": "EIP-8371：把 Blob 重建从超级节点摊到行子网",
        "whatHappened": "Ethereum EIPs 仓库在 2026-08-11 更新 Draft EIP-8371，为 RowDAS 补充节点角色、分阶段重建与安全分析；提案希望在 PeerDAS 之上用行级 partial message 分摊 Blob 数据重建，而不是让每个超级节点重复完成全部恢复工作。",
        "mechanism": "节点按身份进入固定行子网；只有持有某一行至少 64 个不同且通过 KZG 验证的 cell 才承担重建。行重建者、超级节点和普通订阅节点按延迟分阶段介入，若其他路径已经补全该行则取消待执行工作。",
        "workedExample": "一个行重建者从列、行子网或 getBlobs 收齐 64 个已验证 cell 后重建对应行并广播 bitmap；若延迟窗口内已观察到该行完成，就取消本地重建，避免多个节点同时消耗 CPU。",
        "whyItMatters": "它展示了数据可用性协议如何把恢复职责、传播网络和攻击成本写成显式状态机，也能帮助理解 L2 扩容为何不仅是提高 Blob 数量。",
        "risksAndLimits": [
          "EIP-8371 仍为 Draft，wire format 与多段延迟等参数尚未最终确定，不能写成主网已启用。",
          "公开且固定的行子网分配允许攻击者磨取 node id；提案保留列主题和请求响应为权威可用性路径以限制影响。"
        ],
        "sources": [
          {
            "tier": "tier1",
            "role": "event",
            "kind": "protocol_commit",
            "name": "EIP-8371 role split and security analysis update",
            "url": "https://github.com/ethereum/EIPs/commit/b325d33d61f18c8bc9f5f2b9b9c59f8bf702141a",
            "publishedAt": "2026-08-11T01:55:30.000Z"
          },
          {
            "tier": "tier1",
            "role": "mechanism",
            "kind": "protocol_specification",
            "name": "Pinned EIP-8371 RowDAS specification",
            "url": "https://github.com/ethereum/EIPs/blob/b325d33d61f18c8bc9f5f2b9b9c59f8bf702141a/EIPS/eip-8371.md"
          }
        ],
        "nextQuestions": [
          "行子网的延迟与 bitmap 频率怎样设置才能避免恢复风暴？",
          "如何测试 node-id grinding、cell withholding 与重复重建的资源上界？"
        ]
      }
    ],
    "deepDive": {
      "id": "deep-ai-durable-approval-state",
      "domain": "ai",
      "topic": "infrastructure",
      "title": "专题：可恢复审批必须绑定状态、调用与副作用",
      "whatHappened": "Agents SDK 0.20.0 的持久输入能力与官方 HITL 文档共同给出一条完整边界：执行可在敏感工具前中断，RunState 可跨进程保存，审阅决定和补充输入再驱动同一任务恢复。",
      "mechanism": "中断项保存 agent、tool、参数和调用身份；RunState 序列化上下文、用量、工具输入与审批状态。恢复时使用原顶层 Agent 和同一状态，新增输入先经过 Guardrail；外部写动作还需要独立业务幂等键。",
      "workedExample": "消息派发器准备发送日报时先产生待审批调用并保存 RunState，不触达通道。人工检查页面与来源后补充回执要求，只批准该调用；恢复后发送器使用日期与收件人幂等键，进程再次重启也不会生成第二条消息。",
      "whyItMatters": "这能直接转成 Hermes 与 ResearchOps 的检查表：推理状态决定‘继续想什么’，调用身份决定‘允许做哪一次’，幂等键决定‘副作用最多发生一次’，三者不能混用。",
      "risksAndLimits": [
        "序列化 RunState 会持久化应用 context 和运行元数据，必须在写入前排除密钥、正文之外的敏感身份与不必要 trace 凭据。",
        "always_approve 等粘性决定会随状态恢复，若作用域过宽，旧授权可能覆盖后来出现的高风险调用。"
      ],
      "sources": [
        {
          "tier": "tier1",
          "role": "event",
          "kind": "official_release",
          "name": "OpenAI Agents Python SDK v0.20.0",
          "url": "https://github.com/openai/openai-agents-python/releases/tag/v0.20.0",
          "publishedAt": "2026-08-11T03:12:14.000Z"
        },
        {
          "tier": "tier1",
          "role": "mechanism",
          "kind": "official_documentation",
          "name": "OpenAI Agents SDK human-in-the-loop guide",
          "url": "https://openai.github.io/openai-agents-python/human_in_the_loop/"
        }
      ],
      "nextQuestions": [
        "审批记录怎样限定到一次调用，而不是整个工具的永久白名单？",
        "RunState、审计日志与业务幂等表分别应该保存哪些最小字段？"
      ],
      "basedOnBriefId": "ai-durable-runstate-input"
    },
    "sourceUrls": [
      "https://github.com/openai/openai-agents-python/releases/tag/v0.20.0",
      "https://github.com/vllm-project/vllm/releases/tag/v0.27.0",
      "https://github.com/MystenLabs/sui/releases/tag/testnet-v1.77.2",
      "https://github.com/ethereum/EIPs/commit/b325d33d61f18c8bc9f5f2b9b9c59f8bf702141a",
      "https://github.com/ethereum/EIPs/blob/b325d33d61f18c8bc9f5f2b9b9c59f8bf702141a/EIPS/eip-8371.md",
      "https://openai.github.io/openai-agents-python/human_in_the_loop/"
    ],
    "relatedProjectSlugs": [
      "wallet-core",
      "exchange-wallet-system",
      "web3-wallet-engineer-lab"
    ],
    "marketSignals": [],
    "snapshotId": "learning-2026-08-13-34d6285dd374d3b6",
    "asOf": "2026-08-13T00:02:17.000Z",
    "origin": "research",
    "publicationState": "published"
  },
  {
    "date": "2026-08-12",
    "slug": "2026-08-12",
    "title": "学习雷达 · 2026-08-12",
    "summary": "AI 关注生成器—评估器闭环与长任务使用边界；Web3 关注隐私资产执行路径和账户认证协议。",
    "publish": true,
    "reviewStatus": "automated",
    "schemaVersion": 2,
    "editionMode": "backfill",
    "researchedAt": "2026-08-12T05:27:51.000Z",
    "generatedAt": "2026-08-12T05:27:51.000Z",
    "sourceSections": [
      "ai",
      "web3",
      "deepDive"
    ],
    "missingSections": [],
    "briefs": [
      {
        "id": "ai-generator-evaluator-loop",
        "domain": "ai",
        "topic": "agent",
        "title": "长任务 Harness：生成器与评估器要分工",
        "whatHappened": "Anthropic 在 2026-03-24 公开长任务应用开发 harness 设计，说明生成器、评估器与结构化交接如何提升前端和可验证软件任务的完成质量。",
        "mechanism": "生成器负责推进实现，独立评估器按可检查标准寻找缺口；阶段结果写入结构化工件，在上下文重置后恢复目标、已完成项、失败证据和下一步。",
        "workedExample": "实现网页时，生成器提交页面后不自行宣称完成；评估器按可用性、视觉层级和浏览器错误逐项检查，把失败项写入下一轮任务，直到门禁满足或明确停止。",
        "whyItMatters": "它帮助你理解 Agent 不是一次长提示，而是角色、状态和评测组成的控制系统；同样适用于研究内容的采集—编辑—门禁链路。",
        "risksAndLimits": [
          "生成器和评估器可能共享同一盲点，角色分离不等于真正独立证据。",
          "更多循环会增加延迟与 token，必须有停止条件和失败上限。"
        ],
        "sources": [
          {
            "tier": "tier1",
            "role": "event",
            "kind": "official_engineering",
            "name": "Anthropic · Harness design for long-running application development",
            "url": "https://www.anthropic.com/engineering/harness-design-long-running-apps",
            "publishedAt": "2026-03-24T00:00:00.000Z"
          }
        ],
        "nextQuestions": [
          "什么情况下应使用独立模型评估器，什么情况下确定性测试更可靠？",
          "结构化交接最少需要保存哪些字段才能跨上下文恢复？"
        ]
      },
      {
        "id": "ai-long-horizon-adoption",
        "domain": "ai",
        "topic": "data",
        "title": "Agent 使用研究：任务时长只是方向性估计",
        "whatHappened": "OpenAI 在 2026-06-25 发布 Codex 使用研究，报告样本用户越来越多地委派长时、跨工具任务，并明确任务时长由模型根据 transcript 估计。",
        "mechanism": "研究从匿名样本中推断任务类别与人类完成时间，再观察不同时间阈值和岗位的采用变化；这些指标衡量使用模式，不直接证明生产率或输出正确性。",
        "workedExample": "一个被估计为八小时的人类任务可能由 Agent 在并行环境中更快完成，但验收仍要看可用产物、返工和失败成本，不能把估计时长直接当作节省工时。",
        "whyItMatters": "它训练你区分产品使用指标与因果结论，也提醒学习 Agent 系统时应关注验收率、返工和边界，而不是只看运行时长或 token。",
        "risksAndLimits": [
          "样本只覆盖特定用户群，且人类任务时长来自模型估计而非逐项实测。",
          "使用量增长可能来自产品可用性和组织政策，不能单独归因于能力提升。"
        ],
        "sources": [
          {
            "tier": "tier1",
            "role": "event",
            "kind": "official_research",
            "name": "OpenAI · How agents are transforming work",
            "url": "https://openai.com/index/how-agents-are-transforming-work/",
            "publishedAt": "2026-06-25T00:00:00.000Z"
          }
        ],
        "nextQuestions": [
          "如何用交付验收率与返工成本校准模型估计的人类任务时长？",
          "并行 Agent 的总计算量与真实生产率应该如何同时报告？"
        ]
      },
      {
        "id": "web3-zcash-execution-boundary",
        "domain": "web3",
        "topic": "wallet_cex",
        "title": "Ledger Live 4.15：隐私资产路径要单独门禁",
        "whatHappened": "Ledger 在 2026-08-11 发布 Live Desktop 4.15.0，将 Zcash 屏蔽转账纳入独立 coin-module，并加入功能开关、原生构造签名路径和遥测脱敏修复。",
        "mechanism": "隐私币执行不复用普通 token 路径，而由专用模块处理 PCZT 构造、硬件签名与广播；功能开关和双实现差分测试控制迁移，地址与账户标识从 RUM 中移除。",
        "workedExample": "上线前分别回放 t→t、t→z、z→t、z→z，比较旧桥与新模块的交易字节、费用和广播结果；关闭开关时必须能回到已知路径且不残留敏感遥测。",
        "whyItMatters": "它把钱包隐私、签名和发布控制放在同一个具体案例中，适合学习 coin adapter、硬件边界和敏感数据最小化。",
        "risksAndLimits": [
          "发布说明明确仍有未完成路径，不能把版本号理解为所有 Zcash 流程已齐备。",
          "遥测字段移除需要验证历史日志、第三方采集器和错误消息是否仍泄露标识。"
        ],
        "sources": [
          {
            "tier": "tier1",
            "role": "event",
            "kind": "official_release",
            "name": "Ledger Live Desktop 4.15.0",
            "url": "https://github.com/LedgerHQ/ledger-live/releases/tag/%40ledgerhq/live-desktop%404.15.0",
            "publishedAt": "2026-08-11T08:57:07.000Z"
          }
        ],
        "nextQuestions": [
          "隐私币模块的差分测试应比较哪些字节级和状态级不变量？",
          "钱包遥测如何证明地址与账户标识没有通过间接字段泄露？"
        ]
      },
      {
        "id": "web3-canonical-authenticator",
        "domain": "web3",
        "topic": "protocol",
        "title": "EIP-8130：把账户认证从任意代码中拆出",
        "whatHappened": "Ethereum EIPs 仓库在 2026-08-11 更新 EIP-8130，对齐 keystore 合约、交易有效期与精简协议边界，继续定义 canonical authenticator。",
        "mechanism": "交易显式声明受协议认可的认证器，节点可在执行任意账户代码前完成有界认证；账户策略再用 actor、scope、有效期、二维 nonce 与 epoch 管理会话权限。",
        "workedExample": "会话键只获准在一小时内调用特定合约的 transfer，交易携带 actor 与 scope；节点先验证认证器和有效期，再由账户策略检查额度，撤权时提升 epoch 使旧会话立即失效。",
        "whyItMatters": "它把账户抽象最难的认证、并发 nonce 与会话权限集中到可讨论协议中，适合训练从交易格式到钱包策略的全链路思考。",
        "risksAndLimits": [
          "该提案仍是 Draft，字段、交易类型与共识成本都可能继续变化。",
          "更复杂的 nonce、epoch 和跨链配置扩大实现与审计面积。"
        ],
        "sources": [
          {
            "tier": "tier1",
            "role": "event",
            "kind": "protocol_commit",
            "name": "EIP-8130 keystore and validity update",
            "url": "https://github.com/ethereum/EIPs/commit/054078969965674643d7cf4e22460c438d09dd07",
            "publishedAt": "2026-08-11T17:12:36.000Z"
          }
        ],
        "nextQuestions": [
          "canonical authenticator 的允许集如何升级而不破坏旧账户？",
          "二维 nonce 与 epoch 撤权在并发交易中有哪些竞态？"
        ]
      }
    ],
    "deepDive": {
      "id": "deep-web3-eip8130-auth",
      "domain": "web3",
      "topic": "protocol",
      "title": "专题：从认证器到会话权限的完整状态机",
      "whatHappened": "EIP-8130 的最新提交与规范页面把交易认证前置、账户策略读取、会话有效期、scope 和 nonce 组合成一套可验证账户认证框架。",
      "mechanism": "协议层先用 canonical authenticator 验证签名与交易外壳，账户层再读取 actor 配置并检查 scope、有效期和策略；nonce 维度允许并发，epoch 为整组会话提供快速撤权。",
      "workedExample": "用户给交易机器人创建 session actor：只允许调用 DEX A、单笔不超过 100 USDC、08:00 前有效。机器人并发发两笔不同 nonce 的交易；用户提升 epoch 后，未上链旧交易全部失效。",
      "whyItMatters": "这个状态机能把会话键从模糊的‘临时授权’变成可枚举条件，连接钱包 UI、签名服务、节点验证和链上策略四个学习层次。",
      "risksAndLimits": [
        "前端若省略 scope、额度或失效时间，协议安全性无法转化为用户可理解的授权。",
        "跨链复制 actor 配置可能造成不同链上 epoch 与 nonce 状态分叉。"
      ],
      "sources": [
        {
          "tier": "tier1",
          "role": "event",
          "kind": "protocol_commit",
          "name": "EIP-8130 keystore and validity update",
          "url": "https://github.com/ethereum/EIPs/commit/054078969965674643d7cf4e22460c438d09dd07",
          "publishedAt": "2026-08-11T17:12:36.000Z"
        },
        {
          "tier": "tier1",
          "role": "mechanism",
          "kind": "protocol_specification",
          "name": "EIP-8130 canonical transaction authentication",
          "url": "https://eips.ethereum.org/EIPS/eip-8130"
        }
      ],
      "nextQuestions": [
        "钱包确认页如何把 actor、scope、额度、有效期和撤权入口压缩成可理解交互？",
        "需要哪些属性测试覆盖过期、撤权、重放、并发 nonce 和错误 scope？"
      ],
      "basedOnBriefId": "web3-canonical-authenticator"
    },
    "sourceUrls": [
      "https://www.anthropic.com/engineering/harness-design-long-running-apps",
      "https://openai.com/index/how-agents-are-transforming-work/",
      "https://github.com/LedgerHQ/ledger-live/releases/tag/%40ledgerhq/live-desktop%404.15.0",
      "https://github.com/ethereum/EIPs/commit/054078969965674643d7cf4e22460c438d09dd07",
      "https://eips.ethereum.org/EIPS/eip-8130"
    ],
    "relatedProjectSlugs": [
      "wallet-core",
      "exchange-wallet-system",
      "web3-wallet-engineer-lab"
    ],
    "marketSignals": [],
    "snapshotId": "learning-2026-08-12-802ca3adfabc99c8",
    "asOf": "2026-08-12T05:27:51.000Z",
    "origin": "research",
    "publicationState": "published"
  },
  {
    "date": "2026-08-11",
    "slug": "2026-08-11",
    "title": "学习雷达 · 2026-08-11",
    "summary": "AI 关注可恢复 Agent 与评测失效；Web3 关注机密代币可观测性和 Lightning 迁移边界。",
    "publish": true,
    "reviewStatus": "automated",
    "schemaVersion": 2,
    "editionMode": "backfill",
    "researchedAt": "2026-08-12T05:27:51.000Z",
    "generatedAt": "2026-08-12T05:27:51.000Z",
    "sourceSections": [
      "ai",
      "web3",
      "deepDive"
    ],
    "missingSections": [],
    "briefs": [
      {
        "id": "ai-managed-agent-boundaries",
        "domain": "ai",
        "topic": "agent",
        "title": "Managed Agents：把大脑、双手与会话拆开",
        "whatHappened": "Anthropic 在 2026-04-08 公开 Managed Agents 架构，说明长任务如何把持久 session、可替换 harness 与按需 sandbox 分成独立接口。",
        "mechanism": "事件先追加到外部 session 日志；harness 只负责模型循环和工具路由，崩溃后用 sessionId 恢复；sandbox 作为 execute 工具按需创建，凭据留在初始化器或外部 vault。",
        "workedExample": "代码 Agent 修改仓库时，初始化器用短期 token 完成 clone 并配置 remote，生成代码所在沙箱只能执行 git 命令但读不到 token；harness 崩溃后从最后事件继续。",
        "whyItMatters": "它把 Agent 可靠性与安全从提示词问题变成结构问题，适合用来学习会话持久化、工具权限、故障恢复和凭据隔离。",
        "risksAndLimits": [
          "Managed Agents 仍处于 beta，接口、数据保留和功能可用性可能变化。",
          "持久会话提高可恢复性，也扩大数据保留与删除治理责任。"
        ],
        "sources": [
          {
            "tier": "tier1",
            "role": "event",
            "kind": "official_engineering",
            "name": "Anthropic · Scaling Managed Agents",
            "url": "https://www.anthropic.com/engineering/managed-agents",
            "publishedAt": "2026-04-08T00:00:00.000Z"
          }
        ],
        "nextQuestions": [
          "session 日志中哪些事件必须不可变，哪些可以压缩或派生？",
          "如何证明沙箱中的生成代码永远无法读取长期凭据？"
        ]
      },
      {
        "id": "ai-evaluation-signal-decay",
        "domain": "ai",
        "topic": "evaluation",
        "title": "AI-resistant Eval：旧考题会失去区分能力",
        "whatHappened": "Anthropic 在 2026-01-21 复盘三轮性能工程作业：模型逐步追平固定时限内的优秀候选人，迫使团队重建题目与评分信号。",
        "mechanism": "评测不是固定题库，而是对目标能力的测量仪器；模型能力、推理预算或训练暴露改变后，必须重新检查分数分布、作弊路径和人与模型的区分度。",
        "workedExample": "当模型在旧优化题上达到通过线，团队不只提高分数门槛，而是换成多个陌生且受约束的小问题，并把理解、调试工具和跨题稳定性重新纳入信号。",
        "whyItMatters": "学习雷达未来若用模型评估内容，也要监控门禁是否仍能区分真实机制研究与流畅复述，不能迷信一次建立的测试集。",
        "risksAndLimits": [
          "招聘作业样本不能代表所有 Agent 任务或真实软件工程绩效。",
          "为了难倒模型而过度偏离真实工作，会降低评测的岗位相关性。"
        ],
        "sources": [
          {
            "tier": "tier1",
            "role": "event",
            "kind": "official_engineering",
            "name": "Anthropic · Designing AI-resistant technical evaluations",
            "url": "https://www.anthropic.com/engineering/AI-resistant-technical-evaluations",
            "publishedAt": "2026-01-21T00:00:00.000Z"
          }
        ],
        "nextQuestions": [
          "如何检测学习雷达内容门禁已经被新模型轻易游戏化？",
          "哪些隐藏评测能保持新鲜，同时又有稳定的人工基准？"
        ]
      },
      {
        "id": "web3-confidential-token-observability",
        "domain": "web3",
        "topic": "onchain_infrastructure",
        "title": "Agave 4.2：机密代币意图进入节点可观测面",
        "whatHappened": "Anza 在 2026-08-07 发布 Agave 4.2.0，加入 Token-2022 PermissionedBurn、ConfidentialBurn 与 Batch 指令解析，并调整增量快照默认间隔。",
        "mechanism": "节点和解析器识别新的机密代币指令形状，使索引器能记录操作类型与状态变化；但隐私字段仍受协议约束，解析意图不等于解密资产细节。",
        "workedExample": "索引器遇到 ConfidentialBurn 时可以标记燃烧流程并关联交易状态，而不是把未知指令丢进 generic bucket；升级前需回放旧账本和新指令混合数据。",
        "whyItMatters": "钱包、交易所和风控系统依赖节点解析结果；理解协议升级如何改变可观测面，有助于避免把‘无法解析’误判为‘没有发生’。",
        "risksAndLimits": [
          "稳定版本标签不等于你的插件、索引器和快照组合已经兼容。",
          "增加解析能力不能突破机密交易设计本身的隐私边界。"
        ],
        "sources": [
          {
            "tier": "tier1",
            "role": "event",
            "kind": "official_release",
            "name": "Anza Agave v4.2.0",
            "url": "https://github.com/anza-xyz/agave/releases/tag/v4.2.0",
            "publishedAt": "2026-08-07T20:29:04.000Z"
          }
        ],
        "nextQuestions": [
          "新解析器对历史账本回放和索引 schema 有哪些兼容性要求？",
          "钱包可以展示哪些机密代币意图，而不泄露受保护信息？"
        ]
      },
      {
        "id": "web3-lightning-migration-recovery",
        "domain": "web3",
        "topic": "l2",
        "title": "lnd 0.21.2 RC：迁移失败必须可恢复",
        "whatHappened": "Lightning Labs 在 2026-08-08 发布 lnd 0.21.2-beta.rc1，修复历史支付迁移启动失败、缺失版本键处理和通道图同步内存增长。",
        "mechanism": "节点启动时按版本键执行数据库迁移；修复让缺失或部分状态不再把节点困在不可启动状态，同时约束图同步数据结构的增长。",
        "workedExample": "升级前复制 channel.db，在离线节点执行迁移并重启两次，确认版本键稳定、历史支付可读且图同步内存不持续增长，再决定是否进入更高环境。",
        "whyItMatters": "Lightning 节点承载真实通道状态，迁移错误与普通应用回滚不同；学习恢复顺序能建立对不可逆状态和候选版本边界的直觉。",
        "risksAndLimits": [
          "这是 release candidate，不应因修复描述充分就直接替换生产稳定版本。",
          "数据库备份必须与节点停机点一致，复制运行中的文件可能得到不一致快照。"
        ],
        "sources": [
          {
            "tier": "tier1",
            "role": "event",
            "kind": "official_release",
            "name": "lnd v0.21.2-beta.rc1",
            "url": "https://github.com/lightningnetwork/lnd/releases/tag/v0.21.2-beta.rc1",
            "publishedAt": "2026-08-08T22:12:50.000Z"
          }
        ],
        "nextQuestions": [
          "Lightning 节点数据库迁移需要哪些停机、备份与回滚证据？",
          "如何用长期指标区分图同步峰值与真正的内存泄漏？"
        ]
      }
    ],
    "deepDive": {
      "id": "deep-ai-recoverable-agents",
      "domain": "ai",
      "topic": "infrastructure",
      "title": "专题：可恢复 Agent 的最小结构",
      "whatHappened": "Managed Agents 的公开架构与产品文档共同给出一个可操作模型：Agent 定义、执行环境、session 和事件彼此独立，长任务通过持久事件恢复。",
      "mechanism": "不可变事件日志保存事实顺序，stateless harness 从日志构造模型上下文，sandbox 只暴露必要执行接口，外部 vault 代持凭据；幂等动作键阻止恢复时重复产生副作用。",
      "workedExample": "研究任务完成两条来源后 harness 崩溃，新实例读取 session 事件，发现 source-1 与 source-2 已核验，只继续第三条；发布动作使用 edition/date 幂等键，因此不会重复写快照。",
      "whyItMatters": "这可以直接转成 Agent 系统设计练习：分别画出事实存储、推理循环、执行权限和恢复边界，再验证每一层单独失败时会发生什么。",
      "risksAndLimits": [
        "日志可恢复不代表决策正确，错误事件仍会被后续 harness 当作事实读取。",
        "压缩上下文可能删除未来需要的细节，因此原始事件与模型上下文不能混为一体。"
      ],
      "sources": [
        {
          "tier": "tier1",
          "role": "event",
          "kind": "official_engineering",
          "name": "Anthropic · Scaling Managed Agents",
          "url": "https://www.anthropic.com/engineering/managed-agents",
          "publishedAt": "2026-04-08T00:00:00.000Z"
        },
        {
          "tier": "tier1",
          "role": "mechanism",
          "kind": "official_documentation",
          "name": "Claude Managed Agents overview",
          "url": "https://platform.claude.com/docs/en/managed-agents/overview"
        }
      ],
      "nextQuestions": [
        "恢复流程如何区分可以安全重试的工具与必须人工确认的副作用？",
        "事件日志、工作文件和模型上下文分别应该保留多久？"
      ],
      "basedOnBriefId": "ai-managed-agent-boundaries"
    },
    "sourceUrls": [
      "https://www.anthropic.com/engineering/managed-agents",
      "https://www.anthropic.com/engineering/AI-resistant-technical-evaluations",
      "https://github.com/anza-xyz/agave/releases/tag/v4.2.0",
      "https://github.com/lightningnetwork/lnd/releases/tag/v0.21.2-beta.rc1",
      "https://platform.claude.com/docs/en/managed-agents/overview"
    ],
    "relatedProjectSlugs": [
      "wallet-core",
      "exchange-wallet-system",
      "web3-wallet-engineer-lab"
    ],
    "marketSignals": [],
    "snapshotId": "learning-2026-08-11-1b2e89b6a2014ce0",
    "asOf": "2026-08-12T05:27:51.000Z",
    "origin": "research",
    "publicationState": "published"
  },
  {
    "date": "2026-08-10",
    "slug": "2026-08-10",
    "title": "学习雷达 · 2026-08-10",
    "summary": "AI 关注实时推理关键路径与可证据化改进闭环；Web3 关注签名降级防线与清晰签名上下文。",
    "publish": true,
    "reviewStatus": "automated",
    "schemaVersion": 2,
    "editionMode": "backfill",
    "researchedAt": "2026-08-12T05:27:51.000Z",
    "generatedAt": "2026-08-12T05:27:51.000Z",
    "sourceSections": [
      "ai",
      "web3",
      "deepDive"
    ],
    "missingSections": [],
    "briefs": [
      {
        "id": "ai-realtime-critical-path",
        "domain": "ai",
        "topic": "model_inference",
        "title": "实时语音 AI：先保护连续媒体关键路径",
        "whatHappened": "OpenAI 在 2026-08-03 公开 GPT-Live 的实时系统复盘，说明团队如何把连续音频、推理、工具委派与会话恢复拆成不同延迟路径。",
        "mechanism": "音频走独立快路径，较慢的推理、工具调用和持久化跨异步边界运行；替代实例提前预热，媒体握手通过 WARP 减少网络往返，避免所有工作阻塞同一条链。",
        "workedExample": "如果语音助手需要查订单，前台音频流继续接收并给出短确认，订单工具在后台执行；工具返回后再把结果注入会话，而不是暂停音频等待数据库。",
        "whyItMatters": "它给 AI 工程学习提供了可迁移的系统设计范式：先定义用户真正感知的关键路径，再把可重试、可恢复、可降级的工作移出该路径。",
        "risksAndLimits": [
          "文中的延迟与容量结果来自 OpenAI 自有系统，不能直接外推到其他网络、模型和并发规模。",
          "异步拆分增加状态同步与故障定位复杂度，必须保存可恢复事件而不是只保留内存状态。"
        ],
        "sources": [
          {
            "tier": "tier1",
            "role": "event",
            "kind": "official_engineering",
            "name": "OpenAI · Continuous voice interaction with GPT-Live",
            "url": "https://openai.com/index/continuous-voice-interaction-with-gpt-live/",
            "publishedAt": "2026-08-03T00:00:00.000Z"
          }
        ],
        "nextQuestions": [
          "如何用每帧准时率而不是平均请求延迟衡量实时 AI 的用户体验？",
          "哪些会话状态必须同步持久化，哪些可以在故障后重新计算？"
        ]
      },
      {
        "id": "ai-evidence-improvement-loop",
        "domain": "ai",
        "topic": "evaluation",
        "title": "Agent 改进闭环：先把专家纠错变成证据",
        "whatHappened": "OpenAI 与 Thrive Holdings 在 2026-05-27 公开 Tax AI 案例，展示专家纠错、生产 trace、定向 eval 与 Codex 修复任务如何组成持续改进闭环。",
        "mechanism": "系统先保存来源、预测、专家修改和最终提交的完整路径，再把重复且经审阅的差异聚类为失败模式；只有可行动模式才进入定向评测与有边界的工程任务。",
        "workedExample": "当多个税表都漏掉 fair rental days，团队不会直接改提示词，而是先确认这不是流程噪声，再构建代表性样本、预期输出和回归集，让修复同时通过定向与全量评测。",
        "whyItMatters": "学习雷达也需要同样的证据闭环：保留来源与拒绝原因，区分偶发误差和重复模式，再决定 ResearchOps 门禁是否需要修改。",
        "risksAndLimits": [
          "税务案例依赖专业人员和结构化流程，其准确率不能外推到开放网络研究。",
          "如果专家判断或 grader 本身错误，闭环会稳定强化错误目标。"
        ],
        "sources": [
          {
            "tier": "tier1",
            "role": "event",
            "kind": "official_engineering",
            "name": "OpenAI · Building self-improving tax agents with Codex",
            "url": "https://openai.com/index/building-self-improving-tax-agents-with-codex/",
            "publishedAt": "2026-05-27T00:00:00.000Z"
          }
        ],
        "nextQuestions": [
          "学习雷达应记录哪些拒绝原因，才能把编辑判断转成可复用评测？",
          "如何避免把来源稀缺误判成模型生成质量问题？"
        ]
      },
      {
        "id": "web3-signature-fail-closed",
        "domain": "web3",
        "topic": "security",
        "title": "OpenZeppelin 5.7：签名与权限不能静默降级",
        "whatHappened": "OpenZeppelin 在 2026-07-29 发布 Contracts 5.7.0，修复 AccessManager 权限绕过、ERC-7739 畸形描述降级和跨链地址静默误解析等安全边界。",
        "mechanism": "关键策略是 fail closed：无法正确绑定消息内容、域或目标链时直接拒绝，而不是退回一个表面可用但语义更弱的验证路径。",
        "workedExample": "一个 EIP-712 域的 name 超过内联边界时，调用方必须显式处理失败并重新编码；测试还要提交畸形 ERC-7739 描述，确认验证不会退化为与消息无关的签名检查。",
        "whyItMatters": "钱包与交易所后端经常组合代理、权限和签名库；理解静默降级能帮助你把安全不变量写进依赖升级与回归测试。",
        "risksAndLimits": [
          "升级 npm 依赖不会自动修复已经部署且未升级的代理合约。",
          "新版本仍需与自定义扩展、存储布局和既有签名域做兼容性回放。"
        ],
        "sources": [
          {
            "tier": "tier1",
            "role": "event",
            "kind": "official_release",
            "name": "OpenZeppelin Contracts v5.7.0",
            "url": "https://github.com/OpenZeppelin/openzeppelin-contracts/releases/tag/v5.7.0",
            "publishedAt": "2026-07-29T16:43:07.000Z"
          }
        ],
        "nextQuestions": [
          "哪些钱包签名流程仍在错误时自动回退到更弱的验证模式？",
          "如何为代理升级建立可重复的权限绕过回归向量？"
        ]
      },
      {
        "id": "web3-clear-signing-context",
        "domain": "web3",
        "topic": "wallet_cex",
        "title": "ERC-7730：清晰签名必须绑定链与合约上下文",
        "whatHappened": "Ethereum ERCs 仓库在 2026-07-22 更新 ERC-7730，继续收敛清晰签名元数据的版本与所有者字段，使钱包能按明确上下文解释调用数据。",
        "mechanism": "钱包先匹配链、合约地址、函数 selector 与元数据版本，再把原始 calldata 映射成人类可读动作；任一上下文不匹配都应展示原始字段或拒绝，而不是套用相似模板。",
        "workedExample": "同一个 transfer selector 出现在两条链的不同合约时，钱包不能只显示‘转账 100’，而要确认 chainId、合约和 token decimals 后显示资产与接收方。",
        "whyItMatters": "这直接关联钱包确认页、交易所提币审核和钓鱼防护：用户看到的意图必须与真正签名的字节属于同一上下文。",
        "risksAndLimits": [
          "清晰展示不能替代交易模拟，恶意合约仍可能在执行期产生不同效果。",
          "元数据发布者、版本和更新机制本身也需要信任与撤销策略。"
        ],
        "sources": [
          {
            "tier": "tier1",
            "role": "event",
            "kind": "protocol_commit",
            "name": "ERC-7730 owner field update",
            "url": "https://github.com/ethereum/ERCs/commit/73672565aeb10e615905663ad457d75a19eae0c2",
            "publishedAt": "2026-07-22T13:23:46.000Z"
          }
        ],
        "nextQuestions": [
          "钱包如何在元数据缺失时清楚展示不确定性而不是制造安全感？",
          "清晰签名元数据的发布、审核和撤销应由谁负责？"
        ]
      }
    ],
    "deepDive": {
      "id": "deep-ai-realtime-architecture",
      "domain": "ai",
      "topic": "infrastructure",
      "title": "专题：把实时 AI 拆成快路径、异步工作与可恢复状态",
      "whatHappened": "GPT-Live 的工程复盘把实时体验从单一模型延迟问题，扩展成媒体传输、连续推理、工具委派、状态恢复与影子验证的完整系统问题。",
      "mechanism": "先画出端到端关键路径并定义每段预算；媒体与最低限度响应留在快路径，工具和重计算通过事件边界异步执行，持久会话保存恢复点，影子流量只读验证新实现。",
      "workedExample": "构建一个语音研究助手时，可让 WebRTC 音轨持续流动，模型先确认收到问题；检索任务写入事件日志并异步执行，断线后按 sessionId 从最后事件恢复，避免重复发起外部动作。",
      "whyItMatters": "这个专题把模型、网络和分布式系统知识连成一个可练习的架构题，也能用于判断所谓‘低延迟模型’是否真的改善用户感知。",
      "risksAndLimits": [
        "快慢路径共享状态时容易出现乱序、重复执行和旧结果覆盖，需要幂等键与版本检查。",
        "影子流量必须只读并去除敏感数据，否则性能验证会扩大隐私与副作用风险。"
      ],
      "sources": [
        {
          "tier": "tier1",
          "role": "event",
          "kind": "official_engineering",
          "name": "OpenAI · Continuous voice interaction with GPT-Live",
          "url": "https://openai.com/index/continuous-voice-interaction-with-gpt-live/",
          "publishedAt": "2026-08-03T00:00:00.000Z"
        },
        {
          "tier": "tier1",
          "role": "mechanism",
          "kind": "web_standard",
          "name": "W3C WebRTC 1.0 specification",
          "url": "https://www.w3.org/TR/webrtc/"
        }
      ],
      "nextQuestions": [
        "如何为音频、首 token、工具完成和恢复分别定义 SLO？",
        "什么样的事件日志足以支持恢复，同时不会无限放大会话存储？"
      ],
      "basedOnBriefId": "ai-realtime-critical-path"
    },
    "sourceUrls": [
      "https://openai.com/index/continuous-voice-interaction-with-gpt-live/",
      "https://openai.com/index/building-self-improving-tax-agents-with-codex/",
      "https://github.com/OpenZeppelin/openzeppelin-contracts/releases/tag/v5.7.0",
      "https://github.com/ethereum/ERCs/commit/73672565aeb10e615905663ad457d75a19eae0c2",
      "https://www.w3.org/TR/webrtc/"
    ],
    "relatedProjectSlugs": [
      "wallet-core",
      "exchange-wallet-system",
      "web3-wallet-engineer-lab"
    ],
    "marketSignals": [],
    "snapshotId": "learning-2026-08-10-2e30ddbe6dfe7ed5",
    "asOf": "2026-08-12T05:27:51.000Z",
    "origin": "research",
    "publicationState": "published"
  },
  {
    "date": "2026-08-09",
    "slug": "2026-08-09",
    "title": "每日研究雷达 · 2026-08-09",
    "summary": "聚焦 lnd 迁移修复、专家纠错 Eval、清晰签名、Qwen Code 与多 Agent 研究边界。",
    "snapshotId": "learning-2026-08-09-3eb942f463c3d8ab",
    "asOf": "2026-08-09T03:36:30.000Z",
    "origin": "research",
    "publicationState": "published",
    "reviewStatus": "automated",
    "generatedAt": "2026-08-09T11:36:30+08:00",
    "sourceSections": [
      "crypto",
      "radar",
      "vibe",
      "reading"
    ],
    "missingSections": [],
    "marketSignals": [
      {
        "title": "lnd 0.21.2-beta.rc1 修补迁移失败与图同步内存边界",
        "summary": "该 RC 修复历史支付迁移启动失败、缺失版本键跳过迁移和通道图同步内存增长。运维应先备份、演练迁移与回滚；候选版不能直接替代生产稳定版。",
        "sourceUrl": "https://github.com/lightningnetwork/lnd/releases/tag/v0.21.2-beta.rc1"
      }
    ],
    "aiTip": {
      "title": "把专家纠错沉淀成定向 Eval，再给 Agent 有边界的修复任务",
      "summary": "案例把生产 trace 中反复且经专家确认的错误转成定向 eval，再让 Agent 在回归集约束下提出 PR。雷达应记录接受、拒绝和改写原因；税务指标不能外推到开放研究。",
      "sourceUrl": "https://openai.com/index/building-self-improving-tax-agents-with-codex/"
    },
    "web3Design": {
      "title": "签名前把调用数据翻译为与链和合约绑定的人类意图",
      "summary": "ERC-7730 先匹配链、合约和 selector，再把调用数据翻译成动作、对象与金额。上下文不匹配必须退回原始字段；规范仍为 Draft，清晰展示不能替代模拟。",
      "sourceUrl": "https://eips.ethereum.org/EIPS/eip-7730"
    },
    "vibeProject": {
      "title": "Qwen Code 0.21.8 · 并行提速前先封住信任继承",
      "summary": "版本加入 ACP 受限并发与审阅预算，并修复不可信目录继承信任、日志命令注入和 MCP 超时等边界。本地已验证 0.21.8；并发仍会放大副作用。",
      "sourceUrl": "https://github.com/QwenLM/qwen-code/releases/tag/v0.21.8"
    },
    "readingPick": {
      "title": "How we built our multi-agent research system",
      "summary": "主 Agent 规划，子 Agent 分头压缩证据，引用再独立核验。内部广度评测提升 90.2%，但约耗普通聊天 15 倍 token；必须给角色明确来源、停止条件和 schema。",
      "sourceUrl": "https://www.anthropic.com/engineering/multi-agent-research-system"
    },
    "sourceUrls": [
      "https://github.com/lightningnetwork/lnd/releases/tag/v0.21.2-beta.rc1",
      "https://openai.com/index/building-self-improving-tax-agents-with-codex/",
      "https://eips.ethereum.org/EIPS/eip-7730",
      "https://github.com/QwenLM/qwen-code/releases/tag/v0.21.8",
      "https://www.anthropic.com/engineering/multi-agent-research-system"
    ],
    "relatedProjectSlugs": [
      "wallet-core",
      "exchange-wallet-system",
      "web3-wallet-engineer-lab"
    ]
  },
  {
    "date": "2026-08-08",
    "slug": "2026-08-08",
    "title": "每日研究雷达 · 2026-08-08",
    "summary": "聚焦 Algorand 后量子账户预览、长任务 Agent 闭环、跨链地址、Spec Kit 与 Agent 工作研究。",
    "snapshotId": "learning-2026-08-08-78d9ba3a970af50b",
    "asOf": "2026-08-09T03:36:00.000Z",
    "origin": "research",
    "publicationState": "published",
    "reviewStatus": "automated",
    "generatedAt": "2026-08-09T11:36:00+08:00",
    "sourceSections": [
      "crypto",
      "radar",
      "vibe",
      "reading"
    ],
    "missingSections": [],
    "marketSignals": [
      {
        "title": "Algorand BetaNet 5.0.0 预演 Falcon-1024 后量子账户",
        "summary": "BetaNet 引入 Falcon-1024 签名、大交易按字节计费与 AVM v13。钱包需联动迁移密钥、费用和工具链；这仍是测试网预览，不代表主网已激活。",
        "sourceUrl": "https://github.com/algorand/go-algorand/releases/tag/v5.0.0-beta"
      }
    ],
    "aiTip": {
      "title": "让长任务 Agent 在生成、评估和上下文重置之间形成闭环",
      "summary": "planner、generator、evaluator 分工并用结构化交接跨越上下文重置。采集只交证据、独立检查器反驳；代价是更多延迟与 token，错误评分标准仍会稳定误导。",
      "sourceUrl": "https://www.anthropic.com/engineering/harness-design-long-running-apps"
    },
    "web3Design": {
      "title": "跨链地址必须把链语境与账户字节绑定成同一对象",
      "summary": "ERC-7930 把链类型、链引用和地址封进版本化二进制对象。钱包应让链语境共同进入确认、签名与策略键；规范仍在 Review，部分命名空间未必能唯一规范化。",
      "sourceUrl": "https://eips.ethereum.org/EIPS/eip-7930"
    },
    "vibeProject": {
      "title": "GitHub Spec Kit 0.16.1 · 把 Agent 开发交接变成可审阅规格",
      "summary": "它把 constitution、spec、plan、tasks 与实现收敛为版本化工件，并收紧畸形输入和临时文件边界。临时环境已验证 0.16.1；生成规格仍须审查差异。",
      "sourceUrl": "https://github.com/github/spec-kit/releases/tag/v0.16.1"
    },
    "readingPick": {
      "title": "How agents are transforming work",
      "summary": "样本中 70.2% 的个人用户曾发起估算超过一小时的人类工作任务。应衡量可验收产出和失败成本，而非 token 或时长；样本与模型估算不能外推为普遍生产率。",
      "sourceUrl": "https://openai.com/index/how-agents-are-transforming-work/"
    },
    "sourceUrls": [
      "https://github.com/algorand/go-algorand/releases/tag/v5.0.0-beta",
      "https://www.anthropic.com/engineering/harness-design-long-running-apps",
      "https://eips.ethereum.org/EIPS/eip-7930",
      "https://github.com/github/spec-kit/releases/tag/v0.16.1",
      "https://openai.com/index/how-agents-are-transforming-work/"
    ],
    "relatedProjectSlugs": [
      "wallet-core",
      "exchange-wallet-system",
      "web3-wallet-engineer-lab"
    ]
  },
  {
    "date": "2026-08-07",
    "slug": "2026-08-07",
    "title": "每日研究雷达 · 2026-08-07",
    "summary": "聚焦 Nethermind ABI 内存硬化、viem EIP-712 类型校验、欧盟加密服务治理限制、评测资源噪声、P-256 钱包授权分层、Pi，以及 agentic AI 科研软件验证。",
    "snapshotId": "learning-2026-08-07-6473e0cf19c707ff",
    "asOf": "2026-08-06T23:04:03.000Z",
    "origin": "research",
    "publicationState": "published",
    "reviewStatus": "automated",
    "generatedAt": "2026-08-07T07:04:03+08:00",
    "sourceSections": [
      "crypto",
      "radar",
      "vibe",
      "reading"
    ],
    "missingSections": [],
    "marketSignals": [
      {
        "title": "Nethermind 1.39.3 封住畸形 ABI 输入的超大内存分配路径",
        "summary": "强制节点补丁会在创建托管数组前拒绝异常动态 bytes 与数组长度，并补齐多条异常路径的池化内存清理。官方未披露 CVE 或利用事件，升级仍需验证制品、回滚与本地负载。",
        "sourceUrl": "https://github.com/NethermindEth/nethermind/releases/tag/1.39.3"
      },
      {
        "title": "viem 2.55.11 拒绝 EIP-712 裸写 uint 与 int",
        "summary": "typed-data 校验与哈希现在要求 uint256、int256 等完整位宽，避免非规范类型哈希或 RangeError。它只改变 viem 相关调用路径，不代表 EVM 或链上合约规则统一升级。",
        "sourceUrl": "https://github.com/wevm/viem/releases/tag/viem%402.55.11"
      },
      {
        "title": "欧盟扩展加密资产服务实体的治理控制限制",
        "summary": "Regulation (EU) 2026/1848 自 8 月 25 日起把特定所有、控制和治理席位禁令扩展到其他 MiCA 加密资产服务。适用仍取决于主体、设立地、控制关系、豁免与主管机关解释。",
        "sourceUrl": "https://eur-lex.europa.eu/eli/reg/2026/1848/oj/eng"
      }
    ],
    "aiTip": {
      "title": "把评测容器的资源保证值与硬终止上限分开校准",
      "summary": "固定模型、提示、任务集与 harness，只逐级调整硬上限，分别统计答案错误和容器被杀；选择能降低基础设施失败、又未显著抬高正确率的最窄区间。Anthropic 的约 3 倍上限只是特定实验示例，不是通用倍率。",
      "sourceUrl": "https://www.anthropic.com/engineering/infrastructure-noise"
    },
    "web3Design": {
      "title": "把 P-256 硬件密钥接入拆成链能力、验签与账户授权三层",
      "summary": "EIP-7951 的 P256VERIFY 只证明签名匹配公钥。钱包基础设施还应逐链绑定预编译能力，规范化 r、s 与公钥坐标，重算动作摘要，并独立校验账户、额度、nonce、有效期及恢复策略。",
      "sourceUrl": "https://eips.ethereum.org/EIPS/eip-7951"
    },
    "vibeProject": {
      "title": "Pi · 可组合的 coding agent 最小运行时",
      "summary": "Pi 同时提供交互、print/JSON、RPC 与 SDK 入口，并开放工具、权限门、沙箱、MCP 与 UI 扩展。固定版 0.84.0 已复现 CLI；默认写入与 bash、package 全系统权限、安装脚本和极端长会话资源风险要求隔离与逐项放权。",
      "sourceUrl": "https://github.com/earendil-works/pi/releases/tag/v0.84.0"
    },
    "readingPick": {
      "title": "Scientific computing in the age of agentic AI",
      "summary": "八个科研软件案例表明，agent 可加速初版，但科学有效性、数值边界、兼容性和长期所有权仍由人定义与验收。思考题：为一次真实重构列出目标行为、独立真值、最难边界与长期所有者。",
      "sourceUrl": "https://openai.com/index/scientific-computing-agentic-ai/"
    },
    "sourceUrls": [
      "https://github.com/NethermindEth/nethermind/releases/tag/1.39.3",
      "https://github.com/NethermindEth/nethermind/pull/12588",
      "https://github.com/wevm/viem/releases/tag/viem%402.55.11",
      "https://github.com/wevm/viem/pull/4961",
      "https://eur-lex.europa.eu/eli/reg/2026/1848/oj/eng",
      "https://www.anthropic.com/engineering/infrastructure-noise",
      "https://eips.ethereum.org/EIPS/eip-7951",
      "https://github.com/earendil-works/pi/blob/v0.84.0/packages/coding-agent/README.md",
      "https://github.com/earendil-works/pi/releases/tag/v0.84.0",
      "https://registry.npmjs.org/%40earendil-works%2Fpi-coding-agent/0.84.0",
      "https://api.npmjs.org/downloads/point/2026-07-07:2026-08-05/%40earendil-works%2Fpi-coding-agent",
      "https://api.github.com/repos/earendil-works/pi",
      "https://github.com/earendil-works/pi/issues/7194",
      "https://github.com/earendil-works/pi/blob/v0.84.0/packages/coding-agent/docs/packages.md",
      "https://github.com/earendil-works/pi/issues/7517",
      "https://github.com/earendil-works/pi/issues/7730",
      "https://github.com/earendil-works/pi/blob/v0.84.0/LICENSE",
      "https://openai.com/index/scientific-computing-agentic-ai/"
    ],
    "relatedProjectSlugs": [
      "wallet-core",
      "exchange-wallet-system",
      "web3-wallet-engineer-lab"
    ]
  }
]
