/* eslint-disable */
// Generated by scripts/generate-deliveries.mjs. Do not edit by hand.

export type DeliveryStatus = 'in-progress' | 'partial' | 'delivered'
export type DeliveryKind = 'engineering' | 'content' | 'automation'
export interface DeliveryLink { label: string; url: string }
export interface DeliveryRecord {
  slug: string
  title: string
  date: string
  status: DeliveryStatus
  kind: DeliveryKind
  summary: string
  projectSlugs: string[]
  goal: string
  scope: string[]
  aiContribution: string[]
  humanDecisions: string[]
  reviewFindings: string[]
  corrections: string[]
  evidenceSlugs: string[]
  publicLinks: DeliveryLink[]
  knownLimits: string[]
  nextStep: string
  publish: true
}
export const deliveryRecords: DeliveryRecord[] = [
  {
    "slug": "wallet-core-public-v1",
    "title": "wallet-core 公开 V1",
    "date": "2026-07-13",
    "status": "delivered",
    "kind": "engineering",
    "summary": "完成 TypeScript 多链离线钱包库的安全清理、编码修正、九套链测试、公开文档和 v1.0.0 Release。",
    "projectSlugs": [
      "wallet-core"
    ],
    "goal": "把私有学习代码整理成 API 边界明确、干净安装可复现、不会误导为生产 SDK 的公开 TypeScript 项目。",
    "scope": [
      "Solana Base58 编码修复",
      "Cosmos 干净安装恢复",
      "Sui dry-run-first 示例",
      "package exports 与 dist smoke test",
      "Node 20/22 CI 与敏感信息扫描"
    ],
    "aiContribution": [
      "审查公开前的包结构和安全输出",
      "协助修复编码与 ESM distribution 问题",
      "补充 CI、Release 文档和验证门禁"
    ],
    "humanDecisions": [
      "V1 只发布 GitHub Release，不发布 npm",
      "离线核心不负责 RPC、广播和资源锁定",
      "确定测试向量、签名边界和主网广播的公开规则"
    ],
    "reviewFindings": [
      "Solana privateKeyBase58 实际曾返回 Base64",
      "构建产物的 ESM 相对导入缺少扩展名",
      "本地混用依赖安装导致 Cosmos 测试误报失败",
      "测试曾输出确定性私钥材料"
    ],
    "corrections": [
      "修正 Base58 并增加双编码恢复断言",
      "修正内部 ESM import 并增加 dist smoke test",
      "使用 clean npm ci 验证九套链测试",
      "移除敏感日志并记录历史测试夹具例外"
    ],
    "evidenceSlugs": [
      "wallet-core-implementation",
      "wallet-core-tests",
      "wallet-core-sui-demo"
    ],
    "publicLinks": [
      {
        "label": "公开仓库",
        "url": "https://github.com/qianqiu0404/wallet-core"
      },
      {
        "label": "交付 PR #1",
        "url": "https://github.com/qianqiu0404/wallet-core/pull/1"
      },
      {
        "label": "v1.0.0 Release",
        "url": "https://github.com/qianqiu0404/wallet-core/releases/tag/v1.0.0"
      }
    ],
    "knownLimits": [
      "项目未经独立安全审计",
      "不包含在线节点、nonce/UTXO 锁定、广播和账务",
      "暂未发布 npm 包"
    ],
    "nextStep": "为链级过期资源、错误单位和无效对象引用补充统一负向测试，再评估是否稳定 npm API。",
    "publish": true
  },
  {
    "slug": "wallet-failure-playbook-pr2",
    "title": "钱包异常恢复手册",
    "date": "2026-07-13",
    "status": "delivered",
    "kind": "content",
    "summary": "将 30 个钱包异常整理为可筛选、可练习、可追溯到工程边界的公开恢复手册。",
    "projectSlugs": [
      "exchange-wallet-system",
      "web3-wallet-engineer-lab"
    ],
    "goal": "把零散异常判断收敛为一致的资金事实、止损、调查和恢复框架。",
    "scope": [
      "30 个结构化异常案例",
      "工程页六个重要异常摘要",
      "本地练习状态",
      "文章证据等级与 MPC/HSM 边界"
    ],
    "aiContribution": [
      "协助拆解异常分类和统一字段",
      "生成页面、校验器与响应式实现候选",
      "执行构建、类型检查和浏览器验证"
    ],
    "humanDecisions": [
      "确定网站使用自然的工程叙事",
      "决定实现、部分验证和生产设计必须分开",
      "确认私有工程只展示去敏证据"
    ],
    "reviewFindings": [
      "早期文案过度强调展示目的",
      "MPC、HSM 和生产事故边界需要收紧",
      "异常数据必须能被项目、文章和助手共同引用"
    ],
    "corrections": [
      "将目的性标题改为重要异常",
      "将快速模式改为工程概览",
      "修正 MPC/HSM 的事实状态"
    ],
    "evidenceSlugs": [
      "failure-playbook-public"
    ],
    "publicLinks": [
      {
        "label": "GitHub PR #2",
        "url": "https://github.com/qianqiu0404/xiuqiu-site/pull/2"
      },
      {
        "label": "公开异常手册",
        "url": "https://xiuqiu-site.vercel.app/engineering/failures"
      }
    ],
    "knownLimits": [
      "异常内容多数是工程设计和局部验证，不代表真实生产事故",
      "练习自评只保存在当前浏览器"
    ],
    "nextStep": "让六个核心异常与公开 Wallet Reliability Lab 的可运行实验建立一一对应。",
    "publish": true
  },
  {
    "slug": "wallet-reliability-lab-v1",
    "title": "Wallet Reliability Lab 六个异常实验",
    "date": "2026-07-13",
    "status": "delivered",
    "kind": "engineering",
    "summary": "把正常提现作为基线，用 Go 断言和 Vue 时间线实现六个钱包异常恢复实验。",
    "projectSlugs": [
      "web3-wallet-engineer-lab"
    ],
    "goal": "为钱包异常手册提供可运行、可阅读、不会接触真实资金的公开工程证据。",
    "scope": [
      "共享场景 Catalog",
      "六个异常的资金不变量",
      "Go 模型与测试",
      "Vue 静态实验台",
      "CI 与 GitHub Pages"
    ],
    "aiContribution": [
      "协助将异常描述转成确定性场景数据",
      "实现 Go 不变量模型和交互式状态时间线",
      "补充 CI、Pages 与敏感信息门禁"
    ],
    "humanDecisions": [
      "只保留一个主 Wallet Lab，避免重复仓库",
      "正常流程不计入六个异常",
      "确定 fail-closed、canonical 事实和反向分录等恢复原则"
    ],
    "reviewFindings": [
      "原公开 Lab 只覆盖最小 happy path",
      "本地 reliability lab 的 TypeScript 与 Go 场景存在重复事实源",
      "部分实验名称尚未与网站异常 slug 对齐"
    ],
    "corrections": [
      "用共享 JSON 同时供 Go 与 Vue 校验",
      "统一六个实验与异常手册关联",
      "删除目的导向文档并强化当前边界"
    ],
    "evidenceSlugs": [
      "wallet-lab-implementation",
      "wallet-lab-tests",
      "wallet-lab-demo",
      "engineering-observability-demo"
    ],
    "publicLinks": [
      {
        "label": "公开仓库",
        "url": "https://github.com/qianqiu0404/web3-wallet-engineer-lab"
      },
      {
        "label": "交付 PR #1",
        "url": "https://github.com/qianqiu0404/web3-wallet-engineer-lab/pull/1"
      },
      {
        "label": "在线实验台",
        "url": "https://qianqiu0404.github.io/web3-wallet-engineer-lab/"
      }
    ],
    "knownLimits": [
      "使用内存与确定性模拟，不连接生产服务",
      "Go Runner 不在线上部署",
      "MPC/TSS 和 HSM 只作为签名可用性边界表达"
    ],
    "nextStep": "继续增加 RPC 多节点仲裁和账务 outbox 的故障注入，但仍保持每个实验有独立资金不变量。",
    "publish": true
  }
]
