/* eslint-disable */
// Generated by scripts/generate-ai-cases.mjs. Do not edit by hand.

export type AiCaseStage = 'building' | 'verified-local' | 'operational'

export interface AiCase {
  id: number
  slug: string
  title: string
  stage: AiCaseStage
  updatedAt: string
  summary: string
  currentFocus: string
  flow: string[]
  responsibilities: string[]
  evidence: string[]
  failureHandling: string[]
  knownLimits: string[]
  targetOutcome: string
  nextMilestone: string
  relatedArticleSlugs: string[]
}

export const aiCases: AiCase[] = [
  {
    "id": 1,
    "slug": "ai-coding-collaboration",
    "title": "AI Coding 协作",
    "stage": "verified-local",
    "updatedAt": "2026-07-13",
    "summary": "用 Planner、Worker、Reviewer 和人工验收拆开计划、执行与审查，让 AI 修改代码时有边界、有交接、有验证。",
    "currentFocus": "把这套协作方式应用到钱包项目的真实改动，并让每次交付都能回到代码差异、测试结果和未解决风险。",
    "flow": [
      "定义目标与不做什么",
      "Planner 拆解边界与验收标准",
      "Worker 按计划实现",
      "Reviewer 检查错误、遗漏和越界",
      "我运行验证并决定是否接受"
    ],
    "responsibilities": [
      "我负责目标、风险偏好和最终验收",
      "AI 负责方案比较、实现辅助、测试补充和第二视角审查",
      "高风险钱包判断必须由代码与运行结果支撑"
    ],
    "evidence": [
      "已形成最小 Planner/Worker/Reviewer 工作流",
      "在网站与钱包项目中使用构建、类型检查和测试作为完成条件",
      "记录 Agent 修改错文件、目标漂移和验证不足等失败模式"
    ],
    "failureHandling": [
      "发现目标漂移时回到原始成功标准",
      "发现修改越界时保留用户变更并缩小补丁",
      "测试失败时不把代码生成等同于完成"
    ],
    "knownLimits": [
      "并非所有小任务都值得拆成多 Agent",
      "模型审查不能替代本人理解和安全判断",
      "仍需积累更多钱包项目中的量化案例"
    ],
    "targetOutcome": "形成一套可以在复杂工程任务中重复使用的协作协议：上下文模板、角色边界、交接格式、验证清单和失败接管规则完整一致。",
    "nextMilestone": "选择一次钱包状态机或签名边界改动，保留计划、实现、审查和人工验收的完整公开复盘。",
    "relatedArticleSlugs": [
      "minimal-multi-agent-coding-workflow",
      "codex-ai-workflow-system-retrospective"
    ]
  },
  {
    "id": 2,
    "slug": "obsidian-knowledge-system",
    "title": "Obsidian 知识系统",
    "stage": "operational",
    "updatedAt": "2026-07-13",
    "summary": "把外部资料、AI 候选、项目记录和个人理解分层管理，通过人工审核与发布门禁维护唯一主库。",
    "currentFocus": "减少重复笔记和未经核验的 AI 内容，让知识能回到钱包项目、面试讲解、文章和下一步行动。",
    "flow": [
      "来源进入资料库或收件箱",
      "AI 生成待审核候选",
      "人工核对代码与来源",
      "结论合并到唯一主库",
      "显式 publish: true 后生成公开内容"
    ],
    "responsibilities": [
      "我决定哪些结论进入主库和公开站点",
      "AI 负责查重、结构化、关联与候选生成",
      "私人日记、求职计划和未核验内容永远不自动公开"
    ],
    "evidence": [
      "已建立项目、知识、资料、模板和归档分区",
      "网站同步脚本只接受显式发布标记",
      "钱包讲义、Go 学习和项目看板使用统一入口与维护规则"
    ],
    "failureHandling": [
      "没有 publish: true 时同步器忽略笔记",
      "内容重复时合并到唯一主库而不是新增第二份",
      "来源或代码事实不足时保持候选状态"
    ],
    "knownLimits": [
      "发布记录仍需要人工挑选和编辑",
      "站点不读取本机绝对路径",
      "知识结构需要定期清理失效入口"
    ],
    "targetOutcome": "让每次学习都可以沿来源、候选、核验、主库、项目和公开输出追踪，同时确保隐私内容无法因自动同步进入网站。",
    "nextMilestone": "把项目里程碑也接入显式发布流程，并为同步前后的字段、隐私词和关联项目增加自动校验。",
    "relatedArticleSlugs": [
      "codex-ai-workflow-system-retrospective",
      "minimal-multi-agent-coding-workflow"
    ]
  },
  {
    "id": 3,
    "slug": "research-automation-workflows",
    "title": "Obsidian → xiuqiu-site 每日发布",
    "stage": "operational",
    "updatedAt": "2026-07-13",
    "summary": "五个定时任务先把研究输入写入 Obsidian；09:15 发布任务只读取四类公开区块，经来源、隐私、PR 与构建门禁进入每日研究雷达。",
    "currentFocus": "让每日研究内容自动进入网站，同时保证私人笔记不被读取、外部链接不被创造、失败构建不能进入 main。",
    "flow": [
      "五个定时任务生成 Obsidian 输入",
      "只读取 crypto / radar / vibe / reading",
      "筛选并生成同日 radar Markdown",
      "校验来源 URL 与隐私边界",
      "创建或更新自动 PR",
      "构建通过后 squash merge",
      "Vercel 从 main 部署"
    ],
    "responsibilities": [
      "我定义可公开范围、选题价值和最终研究行动",
      "AI 负责筛选、结构化和关联工程项目",
      "CI 只允许日报修改白名单文件并执行完整构建"
    ],
    "evidence": [
      "已有五个定时任务向每日任务文件的固定标记区块写入",
      "首期雷达已从 crypto、radar、vibe、reading 四类输入生成",
      "解析器与测试覆盖三类发布阈值、URL 来源约束、隐私关键词和同日幂等"
    ],
    "failureHandling": [
      "少于三类公开来源时不创建 PR",
      "来源不足或隐私校验失败时立即停止发布",
      "PR 越界修改代码或构建失败时禁止合并并保留上一期线上内容"
    ],
    "knownLimits": [
      "AI 自动汇总不等于个人最终观点",
      "外部信息源质量和可访问性仍需持续评估",
      "自动合并只适用于同仓库指定分支前缀和文件白名单"
    ],
    "targetOutcome": "形成每天可重复运行的研究发布闭环：Obsidian 是私有工作台，GitHub PR 是交付与审计边界，网站只展示经过自动门禁的精选研究内容。",
    "nextMilestone": "连续运行七天并记录来源覆盖、失败原因、重复 URL 和被晋升为长文章的主题。",
    "relatedArticleSlugs": [
      "codex-ai-workflow-system-retrospective",
      "web3-narrative-participation-framework"
    ]
  }
]
