/* eslint-disable */
// Generated by scripts/generate-articles.mjs. Do not edit by hand.

export type ArticleConceptTag = 'wallet-backend' | 'signer-service' | 'multi-chain' | 'go-infra' | 'evm' | 'mpc-tss' | 'api-design' | 'ai-engineering'

export interface ArticleSummary {
  id: number
  slug: string
  title: string
  date: string
  updatedAt?: string
  summary: string
  tags: string[]
  readingTime: string
  difficulty: string
}

export interface ArticleKnowledge extends ArticleSummary {
  conceptTags: ArticleConceptTag[]
  relatedProjectIds: number[]
  recommendedSlugs: string[]
  suggestedQuestions: string[]
}

export const articleKnowledge: ArticleKnowledge[] = [
  {
    "id": 1,
    "slug": "api-system-calls",
    "title": "API 到底是什么？从钱包后端项目理解系统调用",
    "date": "2026-05-14",
    "summary": "从前端、后端、数据库、第三方服务、链节点和签名机之间的关系，拆解 API 在现代软件系统中的连接作用。",
    "tags": [
      "API",
      "Backend",
      "System Design",
      "Wallet"
    ],
    "readingTime": "8 min",
    "difficulty": "基础",
    "conceptTags": [
      "api-design",
      "wallet-backend"
    ],
    "relatedProjectIds": [
      1,
      2,
      3
    ],
    "recommendedSlugs": [
      "http-rpc-grpc",
      "wallet-api-boundary"
    ],
    "suggestedQuestions": [
      "这篇文章如何解释钱包 API 的系统边界？",
      "普通业务 API 和钱包 API 的差异是什么？"
    ]
  },
  {
    "id": 2,
    "slug": "http-rpc-grpc",
    "title": "HTTP、RPC、gRPC 的区别与项目使用场景",
    "date": "2026-05-16",
    "summary": "结合钱包系统和行情服务，解释 HTTP 更适合对外接口，gRPC 更适合内部服务调用，RPC 是远程过程调用思想。",
    "tags": [
      "HTTP",
      "RPC",
      "gRPC",
      "Backend"
    ],
    "readingTime": "10 min",
    "difficulty": "进阶",
    "conceptTags": [
      "api-design",
      "go-infra"
    ],
    "relatedProjectIds": [
      1,
      2,
      3
    ],
    "recommendedSlugs": [
      "api-system-calls",
      "market-services-data-flow"
    ],
    "suggestedQuestions": [
      "HTTP、RPC、gRPC 在钱包系统里分别适合什么场景？",
      "wallet-api 和 wallet-sign 为什么适合用 gRPC 通信？"
    ]
  },
  {
    "id": 3,
    "slug": "wallet-api-boundary",
    "title": "wallet-api：多链钱包后端 API 的职责边界",
    "date": "2026-05-19",
    "summary": "梳理多链钱包 API 服务如何组织链配置、接口入口、节点调用、交易构建和签名服务协作。",
    "tags": [
      "Web3",
      "Wallet",
      "Go",
      "API"
    ],
    "readingTime": "12 min",
    "difficulty": "项目拆解",
    "conceptTags": [
      "wallet-backend",
      "api-design",
      "multi-chain"
    ],
    "relatedProjectIds": [
      1,
      2
    ],
    "recommendedSlugs": [
      "wallet-sign-signer",
      "wallet-address-models"
    ],
    "suggestedQuestions": [
      "wallet-api 应该负责什么，不应该负责什么？",
      "多链钱包 API 的核心复杂度在哪里？"
    ]
  },
  {
    "id": 4,
    "slug": "wallet-sign-signer",
    "title": "wallet-sign：多链签名机为什么要独立设计",
    "date": "2026-05-21",
    "summary": "从安全边界、私钥管理、离线签名、批量签名和多链差异角度，拆解签名机在钱包系统中的位置。",
    "tags": [
      "Wallet",
      "Signer",
      "Security",
      "Multi-chain"
    ],
    "readingTime": "12 min",
    "difficulty": "项目拆解",
    "conceptTags": [
      "signer-service",
      "wallet-backend",
      "multi-chain"
    ],
    "relatedProjectIds": [
      1,
      2,
      5
    ],
    "recommendedSlugs": [
      "wallet-api-boundary",
      "wallet-address-models"
    ],
    "suggestedQuestions": [
      "为什么签名机要从 API 层独立出来？",
      "签名服务如何降低私钥暴露风险？"
    ]
  },
  {
    "id": 5,
    "slug": "market-services-data-flow",
    "title": "market-services：Go 行情服务如何组织数据流",
    "date": "2026-05-24",
    "summary": "从 HTTP、gRPC、Redis、PostgreSQL、行情同步和 Dashboard API，拆解一个 Go 后端行情服务如何运行。",
    "tags": [
      "Go",
      "Market",
      "Backend",
      "Redis"
    ],
    "readingTime": "12 min",
    "difficulty": "项目拆解",
    "conceptTags": [
      "go-infra",
      "api-design"
    ],
    "relatedProjectIds": [
      3
    ],
    "recommendedSlugs": [
      "http-rpc-grpc",
      "api-system-calls"
    ],
    "suggestedQuestions": [
      "market-services 的数据流如何组织？",
      "Redis 和 PostgreSQL 在行情服务里如何分工？"
    ]
  },
  {
    "id": 6,
    "slug": "wallet-address-models",
    "title": "BTC、ETH、Solana 地址生成与签名模型对比",
    "date": "2026-05-27",
    "summary": "对比 UTXO 模型、账户模型、HD 钱包路径、地址格式和不同链的签名逻辑差异，理解多链钱包为什么需要抽象。",
    "tags": [
      "BTC",
      "ETH",
      "Solana",
      "Multi-chain"
    ],
    "readingTime": "12 min",
    "difficulty": "进阶",
    "conceptTags": [
      "multi-chain",
      "signer-service",
      "wallet-backend"
    ],
    "relatedProjectIds": [
      1,
      2
    ],
    "recommendedSlugs": [
      "wallet-api-boundary",
      "wallet-sign-signer"
    ],
    "suggestedQuestions": [
      "BTC、ETH、Solana 的地址和签名模型有什么差异？",
      "多链钱包为什么不能用一套交易模型硬套所有链？"
    ]
  },
  {
    "id": 7,
    "slug": "evm-call-proxy-patterns",
    "title": "合约调用与代理升级：从 delegatecall 到钻石代理的工程实践",
    "date": "2026-06-02",
    "summary": "拆解 call / delegatecall / staticcall 的底层差异、透明代理 vs UUPS vs 钻石代理的取舍逻辑，以及不可升级合约的升级策略。",
    "tags": [
      "Solidity",
      "EVM",
      "Proxy",
      "Upgradeability"
    ],
    "readingTime": "14 min",
    "difficulty": "进阶",
    "conceptTags": [
      "evm"
    ],
    "relatedProjectIds": [
      4,
      6
    ],
    "recommendedSlugs": [
      "evm-create2-assembly-lifecycle",
      "eip-erc-protocol-evolution"
    ],
    "suggestedQuestions": [
      "delegatecall 和代理升级的工程风险是什么？",
      "钻石代理适合什么样的合约系统？"
    ]
  },
  {
    "id": 8,
    "slug": "evm-create2-assembly-lifecycle",
    "title": "EVM 深度工程：create2、内联汇编与合约生命周期管理",
    "date": "2026-06-06",
    "summary": "深入 create2 确定性部署、Solidity 内联汇编的内存模型、合约自毁的边界条件和函数选择器的底层工作机制。",
    "tags": [
      "Solidity",
      "EVM",
      "Assembly",
      "create2"
    ],
    "readingTime": "14 min",
    "difficulty": "进阶",
    "conceptTags": [
      "evm"
    ],
    "relatedProjectIds": [
      4,
      6
    ],
    "recommendedSlugs": [
      "evm-call-proxy-patterns",
      "eip-erc-protocol-evolution"
    ],
    "suggestedQuestions": [
      "create2 在合约部署中解决什么问题？",
      "内联汇编在 EVM 工程里应该谨慎用在哪里？"
    ]
  },
  {
    "id": 9,
    "slug": "eip-erc-protocol-evolution",
    "title": "EIP 工程解读：从 ERC20 到 EIP7702 的协议演进与选择逻辑",
    "date": "2026-06-10",
    "summary": "梳理 ERC20/721/1155 的工程差异、EIP1559 的 gas 模型变革、EIP4337 账户抽象和 EIP7702 的 EOA 升级路径。",
    "tags": [
      "EIP",
      "ERC",
      "Ethereum",
      "Standards"
    ],
    "readingTime": "14 min",
    "difficulty": "进阶",
    "conceptTags": [
      "evm",
      "api-design"
    ],
    "relatedProjectIds": [
      4,
      6
    ],
    "recommendedSlugs": [
      "evm-call-proxy-patterns",
      "evm-create2-assembly-lifecycle"
    ],
    "suggestedQuestions": [
      "ERC20 到 EIP7702 的演进反映了哪些工程取舍？",
      "协议标准如何影响钱包和 DApp 的设计？"
    ]
  },
  {
    "id": 10,
    "slug": "withdrawal-error-handling",
    "title": "提现错误处理机制：自动重试、补偿任务与人工复核",
    "date": "2026-06-18",
    "summary": "提现错误不能简单按失败重发处理，而要按链上事实是否确定分层：网络和节点问题自动重试，系统状态落后自动补偿，链上事实不确定或账务有风险时人工复核。",
    "tags": [
      "Web3",
      "Wallet",
      "Withdrawal",
      "Backend",
      "Security"
    ],
    "readingTime": "6 min",
    "difficulty": "项目拆解",
    "conceptTags": [
      "wallet-backend",
      "api-design",
      "multi-chain",
      "signer-service"
    ],
    "relatedProjectIds": [
      1,
      2
    ],
    "recommendedSlugs": [
      "wallet-api-boundary",
      "wallet-sign-signer",
      "wallet-address-models",
      "market-services-data-flow"
    ],
    "suggestedQuestions": [
      "提现广播 timeout 时为什么不能直接重新发一笔？",
      "提现系统如何区分自动重试、自动补偿和人工复核？",
      "EVM nonce 和 BTC UTXO 在提现错误处理中有什么风险？"
    ]
  },
  {
    "id": 11,
    "slug": "mpc-wallet-sign-integration",
    "title": "wallet-sign 接入 MPC：一次签名安全边界升级的工程复盘",
    "date": "2026-06-19",
    "summary": "这次改造里，我把 wallet-sign 从本地私钥签名机收敛成 SignerBackend 调度层，并将 MPC 作为生产级签名后端接入，让完整私钥不再落在单点服务里。",
    "tags": [
      "Web3",
      "Wallet",
      "MPC",
      "TSS",
      "wallet-sign",
      "Security"
    ],
    "readingTime": "6 min",
    "difficulty": "项目拆解",
    "conceptTags": [
      "mpc-tss",
      "signer-service",
      "wallet-backend",
      "multi-chain"
    ],
    "relatedProjectIds": [
      2,
      5
    ],
    "recommendedSlugs": [
      "wallet-sign-signer",
      "wallet-api-boundary",
      "wallet-address-models",
      "withdrawal-error-handling"
    ],
    "suggestedQuestions": [
      "这次 wallet-sign 接入 MPC 后，签名边界发生了什么变化？",
      "为什么我没有让 wallet-api 或 wallet-service 直接感知 MPC？",
      "MPC 接入后，SignerBackend 抽象解决了什么问题？"
    ]
  },
  {
    "id": 12,
    "slug": "aws-cloudhsm-wallet-sign-integration",
    "title": "wallet-sign 接入 AWS CloudHSM：一次生产级 HSM 签名架构复盘",
    "date": "2026-06-19",
    "summary": "这次改造里，我把 wallet-sign 从本地私钥签名升级为 AWS CloudHSM 支撑的生产级签名架构，让私钥在 HSM 内生成、不可导出，并通过 hsm-gateway 收敛 PKCS#11 复杂性。",
    "tags": [
      "Web3",
      "Wallet",
      "AWS",
      "CloudHSM",
      "HSM",
      "wallet-sign",
      "Security"
    ],
    "readingTime": "8 min",
    "difficulty": "项目拆解",
    "conceptTags": [
      "signer-service",
      "wallet-backend",
      "multi-chain",
      "mpc-tss"
    ],
    "relatedProjectIds": [
      2,
      5
    ],
    "recommendedSlugs": [
      "mpc-wallet-sign-integration",
      "wallet-sign-signer",
      "wallet-api-boundary",
      "withdrawal-error-handling"
    ],
    "suggestedQuestions": [
      "这次 wallet-sign 接入 AWS CloudHSM 后，签名安全边界发生了什么变化？",
      "为什么要在 wallet-sign 和 CloudHSM 之间加 hsm-gateway？",
      "CloudHSM 签名失败时，为什么不能 fallback 到本地私钥？"
    ]
  }
]

export const articleSummaries: ArticleSummary[] = [
  {
    "id": 1,
    "slug": "api-system-calls",
    "title": "API 到底是什么？从钱包后端项目理解系统调用",
    "date": "2026-05-14",
    "summary": "从前端、后端、数据库、第三方服务、链节点和签名机之间的关系，拆解 API 在现代软件系统中的连接作用。",
    "tags": [
      "API",
      "Backend",
      "System Design",
      "Wallet"
    ],
    "readingTime": "8 min",
    "difficulty": "基础"
  },
  {
    "id": 2,
    "slug": "http-rpc-grpc",
    "title": "HTTP、RPC、gRPC 的区别与项目使用场景",
    "date": "2026-05-16",
    "summary": "结合钱包系统和行情服务，解释 HTTP 更适合对外接口，gRPC 更适合内部服务调用，RPC 是远程过程调用思想。",
    "tags": [
      "HTTP",
      "RPC",
      "gRPC",
      "Backend"
    ],
    "readingTime": "10 min",
    "difficulty": "进阶"
  },
  {
    "id": 3,
    "slug": "wallet-api-boundary",
    "title": "wallet-api：多链钱包后端 API 的职责边界",
    "date": "2026-05-19",
    "summary": "梳理多链钱包 API 服务如何组织链配置、接口入口、节点调用、交易构建和签名服务协作。",
    "tags": [
      "Web3",
      "Wallet",
      "Go",
      "API"
    ],
    "readingTime": "12 min",
    "difficulty": "项目拆解"
  },
  {
    "id": 4,
    "slug": "wallet-sign-signer",
    "title": "wallet-sign：多链签名机为什么要独立设计",
    "date": "2026-05-21",
    "summary": "从安全边界、私钥管理、离线签名、批量签名和多链差异角度，拆解签名机在钱包系统中的位置。",
    "tags": [
      "Wallet",
      "Signer",
      "Security",
      "Multi-chain"
    ],
    "readingTime": "12 min",
    "difficulty": "项目拆解"
  },
  {
    "id": 5,
    "slug": "market-services-data-flow",
    "title": "market-services：Go 行情服务如何组织数据流",
    "date": "2026-05-24",
    "summary": "从 HTTP、gRPC、Redis、PostgreSQL、行情同步和 Dashboard API，拆解一个 Go 后端行情服务如何运行。",
    "tags": [
      "Go",
      "Market",
      "Backend",
      "Redis"
    ],
    "readingTime": "12 min",
    "difficulty": "项目拆解"
  },
  {
    "id": 6,
    "slug": "wallet-address-models",
    "title": "BTC、ETH、Solana 地址生成与签名模型对比",
    "date": "2026-05-27",
    "summary": "对比 UTXO 模型、账户模型、HD 钱包路径、地址格式和不同链的签名逻辑差异，理解多链钱包为什么需要抽象。",
    "tags": [
      "BTC",
      "ETH",
      "Solana",
      "Multi-chain"
    ],
    "readingTime": "12 min",
    "difficulty": "进阶"
  },
  {
    "id": 7,
    "slug": "evm-call-proxy-patterns",
    "title": "合约调用与代理升级：从 delegatecall 到钻石代理的工程实践",
    "date": "2026-06-02",
    "summary": "拆解 call / delegatecall / staticcall 的底层差异、透明代理 vs UUPS vs 钻石代理的取舍逻辑，以及不可升级合约的升级策略。",
    "tags": [
      "Solidity",
      "EVM",
      "Proxy",
      "Upgradeability"
    ],
    "readingTime": "14 min",
    "difficulty": "进阶"
  },
  {
    "id": 8,
    "slug": "evm-create2-assembly-lifecycle",
    "title": "EVM 深度工程：create2、内联汇编与合约生命周期管理",
    "date": "2026-06-06",
    "summary": "深入 create2 确定性部署、Solidity 内联汇编的内存模型、合约自毁的边界条件和函数选择器的底层工作机制。",
    "tags": [
      "Solidity",
      "EVM",
      "Assembly",
      "create2"
    ],
    "readingTime": "14 min",
    "difficulty": "进阶"
  },
  {
    "id": 9,
    "slug": "eip-erc-protocol-evolution",
    "title": "EIP 工程解读：从 ERC20 到 EIP7702 的协议演进与选择逻辑",
    "date": "2026-06-10",
    "summary": "梳理 ERC20/721/1155 的工程差异、EIP1559 的 gas 模型变革、EIP4337 账户抽象和 EIP7702 的 EOA 升级路径。",
    "tags": [
      "EIP",
      "ERC",
      "Ethereum",
      "Standards"
    ],
    "readingTime": "14 min",
    "difficulty": "进阶"
  },
  {
    "id": 10,
    "slug": "withdrawal-error-handling",
    "title": "提现错误处理机制：自动重试、补偿任务与人工复核",
    "date": "2026-06-18",
    "summary": "提现错误不能简单按失败重发处理，而要按链上事实是否确定分层：网络和节点问题自动重试，系统状态落后自动补偿，链上事实不确定或账务有风险时人工复核。",
    "tags": [
      "Web3",
      "Wallet",
      "Withdrawal",
      "Backend",
      "Security"
    ],
    "readingTime": "6 min",
    "difficulty": "项目拆解"
  },
  {
    "id": 11,
    "slug": "mpc-wallet-sign-integration",
    "title": "wallet-sign 接入 MPC：一次签名安全边界升级的工程复盘",
    "date": "2026-06-19",
    "summary": "这次改造里，我把 wallet-sign 从本地私钥签名机收敛成 SignerBackend 调度层，并将 MPC 作为生产级签名后端接入，让完整私钥不再落在单点服务里。",
    "tags": [
      "Web3",
      "Wallet",
      "MPC",
      "TSS",
      "wallet-sign",
      "Security"
    ],
    "readingTime": "6 min",
    "difficulty": "项目拆解"
  },
  {
    "id": 12,
    "slug": "aws-cloudhsm-wallet-sign-integration",
    "title": "wallet-sign 接入 AWS CloudHSM：一次生产级 HSM 签名架构复盘",
    "date": "2026-06-19",
    "summary": "这次改造里，我把 wallet-sign 从本地私钥签名升级为 AWS CloudHSM 支撑的生产级签名架构，让私钥在 HSM 内生成、不可导出，并通过 hsm-gateway 收敛 PKCS#11 复杂性。",
    "tags": [
      "Web3",
      "Wallet",
      "AWS",
      "CloudHSM",
      "HSM",
      "wallet-sign",
      "Security"
    ],
    "readingTime": "8 min",
    "difficulty": "项目拆解"
  }
]
