/* eslint-disable */
// Generated by scripts/generate-evidence.mjs. Do not edit by hand.

export type EvidenceKind = 'implementation' | 'test' | 'demo' | 'writeup'
export type EvidenceStatus = 'verified' | 'partial' | 'design'
export type EvidenceVisibility = 'public' | 'private-summary'

export interface EvidenceRecord {
  slug: string
  title: string
  capabilityIds: string[]
  projectSlugs: string[]
  kind: EvidenceKind
  status: EvidenceStatus
  visibility: EvidenceVisibility
  summary: string
  verifiedAt: string
  command?: string
  url?: string
  failureSlugs: string[]
  deliverySlugs: string[]
}

export const evidenceRecords: EvidenceRecord[] = [
  {
    "slug": "engineering-observability-demo",
    "title": "健康检查、指标与恢复证据展示",
    "capabilityIds": [
      "observability"
    ],
    "projectSlugs": [
      "web3-wallet-engineer-lab"
    ],
    "kind": "demo",
    "status": "partial",
    "visibility": "public",
    "summary": "公开 Lab 提供健康检查、Prometheus 文本指标、审计日志和实验时间线；真实告警、追踪与多实例运行仍未实现。",
    "verifiedAt": "2026-07-13",
    "url": "https://github.com/qianqiu0404/web3-wallet-engineer-lab",
    "failureSlugs": [],
    "deliverySlugs": [
      "wallet-reliability-lab-v1"
    ]
  },
  {
    "slug": "exchange-wallet-implementation",
    "title": "Exchange Wallet Infrastructure 工程边界",
    "capabilityIds": [
      "request-idempotency",
      "fund-state",
      "risk-authorization",
      "chain-resources",
      "signer-boundary",
      "broadcast-finality",
      "reconciliation",
      "observability"
    ],
    "projectSlugs": [
      "exchange-wallet-system"
    ],
    "kind": "implementation",
    "status": "partial",
    "visibility": "private-summary",
    "summary": "四个私有服务已定位资金编排、风险审批、多链适配与签名边界；网站只公开去敏后的代码事实和当前限制。",
    "verifiedAt": "2026-07-13",
    "failureSlugs": [
      "duplicate-request-id",
      "broadcast-result-unknown",
      "chain-success-local-failure",
      "credited-deposit-reorg",
      "evm-nonce-gap",
      "risk-signer-unavailable"
    ],
    "deliverySlugs": []
  },
  {
    "slug": "exchange-wallet-tests",
    "title": "四服务局部测试基线",
    "capabilityIds": [
      "request-idempotency",
      "fund-state",
      "risk-authorization",
      "chain-resources",
      "signer-boundary",
      "broadcast-finality",
      "reconciliation",
      "observability"
    ],
    "projectSlugs": [
      "exchange-wallet-system"
    ],
    "kind": "test",
    "status": "partial",
    "visibility": "private-summary",
    "summary": "dispatcher、chain adaptor、RPC、risk approval 与幂等相关测试已分别运行；跨四服务的一键基线仍在整理。",
    "verifiedAt": "2026-07-13",
    "command": "go test ./services ./services/grpc ./services/rpc ./chaindispatcher",
    "failureSlugs": [
      "duplicate-request-id",
      "broadcast-result-unknown",
      "chain-success-local-failure",
      "risk-signer-unavailable"
    ],
    "deliverySlugs": []
  },
  {
    "slug": "failure-playbook-public",
    "title": "30 个钱包异常恢复手册",
    "capabilityIds": [
      "request-idempotency",
      "fund-state",
      "risk-authorization",
      "chain-resources",
      "signer-boundary",
      "broadcast-finality",
      "reconciliation",
      "observability"
    ],
    "projectSlugs": [
      "exchange-wallet-system",
      "web3-wallet-engineer-lab",
      "wallet-core"
    ],
    "kind": "writeup",
    "status": "verified",
    "visibility": "public",
    "summary": "30 个异常按资金事实、先止损、调查证据、恢复步骤、幂等依据和当前项目边界组织。",
    "verifiedAt": "2026-07-13",
    "url": "https://xiuqiu-site.vercel.app/engineering/failures",
    "failureSlugs": [
      "duplicate-request-id",
      "broadcast-result-unknown",
      "chain-success-local-failure",
      "credited-deposit-reorg",
      "evm-nonce-gap",
      "risk-signer-unavailable"
    ],
    "deliverySlugs": [
      "wallet-failure-playbook-pr2"
    ]
  },
  {
    "slug": "wallet-core-implementation",
    "title": "wallet-core TypeScript 多链实现",
    "capabilityIds": [
      "chain-resources",
      "signer-boundary"
    ],
    "projectSlugs": [
      "wallet-core"
    ],
    "kind": "implementation",
    "status": "verified",
    "visibility": "public",
    "summary": "公开 TypeScript 库覆盖 EVM、Bitcoin、Solana、TRON、Cosmos 与 Sui，并显式保留 nonce、UTXO、blockhash、TAPOS、sequence 和对象版本。",
    "verifiedAt": "2026-07-13",
    "url": "https://github.com/qianqiu0404/wallet-core",
    "failureSlugs": [
      "evm-nonce-gap"
    ],
    "deliverySlugs": [
      "wallet-core-public-v1"
    ]
  },
  {
    "slug": "wallet-core-sui-demo",
    "title": "Sui dry-run-first 示例",
    "capabilityIds": [
      "chain-resources",
      "signer-boundary",
      "broadcast-finality"
    ],
    "projectSlugs": [
      "wallet-core"
    ],
    "kind": "demo",
    "status": "verified",
    "visibility": "public",
    "summary": "示例从调用方读取新鲜 Sui 对象与 gas 数据，默认只 dry-run；广播和 mainnet 均需要显式开关。",
    "verifiedAt": "2026-07-13",
    "command": "npm run sui:deposit",
    "url": "https://github.com/qianqiu0404/wallet-core/tree/main/examples",
    "failureSlugs": [],
    "deliverySlugs": [
      "wallet-core-public-v1"
    ]
  },
  {
    "slug": "wallet-core-tests",
    "title": "wallet-core 九套链测试",
    "capabilityIds": [
      "chain-resources",
      "signer-boundary"
    ],
    "projectSlugs": [
      "wallet-core"
    ],
    "kind": "test",
    "status": "verified",
    "visibility": "public",
    "summary": "干净安装下类型检查、九套 Jest、45 个测试、构建和 dist import smoke test 全部通过。",
    "verifiedAt": "2026-07-13",
    "command": "npm run verify",
    "url": "https://github.com/qianqiu0404/wallet-core/actions",
    "failureSlugs": [
      "evm-nonce-gap"
    ],
    "deliverySlugs": [
      "wallet-core-public-v1"
    ]
  },
  {
    "slug": "wallet-lab-demo",
    "title": "六个异常恢复交互实验",
    "capabilityIds": [
      "request-idempotency",
      "fund-state",
      "risk-authorization",
      "signer-boundary",
      "broadcast-finality",
      "reconciliation",
      "observability"
    ],
    "projectSlugs": [
      "web3-wallet-engineer-lab"
    ],
    "kind": "demo",
    "status": "verified",
    "visibility": "public",
    "summary": "静态实验台可逐步展开故障注入、资金不变量、止损动作、恢复依据和状态时间线。",
    "verifiedAt": "2026-07-13",
    "url": "https://qianqiu0404.github.io/web3-wallet-engineer-lab/",
    "failureSlugs": [
      "duplicate-request-id",
      "broadcast-result-unknown",
      "chain-success-local-failure",
      "credited-deposit-reorg",
      "evm-nonce-gap",
      "risk-signer-unavailable"
    ],
    "deliverySlugs": [
      "wallet-reliability-lab-v1"
    ]
  },
  {
    "slug": "wallet-lab-implementation",
    "title": "Wallet Reliability Lab 状态机实现",
    "capabilityIds": [
      "request-idempotency",
      "fund-state",
      "risk-authorization",
      "signer-boundary",
      "broadcast-finality",
      "reconciliation",
      "observability"
    ],
    "projectSlugs": [
      "web3-wallet-engineer-lab"
    ],
    "kind": "implementation",
    "status": "verified",
    "visibility": "public",
    "summary": "公开 Go 项目包含钱包领域 API、六个异常恢复模型和共享场景目录，不接触真实私钥与资产。",
    "verifiedAt": "2026-07-13",
    "url": "https://github.com/qianqiu0404/web3-wallet-engineer-lab",
    "failureSlugs": [
      "duplicate-request-id",
      "broadcast-result-unknown",
      "chain-success-local-failure",
      "credited-deposit-reorg",
      "evm-nonce-gap",
      "risk-signer-unavailable"
    ],
    "deliverySlugs": [
      "wallet-reliability-lab-v1"
    ]
  },
  {
    "slug": "wallet-lab-tests",
    "title": "Wallet Reliability Lab Go 断言",
    "capabilityIds": [
      "request-idempotency",
      "fund-state",
      "risk-authorization",
      "signer-boundary",
      "broadcast-finality",
      "reconciliation",
      "observability"
    ],
    "projectSlugs": [
      "web3-wallet-engineer-lab"
    ],
    "kind": "test",
    "status": "verified",
    "visibility": "public",
    "summary": "Go 测试断言重复请求只冻结一次、结果未知必须暂停、canonical 补偿幂等、reorg 写反向分录、replacement 只有一个终态以及关键依赖 fail-closed。",
    "verifiedAt": "2026-07-13",
    "command": "go test ./...",
    "url": "https://github.com/qianqiu0404/web3-wallet-engineer-lab/actions",
    "failureSlugs": [
      "duplicate-request-id",
      "broadcast-result-unknown",
      "chain-success-local-failure",
      "credited-deposit-reorg",
      "evm-nonce-gap",
      "risk-signer-unavailable"
    ],
    "deliverySlugs": [
      "wallet-reliability-lab-v1"
    ]
  }
]
