/* eslint-disable */
// Generated by scripts/generate-now.mjs. Do not edit by hand.
export interface NowSnapshot { updatedAt: string; headline: string; summary: string; developmentProjectSlugs: string[]; nextFocus: string[] }
export const nowSnapshot: NowSnapshot = {
  "updatedAt": "2026-07-24",
  "headline": "钱包工程，持续验证",
  "summary": "开发钱包基础设施，记录验证结果与安全研究。",
  "developmentProjectSlugs": [
    "exchange-wallet-system",
    "wallet-core",
    "wallet-reliability-lab",
    "tss-mpc"
  ],
  "nextFocus": [
    "跑通包含风控放行与失败注入的提现链路",
    "把签名安全研究转成首个 Wallet Lab 失败实验",
    "为 wallet-core 补充链资源与错误单位负向测试"
  ]
}
